eclipse-xtext/xtext

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/XbaseTypeComputer.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/XbaseJavaValidator.java
tests/org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/validation/XbaseValidationTest.xtend
tests/org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/validation/XbaseValidationTest.java

Change-Id: I9c14610b4c45756def62ed391d2fe8cf14899375
Signed-off-by: Miro Spönemann <miro.spoenemann@itemis.de>

[xbase] Bug 444972: warning on missing default for switch expression is suppressed for complete enum cases

---

plugins/org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/quickfix/XbaseQuickfixProvider.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/FeatureLinkingCandidate.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/XtendValidationTest.java
tests/org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
tests/org.eclipse.xtend.ide.tests/longrunning/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java

Transferred from Gerrit:
https://git.eclipse.org/r/#/c/43499/
Waiting for auto-build to verify...

[xbase] Bug 456888: Added validation and quick fix for private feature call in subclass context

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendJavaValidator.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/XtendValidationTest.java

Transferred from Gerrit:
https://git.eclipse.org/r/#/c/43500/
Waiting for auto-build to verify...

[xtend] Bug 460454: enhanced inheritance cycle detection such that containing types are considered

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/ActiveAnnotationContext.xtend
plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/ConstantExpressionsInterpreter.xtend
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/ActiveAnnotationContextProvider.java
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/ConstantExpressionsInterpreter.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/MoreActiveAnnotationsTest.xtend
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/MoreActiveAnnotationsTest.java

improved error logging for easier diagnosis next time

[461761] fixed annotation processors with static imports

---

plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/contentassist/ImplementMemberFromSuperAssist.java
plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/contentassist/XtendProposalProvider.java
plugins/org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/ui/util/JavaProjectSetupUtil.java
tests/org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
tests/org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTestBuilder.xtend
tests/org.eclipse.xtend.ide.tests/longrunning/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java
tests/org.eclipse.xtend.ide.tests/longrunning/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTestBuilder.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/AbstractXtendUITestCase.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/WorkbenchTestHelper.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/AbstractXtendContentAssistBugTest.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/Bug460093Test.xtend
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/contentassist/Bug460093Test.java

- Enabled content assist for overriding default methods
- Enhanced IDE test infrastructure to support different Java versions
Waiting for auto-build to verify...

[xtend] Bug 460093: Content assist for overriding default methods

---

plugins/org.eclipse.xtext.xbase.junit/src/org/eclipse/xtext/xbase/junit/formatter/FormatterTester.xtend
plugins/org.eclipse.xtext.xbase.junit/xtend-gen/org/eclipse/xtext/xbase/junit/formatter/FormatterTester.java

Change-Id: I9f9f78c4ff2fcec99c8f5555b8275ce6fcf3e7f4

[formatter 1.5] deprecated old formatter tester

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/actions/OutlineWithEditorLinker.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/impl/DocumentRootNode.java

Change-Id: Idc56cd32add8bf1e42d72cf2fc408fafb38f0dc1

[461111] Avoid logging when text -> outline sync fails

---

tests/org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/outline/OutlineNodeTest.java

Change-Id: Ic783cdbe9bc06f1748d5f8513ef3970a0e121664

[461111] fixed strange test expectation

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperJavaImpl.java

Change-Id: Ib55253074550456a6d526ee9f0a490d7dcf15f2e

[461018] don't log JavaModelExceptions in the build as errors

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/PackageFragmentRootWalker.java

Change-Id: I8362cf065ca5c7af2cd0d5749729e6ceed6adc22

[461019] detect missing jar files before trying to index their content

---

README.md

[readme] How to build xtext locally [Jenkins skip test]

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/PackageFragmentRootWalker.java

[461019] avoid API tooling trouble

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendJavaValidator.java

bug462217: update message for anonymous classes

---

plugins/org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/validation/ProjectAwareUniqueClassNameValidator.xtend
plugins/org.eclipse.xtext.xbase.ui/xtend-gen/org/eclipse/xtext/xbase/ui/validation/ProjectAwareUniqueClassNameValidator.java

[xbase] Changed the solution of #59 so we stay compatible with 2.8.0 API

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/ArrayListTextSegmentSet.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/FormattableDocument.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/TextSegmentSet.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/AbstractXtendFormatterTest.xtend
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/XtendFormatterBugTests.xtend
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/AbstractXtendFormatterTest.java
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendFormatterBugTests.java

[serializer] fixed Bug 461470: IAE in TextReplacerContext.withReplacer

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/TextReplacement.java

https://bugs.eclipse.org/bugs/show_bug.cgi?id=461966

[formatter] more preconditions to track down AFE in TextEdit.<init>

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/CollectionLiteralsTypeComputer.java

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=462754

[462754]: Fixed NPE

---

plugins/org.eclipse.xtend.ide/templates/templates.xml
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/ContentAssistInElseBlockTest.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/ContentAssistTest.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/ImplementSuperMemberAssistTest.java

Added some standard templates (more or less the same as in Java) plus create methods and template expressions.

[xtend] Bug 342396: Added templates for Xtend

---

examples/org.eclipse.xtend.examples/plugin.xml
examples/org.eclipse.xtext.xtext.ui.examples/org.eclipse.xtext.xtext.ui.examples/plugin.xml

[bug 381074] configure fileToOpen for materialized examples
formatting

[bug 381074] configure fileToOpen for materialized examples

---

plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/ui/generator/projectWizard/NewProjectWizard.xpt
plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/ui/generator/projectWizard/ProjectCreator.xpt

annotations
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=463068

[463068] SimpleProjectWizardFragment does not generate all @Override

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/XAnnotationExtensions.xtend
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/XAnnotationExtensions.java
tests/org.eclipse.xtend.core.tests/smoke-suites/org/eclipse/xtend/core/tests/smoke/FormatterSmokeSuite.java

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=463044

[463044]: Fixed CCE in annotation processor

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/jvmmodel/CacheVariableCompileStrategy.java
plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/AnnotationProcessor.xtend
plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/XAnnotationExtensions.xtend
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/AnnotationProcessor.java
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/XAnnotationExtensions.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/ErrorSafeExtensions.xtend
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/JvmModelGenerator.xtend
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/compiler/BrokenTypeRefDetector.java
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/compiler/JvmModelGenerator.java
tests/org.eclipse.xtend.core.tests/smoke-suites/org/eclipse/xtend/core/tests/smoke/FormatterSmokeSuite.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/XtendCompilerErrorHandlingTest.xtend
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/XtendCompilerErrorHandlingTest.java

Broken create extensions are now properly guarded
by the error-safe extension mechanism
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=462914

 [462914]: Fixed exception during compilation

---

plugins/org.eclipse.xtext.xbase.ui/META-INF/MANIFEST.MF
plugins/org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/annotations/ui/contentassist/XbaseWithAnnotationsProposalProvider.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/annotations/typesystem/XbaseWithAnnotationsTypeComputer.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/Bug439019Test.xtend
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/contentassist/Bug439019Test.java

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=463053

[463053]: Fixed content assist problem in annotation values

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/IResourceForEditorInputFactory.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/JavaClassPathResourceForIEditorInputFactory.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/ResourceForIEditorInputFactory.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocumentProvider.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/IStorage2UriMapper.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperJavaImpl.java
tests/org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJdtImplTest.java
tests/org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/hover/AbstractCompositeHoverTest.java
tests/org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/model/JavaClassPathResourceForIEditorInputFactoryTest.java

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=463258
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=463259

[463528]: Fixed exception when editor is opened for deleted archive

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/resource/DerivedStateAwareResource.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/resource/DerivedStateAwareResourceTest.java

don’t recomputed on error, but store exception in diagnostic (see also https://bugs.eclipse.org/bugs/show_bug.cgi?id=458620#c2)

[458620]: Fixed derived state error handling

---

plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/builder/UIResourceChangeRegistry.xtend
plugins/org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/builder/UIResourceChangeRegistry.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/UIResourceChangeRegistryTest.xtend
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/UIResourceChangeRegistryTest.java

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=463772

[463772]: Fixed synchronization problem in registry

---

plugins/org.eclipse.xtext.common.types.ui/.settings/.api_filters
plugins/org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/access/jdt/JdtBasedTypeFactory.java

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=463749

[463749]: Fixed I/O exception in JdtDeclaredTypeFactory

---

plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/grammarAccess/GrammarAccessFragment.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/EcoreUtil2.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/EcoreUtil2Test.java

https://bugs.eclipse.org/bugs/show_bug.cgi?id=463794

[xtext] Moved copy fully initialized flag logic to EcoreUtil2

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/outline/impl/AbstractOutlineNode.java

[462436] catch and handle runtime exception

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/folding/DefaultFoldedPosition.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/folding/DefaultFoldingRegionAcceptor.java

[464016] reverted incompatible API change

---

plugins/org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/debug/XbaseBreakpointDetailPaneFactory.java

This prevents CCE when other customizing is applied, too
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=464013

[464013]: Fixed unconditional cast to IBreakpoint

---

maven/org.eclipse.xtend.maven.plugin/.gitignore
maven/org.eclipse.xtext.maven.plugin/src/test/java/org/eclipse/xtext/maven/plugin/XtextGeneratorIT.java
maven/org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/bug463946/model/Bug463946.xcore
maven/org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/bug463946/pom.xml
maven/org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/bug463946/src/main/java/xcore/bug463946/Bug463946SuperImpl.java
maven/org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/bug463946/src/main/java/xcore/bug463946/Bug463946SuperIntf.java
plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendConfigurableIssueCodes.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/AbstractPendingLinkingCandidate.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/FeatureLinkingCandidate.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/SuspiciouslyOverloadedCandidate.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/XbaseConfigurableIssueCodes.java
tests/org.eclipse.xtend.core.tests/.gitignore

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=463946

[463946]: Fixed regression in validation for Xcore

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextEditor.java

[463940] added instanceof check as per comment https://bugs.eclipse.org/bugs/show_bug.cgi?id=463940#c3

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocument.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/resource/DerivedStateAwareResource.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/resource/XtextResource.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/xtext/PredicateUsesUnorderedGroupInspector.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextValidator.java

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=464029

 [464029]: Fixed NPE in grammar editor

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/AbstractProblemHover.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/ProblemAnnotationHover.java

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=464233

[464233]: Fixed NPE in hover

---

examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel/xtend-gen/org/eclipse/xtext/example/domainmodel/formatting2/DomainmodelFormatter.java
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.homeautomation/xtend-gen/org/eclipse/xtext/example/homeautomation/formatting2/RuleEngineFormatter.java
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/XtendFormatter.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.xtend
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/annotations/formatting2/XbaseWithAnnotationsFormatter.java
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.java
tests/org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/formatting/XbaseFormatterTest.xtend
tests/org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/formatting/XbaseFormatterTest.java

[formatter/xbase] format 'instanceof' expressions

---

plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/view/DerivedSourceView.java
plugins/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/smap/DerivedResourceMarkerCopier.java
plugins/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/trace/AbstractLocationInResource.java
plugins/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/trace/StorageAwareTrace.java
plugins/org.eclipse.xtext.common.types.shared.jdt38/src/org/eclipse/xtext/common/types/shared/jdt38/OriginalEditorSelector.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/generator/trace/TraceBasedOpenerContributor.java
plugins/org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/editor/XbaseEditorInputRedirector.xtend
plugins/org.eclipse.xtext.xbase.ui/xtend-gen/org/eclipse/xtext/xbase/ui/editor/XbaseEditorInputRedirector.java

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=462414

[462414]: Fixed exception after branch switch

---

plugins/org.eclipse.xtext.common.types.shared.jdt38/src/org/eclipse/xtext/common/types/shared/jdt38/OriginalEditorSelector.java

see https://xtext-builds.itemis.de/jenkins/job/xtend-ide-tests-maintenance-latest/39/#showFailuresLink

[462414]: Fixed regression with storage lookup

---

plugins/org.eclipse.xtend.lib/src/org/eclipse/xtend/lib/annotations/ToString.xtend
plugins/org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/ToString.java
plugins/org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/ToStringConfiguration.java
plugins/org.eclipse.xtend.lib/xtend-gen/org/eclipse/xtend/lib/annotations/ToStringProcessor.java
plugins/org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/util/ToStringBuilder.xtend
plugins/org.eclipse.xtext.xbase.lib/xtend-gen/org/eclipse/xtext/xbase/lib/util/ToStringBuilder.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/ToStringCompilerTest.xtend
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/ToStringCompilerTest.java

Signed-off-by: Stefan Oehme <stefan.oehme@itemis.de>

Make @ToString faster

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/ScopeStack.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/util/BoundTypeArgumentMerger.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug464264Test.xtend
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/linking/LinkingTest.java
tests/org.eclipse.xtend.core.tests/suites/org/eclipse/xtend/core/tests/compiler/CompilerSuite.java
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug464264Test.java

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=464264

[464264]: Detect incompatible lambda type

---

plugins/org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/StandaloneBuilder.xtend
plugins/org.eclipse.xtext.builder.standalone/xtend-gen/org/eclipse/xtext/builder/standalone/StandaloneBuilder.java
tests/org.eclipse.xtext.builder.tests/src-standalone/org/eclipse/xtext/builder/standalone/StandaloneBuilderInjectorProvider.java
tests/org.eclipse.xtext.builder.tests/src-standalone/org/eclipse/xtext/builder/standalone/StandaloneBuilderTest.java
tests/org.eclipse.xtext.builder.tests/src-standalone/org/eclipse/xtext/builder/standalone/TestableStandaloneBuilder.java
tests/org.eclipse.xtext.builder.tests/test-data/standalone/src-error/Bar.buildertestlanguage

[464663] maven build does not fails on validation error

---

tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/FormatterSerializerIntegrationTest.xtend
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/internal/FormatterSerializerIntegrationTest.java

This particularly tests the changes introduced by 
37ab5c4965c9920dd625dee77b4a6d5a64bf7638

[formatter/serializer] added integration test

---

plugins/org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/formatter/FormatterTester.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/AbstractFormatter2.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/HiddenRegionReplacer.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/IHiddenRegion.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/AbstractHiddenRegion.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/TextRegions.java
tests/org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/serializer/SerializerTest.java

[formatter] format leftover undefined hidden regions

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.xtend
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.java

[formatter/xbase] fixed a potential NPE detected by the smoke test

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/diagnostics/AbstractDiagnostic.java

[380232] getColumn() should return 0 for "for no information available"

---

plugins/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/EclipseResourceFileSystemAccess2.java
plugins/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/ParallelFileSystemAccess.xtend
plugins/org.eclipse.xtext.builder/xtend-gen/org/eclipse/xtext/builder/ParallelFileSystemAccess.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/generator/AbstractFileSystemAccess2.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/generator/IFileSystemAccessExtension4.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/generator/JavaIoFileSystemAccess.java
tests/org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/builderState/EclipseResourceFileSystemAccess2Test.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/JavaIoFileSystemAccessTest.java

This patch introduces interface IFileSystemAccessExtension4, which defines method exists().
Implemented new exists() method for FSA implementations.
Adding test code.
Change-Id: I4380ebdabe023d5abeb0219fc8f6b27c73e01d4d

[bug 443574] Added interface IFileSystemAccessExtension4

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/embedded/EmbeddedEditorModelAccess.java

- Update the model with no prefix and suffix
- Update the model with a given EObject and use the serializer to get the text
The latter is very useful for live synchronization with another EMF-based editor, e.g. a GMF editor.

[xtext] Added two methods to EmbeddedEditorModelAccess

---

examples/org.eclipse.xtend.examples-container/contents/xtend-annotation-examples/src/i18n/Externalized.xtend
examples/org.eclipse.xtend.examples-container/contents/xtend-annotation-examples/src/lazy/Lazy.xtend
examples/org.eclipse.xtend.examples-container/contents/xtend-annotation-examples/xtend-gen/i18n/ExternalizedProcessor.java
examples/org.eclipse.xtend.examples-container/contents/xtend-annotation-examples/xtend-gen/lazy/LazyProcessor.java

[bug430830] updated examples

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/jvmmodel/DispatchHelper.java
plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/jvmmodel/XtendJvmModelInferrer.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/DefaultReentrantTypeResolver.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.xtend
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.java

[dispatch] fixed bug with non explicit dispatch cases

---

plugins/org.eclipse.xtext.ui.ecore/src/org/eclipse/xtext/ui/ecore/EcoreEditorOpener.java

[bug465155] Skip select and reveal on URIs without fragment

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/AbstractLinkingCandidate.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/typesystem/Bug464760Test.xtend
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/Bug464760Test.java

[bug464760] fixed problem with typeless parameters

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/resource/BatchLinkableResource.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/resource/BatchLinkingService.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/PortableURIs.xtend
plugins/org.eclipse.xtext/xtend-gen/org/eclipse/xtext/resource/persistence/PortableURIs.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/typesystem/BatchLinkingServiceTest.xtend
tests/org.eclipse.xtend.core.tests/suites/org/eclipse/xtend/core/tests/linking/LinkingSuite.java
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/typesystem/BatchLinkingServiceTest.java

[bug 464762] Handle cases where resolve returns a detached proxy itself

---

plugins/org.eclipse.xtext.ui.shared/src/org/eclipse/xtext/ui/shared/internal/Activator.java

https://bugs.eclipse.org/bugs/show_bug.cgi?id=465225
Signed-off-by: Hendrik Eeckhaut <hendrik.eeckhaut@sigasi.com>

Reduce log level of JDT startup message from warning to info

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.xtend
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.java

https://bugs.eclipse.org/bugs/show_bug.cgi?id=460128

[460128|formatter/xbase] fixed a ConflictingRegionsException

---

examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/InjectorProviderCustom.java
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/XbaseIntegrationTest.xtend
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/tests/XbaseIntegrationTest.java
plugins/org.eclipse.xtext.xbase.junit/src/org/eclipse/xtext/xbase/compiler/CompilationTestHelper.java
plugins/org.eclipse.xtext.xbase.junit/src/org/eclipse/xtext/xbase/compiler/InMemoryJavaCompiler.xtend
plugins/org.eclipse.xtext.xbase.junit/src/org/eclipse/xtext/xbase/compiler/OnTheFlyJavaCompiler.java
plugins/org.eclipse.xtext.xbase.junit/src/org/eclipse/xtext/xbase/compiler/OnTheFlyJavaCompiler2.xtend
plugins/org.eclipse.xtext.xbase.junit/xtend-gen/org/eclipse/xtext/xbase/compiler/InMemoryJavaCompiler.java
plugins/org.eclipse.xtext.xbase.junit/xtend-gen/org/eclipse/xtext/xbase/compiler/JavaSource.java
plugins/org.eclipse.xtext.xbase.junit/xtend-gen/org/eclipse/xtext/xbase/compiler/OnTheFlyJavaCompiler2.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerTest.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerTestHelper.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/ActiveAnnotationsRuntimeTest.xtend
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/ActiveAnnotationsRuntimeTest.java
tests/org.eclipse.xtext.purexbase.tests/src/org/eclipse/xtext/purexbase/test/RuntimeInjectorProvider.java
tests/org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/EvaluationCompilerTest.java
tests/org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/JvmModelGeneratorTest.xtend
tests/org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/OnTheFlyJavaCompilerTest.java
tests/org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/compiler/JvmModelGeneratorTest.java

[tests] in-memory java compiler

---

plugins/org.eclipse.xtext.xbase.junit/src/org/eclipse/xtext/xbase/compiler/InMemoryJavaCompiler.xtend
plugins/org.eclipse.xtext.xbase.junit/xtend-gen/org/eclipse/xtext/xbase/compiler/InMemoryJavaCompiler.java
tests/org.eclipse.xtend.core.tests.java8/src/org/eclipse/xtend/core/tests/java8/compiler/Java8CompilerTest1.xtend
tests/org.eclipse.xtend.core.tests.java8/xtend-gen/org/eclipse/xtend/core/tests/java8/compiler/Java8CompilerTest1.java

[tests] set source and compliance level for java 8 tests

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/formatting2/XtendFormatter.xtend
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/XtendFormatter.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/AbstractSemanticRegionsFinder.java

Fix potential NPEs detected by smoke test

---

plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/contentassist/XtendProposalProvider.java
plugins/org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/xtext/ui/AbstractTypesProposalProvider.java
plugins/org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/xtext/ui/TypeMatchFilters.java
plugins/org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/contentassist/XbaseProposalProvider.java

This patch will add the methods isFilteredByPreference and isFilteredByDefault to TypeMatchFilters. isFilteredByPreference considers the JDT type filter preference.

[bug 378057] type filter

---

tests/org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/FileAsserts.xtend
tests/org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/RefactoringIntegrationTest.java
tests/org.eclipse.xtend.ide.tests/longrunning/xtend-gen/org/eclipse/xtend/ide/tests/refactoring/FileAsserts.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/WorkbenchTestHelper.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/builder/WorkspaceScenariosTest.xtend
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/codebuilder/AbstractBuilderTest.xtend
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/compiler/LineSeparatorConversionTest.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/ActiveAnnotationsProcessingInIDETest.xtend
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/JdtBasedProcessorProviderTest.xtend
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/MoreActiveAnnotationsTest.xtend
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/builder/WorkspaceScenariosTest.java
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/codebuilder/AbstractBuilderTest.java
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/ActiveAnnotationsProcessingInIDETest.java
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/JdtBasedProcessorProviderTest.java
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/MoreActiveAnnotationsTest.java

Please keep an eye out for unclosed input streams =)

Fixed a bunch of test failures on windows

---

intellij/org.eclipse.xtend.idea/META-INF/plugin.xml
intellij/org.eclipse.xtend.idea/src/fileTemplates/internal/Xtend Annotation Type.xtend.ft
intellij/org.eclipse.xtend.idea/src/fileTemplates/internal/Xtend Annotation Type.xtend.html
intellij/org.eclipse.xtend.idea/src/fileTemplates/internal/Xtend Class.xtend.ft
intellij/org.eclipse.xtend.idea/src/fileTemplates/internal/Xtend Class.xtend.html
intellij/org.eclipse.xtend.idea/src/fileTemplates/internal/Xtend Enum.xtend.ft
intellij/org.eclipse.xtend.idea/src/fileTemplates/internal/Xtend Enum.xtend.html
intellij/org.eclipse.xtend.idea/src/fileTemplates/internal/Xtend Interface.xtend.ft
intellij/org.eclipse.xtend.idea/src/fileTemplates/internal/Xtend Interface.xtend.html
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/actions/NewXtendFileAction.xtend
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/actions/XtendCreateFromTemplateHandler.xtend
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/actions/NewXtendFileAction.java
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/actions/XtendCreateFromTemplateHandler.java

[IDEA] added ‘New Xtend Type’ wizard

---

intellij/org.eclipse.xtext.idea/META-INF/plugin.xml
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/highlighting/ProblemXtextFileHighlightFilter.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/highlighting/ProblemXtextFileHighlightFilter.java

Change-Id: I19bcbc4983e3a59de9cec426b4fdb082c962649b

[idea][highlighting] Highlight bogus files in the project view

---

intellij/build.gradle
intellij/org.eclipse.xtend.idea.tests/src/org/eclipse/xtend/idea/LightXtendTest.xtend
intellij/org.eclipse.xtend.idea.tests/src/org/eclipse/xtend/idea/psi/JvmPsiClassTest.xtend
intellij/org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/LightXtendTest.java
intellij/org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/psi/JvmPsiClassTest.java
intellij/org.eclipse.xtext.idea.builder/src/org/eclipse/xtext/idea/build/client/DaemonConnector.xtend
intellij/org.eclipse.xtext.idea.builder/xtend-gen/org/eclipse/xtext/idea/build/client/DaemonConnector.java
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/resource/AbstractScopeBasedSelectable.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/resource/ScopeBasedResourceDescriptions.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/psi/PsiModelAssociations.java
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/psi/impl/BaseXtextFile.java
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/psi/impl/XtextFileAwareEObjectDescription.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/containers/ResolveScopeBasedContainer.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/resource/AbstractScopeBasedSelectable.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/resource/ScopeBasedResourceDescriptions.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/resource/impl/ProjectScopeBasedResourceDescriptions.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/psi/impl/XtextFileAwareEObjectDescription.java
intellij/org.eclipse.xtext.xbase.idea/src/org/eclipse/xtext/xbase/idea/jvmmodel/PsiJvmModelAssociator.xtend
intellij/org.eclipse.xtext.xbase.idea/src/org/eclipse/xtext/xbase/idea/types/JvmTypesShortNamesCache.xtend
intellij/org.eclipse.xtext.xbase.idea/src/org/eclipse/xtext/xbase/idea/types/access/StubJvmTypeProvider.xtend
intellij/org.eclipse.xtext.xbase.idea/src/org/eclipse/xtext/xbase/idea/types/psi/JvmPsiClasses.xtend
intellij/org.eclipse.xtext.xbase.idea/src/org/eclipse/xtext/xbase/idea/types/psi/JvmTypesElementFinder.xtend
intellij/org.eclipse.xtext.xbase.idea/src/org/eclipse/xtext/xbase/idea/types/psi/impl/JvmPsiClassImpl.xtend
intellij/org.eclipse.xtext.xbase.idea/src/org/eclipse/xtext/xbase/idea/types/psi/impl/StubBasedJvmPsiClass.xtend
intellij/org.eclipse.xtext.xbase.idea/xtend-gen/org/eclipse/xtext/xbase/idea/types/JvmTypesShortNamesCache.java
intellij/org.eclipse.xtext.xbase.idea/xtend-gen/org/eclipse/xtext/xbase/idea/types/access/StubJvmTypeProvider.java
intellij/org.eclipse.xtext.xbase.idea/xtend-gen/org/eclipse/xtext/xbase/idea/types/psi/JvmPsiClasses.java
intellij/org.eclipse.xtext.xbase.idea/xtend-gen/org/eclipse/xtext/xbase/idea/types/psi/JvmTypesElementFinder.java
intellij/org.eclipse.xtext.xbase.idea/xtend-gen/org/eclipse/xtext/xbase/idea/types/psi/impl/StubBasedJvmPsiClass.java

builder
Change-Id: I6ff34aff4fa782683860872a63cb517150872bac

[idea] Filter out psi classes for java files generated by the external

---

intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/XtendIdeaModule.java
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/DefaultIdeaModule.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/psi/impl/BaseXtextFile.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/DefaultIdeaModule.java

Change-Id: I3681abcb90d285e8689b74a235f7c5e5e7fe3e5a

[idea][xtend] Invalidate a resource set only on a structural change

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/IssueUtil.java

Set -1 instead of null as a default value for offset and length of an issue

Fix possible NPE found by FindBugs

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/compare/CompareInputResourceProvider.java

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=465572

[465572] Fixed NPE in compare editor

---

intellij/org.eclipse.xtext.idea.builder/src/org/eclipse/xtext/idea/build/net/Protocol.xtend
intellij/org.eclipse.xtext.idea.builder/xtend-gen/org/eclipse/xtext/idea/build/net/Protocol.java

Change-Id: I5965cf0ca96efc96366fb267dd2a8ecf03f46f53

Fixed failing idea test

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/DirtyStateEditorSupport.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/editor/DirtyStateEditorSupportTest.xtend
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/editor/DirtyStateEditorSupportTest.java

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=464483

[464483] Mark ResourceSet as outdated on forceReconcile request

---

plugins/org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/editor/XbaseDocumentProvider.java

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=465752

[465752] Don’t throw NPE if trace points into void

---

plugins/org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/incremental/FilesAndURIs.xtend
plugins/org.eclipse.xtext.builder.standalone/xtend-gen/org/eclipse/xtext/builder/standalone/incremental/FilesAndURIs.java
tests/org.eclipse.xtext.builder.tests/src-standalone/org/eclipse/xtext/builder/standalone/incremental/FilesAndURIsTest.xtend
tests/org.eclipse.xtext.builder.tests/xtend-gen/org/eclipse/xtext/builder/standalone/incremental/FilesAndURIsTest.java

Change-Id: If0ade2702ec2e9e228e8cfae98b9a845ee528ec7

[idea] builder should not delete source folders

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/tasks/Task.xtend
plugins/org.eclipse.xtext/xtend-gen/org/eclipse/xtext/tasks/Task.java

Signed-off-by: muelder <andreas.muelder@itemis.de>

removed 'final' from Tasks to allow addition of custom data via delegation

---

plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/XtendResourceUiServiceProvider.java
plugins/org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/ui/util/JavaProjectSetupUtil.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/ResourceStorageFacade.xtend
plugins/org.eclipse.xtext/xtend-gen/org/eclipse/xtext/resource/persistence/ResourceStorageFacade.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/builder/WorkspaceScenariosTest.xtend
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/builder/WorkspaceScenariosTest.java

[xtend] don’t index xtend sources from jars (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=466667)

---

plugins/org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/access/jdt/JdtBasedTypeFactory.java
tests/org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/access/jdt/SourceBasedJdtTypeProviderTest.java

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=464973

[464973] Fixed NPE in JdtBasedTypeFactory

---

plugins/org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseHoverConfiguration.java
plugins/org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseInformationControl.java

This should probably fix bug 464759

[464759] Use SynchronizedXtextResourceSet in hover

---

plugins/org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/access/jdt/JdtBasedTypeFactory.java

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=467313

[467313] More NPE guards in JdtBasedTypeFactory

---

intellij/org.eclipse.xtext.core.idea.tests/testData/parsing/unorderedGroups/backtrackingBug325745ParserTest/Valid_01.txt
intellij/org.eclipse.xtext.core.idea.tests/testData/parsing/unorderedGroups/backtrackingBug325745ParserTest/Valid_02.txt
intellij/org.eclipse.xtext.core.idea.tests/testData/parsing/unorderedGroups/backtrackingBug325745ParserTest/Valid_03.txt
intellij/org.eclipse.xtext.core.idea.tests/testData/parsing/unorderedGroups/backtrackingBug325745ParserTest/Valid_04.txt
intellij/org.eclipse.xtext.core.idea.tests/testData/parsing/unorderedGroups/backtrackingBug325745ParserTest/Valid_05.txt
intellij/org.eclipse.xtext.core.idea.tests/testData/parsing/unorderedGroups/backtrackingBug325745ParserTest/Valid_06.txt
intellij/org.eclipse.xtext.core.idea.tests/testData/parsing/unorderedGroups/backtrackingBug325745ParserTest/Valid_07.txt
intellij/org.eclipse.xtext.core.idea.tests/testData/parsing/unorderedGroups/backtrackingBug325745ParserTest/Valid_08.txt
intellij/org.eclipse.xtext.core.idea.tests/testData/parsing/unorderedGroups/backtrackingBug325745ParserTest/Valid_09.txt
intellij/org.eclipse.xtext.core.idea.tests/testData/parsing/unorderedGroups/backtrackingBug325745ParserTest/Valid_10.txt
intellij/org.eclipse.xtext.core.idea.tests/testData/parsing/unorderedGroups/backtrackingParserTest/Exception_01.txt
intellij/org.eclipse.xtext.core.idea.tests/testData/parsing/unorderedGroups/backtrackingParserTest/NoException_01.txt
intellij/org.eclipse.xtext.idea.tests/src/org/eclipse/xtext/idea/tests/parsing/AbstractLanguageParsingTestCase.xtend
intellij/org.eclipse.xtext.idea.tests/src/org/eclipse/xtext/idea/tests/parsing/XtextResourceAsserts.xtend
intellij/org.eclipse.xtext.idea.tests/xtend-gen/org/eclipse/xtext/idea/tests/parsing/AbstractLanguageParsingTestCase.java
intellij/org.eclipse.xtext.idea.tests/xtend-gen/org/eclipse/xtext/idea/tests/parsing/XtextResourceAsserts.java
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/annotation/IssueAnnotator.java
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/util/CancelProgressIndicator.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/psi/impl/BaseXtextFile.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/util/CancelProgressIndicator.java

Change-Id: I0bf26560fe41722f48f3c4ee421e8d8981d39688

[idea] Resolve lazy cross references with a lock on the resource set

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/syntaxcoloring/TextAttributeProvider.java

[467478] clear the attributes map within the async operation

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/jvmmodel/CacheVariableCompileStrategy.java
plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/jvmmodel/XtendCompileStrategies.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/XbaseCompiler.java

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=468909

[468909] Fixed NPE when compiling with incomplete classpath

---

web/org.eclipse.xtext.web.generator/src/org/eclipse/xtext/web/generator/ClientHighlightingFragment.xtend
web/org.eclipse.xtext.web.generator/xtend-gen/org/eclipse/xtext/web/generator/ClientHighlightingFragment.java
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/XtextServiceDispatcher.xtend
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/XtextServiceDispatcher.java

Fix problem when there are no keywords left after filtering
Extract method to create ServiceDescriptor in XtextServiceDispatcher to make it easier to create custom services

[WEB] Fix problem when there are no keywords left after filtering

---

tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug456883Test.xtend
tests/org.eclipse.xtend.core.tests/suites/org/eclipse/xtend/core/tests/compiler/CompilerSuite.java
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug456883Test.java

[456883] Tests for already fixed bug

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/validation/Issue.java

[469069] fixed NPE

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/XtendGenerator.xtend
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/compiler/XtendGenerator.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/XtendCompilerErrorHandlingTest.xtend
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/XtendCompilerErrorHandlingTest.java

[469068] don’t fail with NPE on private top level types

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/jvmmodel/JvmTypesBuilder.java

https://bugs.eclipse.org/bugs/show_bug.cgi?id=468641

Bug 468641 [xbase] issues with JvmTypesBuilder toGetter/toSetter

---

intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/build/XtextAutoBuilderComponent.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/build/XtextAutoBuilderComponent.java

Change-Id: I253db026b7d1ca12a078506ed81896f0bdfe0a61

[idea auto build] Run read action to access the module graph

---

plugins/org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IterableExtensions.java
plugins/org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/IteratorExtensions.java

Signed-off-by: Andreas Heiduk <asheiduk@gmail.com>

Fix copy&paste error in forall Javadoc

---

intellij/org.eclipse.xtend.idea.tests/src/org/eclipse/xtend/idea/autoedit/AbstractCStyleLanguageAutoEditTest.xtend
intellij/org.eclipse.xtend.idea.tests/src/org/eclipse/xtend/idea/autoedit/AutoEditTest.xtend
intellij/org.eclipse.xtend.idea.tests/src/org/eclipse/xtend/idea/autoedit/XtendAutoEditTest.xtend
intellij/org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/autoedit/AbstractCStyleLanguageAutoEditTest.java
intellij/org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/autoedit/AutoEditTest.java
intellij/org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/autoedit/XtendAutoEditTest.java
intellij/org.eclipse.xtend.idea/META-INF/plugin.xml
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/editorActions/XtendAutoEditHandler.xtend
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/editorActions/XtendAutoEditHandler.java
intellij/org.eclipse.xtext.idea/META-INF/plugin.xml
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/editorActions/AutoEditBlock.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/editorActions/DefaultAutoEditHandler.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/editorActions/IdeaAutoEditHandler.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/editorActions/IdeaAutoEditHandlerExtension.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/editorActions/XtextAutoEditBackspaceHandler.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/editorActions/XtextAutoEditEnterHandler.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/editorActions/XtextAutoEditTypedHandler.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/editorActions/AutoEditBlock.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/editorActions/AutoEditBlockRegion.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/editorActions/DefaultAutoEditHandler.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/editorActions/IdeaAutoEditHandler.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/editorActions/IdeaAutoEditHandlerExtension.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/editorActions/XtextAutoEditBackspaceHandler.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/editorActions/XtextAutoEditEnterHandler.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/editorActions/XtextAutoEditTypedHandler.java

handlers
Change-Id: I24ead91b968340f67411fcac47ce33eda9d97201

[idea] Added an extension point to register language specific auto edit

---

plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/compiler/batch/BootClassLoader.java
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/compiler/batch/internal/AlternateJdkLoader.java
plugins/org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/quickfix/CodeBuilderQuickfix.java
plugins/org.eclipse.xtext.ui.shared/src/org/eclipse/xtext/ui/shared/internal/ListenerRegistrar.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperJavaImpl.java
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/AbstractXtendCompilerTest.java
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/ImmutableAnnotationTest.java

https://bugs.eclipse.org/bugs/show_bug.cgi?id=471574

[471574] Spurious linking errors when refering to library models in external jars

---

plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/XtendFormatter.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.xtend
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/annotations/formatting2/XbaseWithAnnotationsFormatter.java
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.java
tests/org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/formatting/XbaseFormatterTest.xtend
tests/org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/formatting/XbaseFormatterTest.java

Task-Url: https://bugs.eclipse.org/bugs/show_bug.cgi?id=471239

471239: [formatter/xbase] format cast end postfix xpressions

---

web/org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-stateless.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/index.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-stateless.html
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/XtextServiceDispatcher.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/contentassist/ContentAssistService.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/formatting/FormattingService.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/model/DocumentSynchronizer.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/model/IXtextWebDocument.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/model/PreComputedServices.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/model/UpdateDocumentService.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/model/XtextWebDocument.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/model/XtextWebDocumentAccess.java
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/persistence/ResourcePersistenceService.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/syntaxcoloring/HighlightingService.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/validation/ValidationService.xtend
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/XtextServiceDispatcher.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/contentassist/ContentAssistService.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/formatting/FormattingService.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/model/AbstractPreComputedService.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/model/DocumentSynchronizer.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/model/IXtextWebDocument.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/model/PreComputedServiceRegistry.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/model/UpdateDocumentService.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/model/XtextWebDocument.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/persistence/ResourcePersistenceService.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/syntaxcoloring/HighlightingService.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/validation/ValidationService.java
web/org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/UpdateDocumentTest.xtend
web/org.eclipse.xtext.web/src/test/xtend-gen/org/eclipse/xtext/web/server/test/UpdateDocumentTest.java

Change-Id: I4c21af3d46588ab363d7129ccccd5f465cf992ae

[web] redesigned pre-computation of service results

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/GeneratorConfigProvider.xtend
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/compiler/GeneratorConfigProvider.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/preferences/IPreferenceValuesProvider.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/preferences/PreferenceValuesByLanguage.xtend
plugins/org.eclipse.xtext/xtend-gen/org/eclipse/xtext/preferences/PreferenceValuesByLanguage.java

So we can finally configure issue severities in the Gradle plugin and other standalone clients

Allow installing preferences into the resourceSet

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hyperlinking/SingleHoverShowingHyperlinkPresenter.xtend
plugins/org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/editor/hyperlinking/SingleHoverShowingHyperlinkPresenter.java
plugins/org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/debug/ConditionPage.java

Also made hyperlink presenters more failsafe

[472013] Added NPE guard on breakpoint condition page

---

plugins/org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/ui/util/IResourcesSetupUtil.java
plugins/org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/ui/util/JavaProjectSetupUtil.java
tests/org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/builder/XtendBuilderParticipantTest.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/Bug457681Test.xtend
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/JdtBasedProcessorProviderTest.xtend
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/MoreActiveAnnotationsTest.xtend
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/Bug457681Test.java
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/JdtBasedProcessorProviderTest.java
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/MoreActiveAnnotationsTest.java
tests/org.eclipse.xtext.builder.tests/src-longrunning/org/eclipse/xtext/builder/impl/IntegrationTest.java
tests/org.eclipse.xtext.builder.tests/src-longrunning/org/eclipse/xtext/builder/impl/SimpleProjectsIntegrationTest.java
tests/org.eclipse.xtext.builder.tests/src-longrunning/org/eclipse/xtext/builder/impl/XtextBuilderParticipantTest.java
tests/org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/AbstractBuilderTest.java
tests/org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/Bug355821Test.java
tests/org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/BuilderParticipantTest.java
tests/org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/BuilderPerformanceTest.java
tests/org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/ui/notification/RebuildDependentResourcesTest.java

They fail with an explicit build request. To be analysed 
in 2.9 branch

[471384] A few tests depend on auto building

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/service/MethodBasedModule.java

https://bugs.eclipse.org/bugs/show_bug.cgi?id=380403
Signed-off-by: Dietmar Stoll <eclipse.etc@dietmar-stoll.de>

Fix bug 380403

---

plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/autoedit/RichStringPartionIndentationStrategy.xtend
plugins/org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/autoedit/RichStringPartionIndentationStrategy.java
tests/org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/autoedit/AutoEditTest.java

don't swallow windows newlines in RichString autoedit

---

plugins/org.eclipse.xtext.ui/.settings/.api_filters
plugins/org.eclipse.xtext.xbase.junit/.settings/.api_filters
plugins/org.eclipse.xtext.xbase/.settings/.api_filters
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/buildpath/XtendLibClasspathAdderTest.java
tests/org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/Bug334456Test.java
tests/org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/Bug355821Test.java

[471384] Even more tests that rely on auto builds

---

intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/highlighting/SemanticHighlightVisitor.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/highlighting/SemanticHighlightVisitor.java
plugins/org.eclipse.xtend.ide.common/META-INF/MANIFEST.MF
plugins/org.eclipse.xtend.ide.common/src/org/eclipse/xtend/ide/common/highlighting/XtendHighlightingCalculator.java
plugins/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/syntaxcoloring/DefaultSemanticHighlightingCalculator.java
plugins/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/syntaxcoloring/ISemanticHighlightingCalculator.java
plugins/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/syntaxcoloring/MergingHighlightedPositionAcceptor.java
plugins/org.eclipse.xtext.ui.codetemplates.ui/src/org/eclipse/xtext/ui/codetemplates/ui/highlighting/SemanticHighlighter.java
plugins/org.eclipse.xtext.ui/deprecated/org/eclipse/xtext/ui/editor/syntaxcoloring/DefaultSemanticHighlightingCalculator.java
plugins/org.eclipse.xtext.ui/deprecated/org/eclipse/xtext/ui/editor/syntaxcoloring/ISemanticHighlightingCalculator.java
plugins/org.eclipse.xtext.ui/deprecated/org/eclipse/xtext/ui/editor/syntaxcoloring/MergingHighlightedPositionAcceptor.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/syntaxcoloring/HighlightingReconciler.java
plugins/org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
plugins/org.eclipse.xtext.xbase.ide/src/org/eclipse/xtext/xbase/ide/highlighting/XbaseHighlightingCalculator.java
plugins/org.eclipse.xtext.xbase.ui/deprecated/org/eclipse/xtext/xbase/ui/highlighting/XbaseHighlightingCalculator.java
plugins/org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/editor/syntaxcoloring/SemanticHighlightingCalculator.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/highlighting/XtendHighlightingCalculatorTest.java
tests/org.eclipse.xtext.ui.codetemplates.tests/src/org/eclipse/xtext/ui/codetemplates/tests/HighlightingTest.java
tests/org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/syntaxcoloring/DeprecatedMergingHighlightedPositionAcceptorTest2.java
tests/org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/syntaxcoloring/TaskHighlightingTest.xtend
tests/org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/syntaxcoloring/TaskHighlightingTest.java
tests/org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/SemanticHighlightingTest.java
web/org.eclipse.xtext.web.example.statemachine.ide/src/org/eclipse/xtext/web/example/statemachine/ide/StatemachineImageDescriptionProvider.xtend
web/org.eclipse.xtext.web.example.statemachine.ide/src/org/eclipse/xtext/web/example/statemachine/ide/StatemachineSemanticHighlightingCalculator.xtend
web/org.eclipse.xtext.web.example.statemachine.ide/xtend-gen/org/eclipse/xtext/web/example/statemachine/ide/StatemachineImageDescriptionProvider.java
web/org.eclipse.xtext.web.example.statemachine.ide/xtend-gen/org/eclipse/xtext/web/example/statemachine/ide/StatemachineSemanticHighlightingCalculator.java
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/syntaxcoloring/HighlightingService.xtend
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/syntaxcoloring/HighlightingService.java

This extension of the API would allow better performance in the web context, especially if computing semantic highlighting is expensive.

[ide] Added cancel indicator to new semantic highlighting API

---

intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/editorActions/XtendAutoEditBlockProvider.xtend
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/editorActions/XtendAutoEditBlockProvider.java
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/DefaultIdeaModule.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/actionSystem/DataContextExtensions.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/editorActions/AbstractAutoEditBlockProvider.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/editorActions/AbstractIndentableAutoEditBlock.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/editorActions/DefaultAutoEditBlockProvider.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/formatting/CodeStyleSettingsIndentationInformation.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/DefaultIdeaModule.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/actionSystem/DataContextExtensions.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/editorActions/AbstractAutoEditBlockProvider.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/editorActions/AbstractIndentableAutoEditBlock.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/editorActions/DefaultAutoEditBlockProvider.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/formatting/CodeStyleSettingsIndentationInformation.java

Change-Id: Ic90e9cc51c87b2ceca450aa99e9758cd638574ee

[idea] Use code style settings to generate indentation

---

intellij/org.eclipse.xtend.idea.tests/src/org/eclipse/xtend/idea/autoedit/AbstractCStyleLanguageAutoEditTest.xtend
intellij/org.eclipse.xtend.idea.tests/src/org/eclipse/xtend/idea/autoedit/XtendAutoEditTest.xtend
intellij/org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/autoedit/AbstractCStyleLanguageAutoEditTest.java
intellij/org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/autoedit/XtendAutoEditTest.java
intellij/org.eclipse.xtext.idea.tests/src/org/eclipse/xtext/idea/tests/AbstractAutoEditTest.xtend
intellij/org.eclipse.xtext.idea.tests/xtend-gen/org/eclipse/xtext/idea/tests/AbstractAutoEditTest.java
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/formatting/DefaultXtextBlock.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/formatting/SyntheticXtextBlock.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/formatting/DefaultXtextBlock.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/formatting/SyntheticXtextBlock.java

Change-Id: Iea85cceb572982fbfbf7b12825dd2f082148fc89

[idea] Fixed indentation adjustment between two blocks

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/resource/SynchronizedXtextResourceSet.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/resource/XtextResourceSet.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/resource/XtextResourceSetTest.xtend
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/AbstractResourceSetTest.java
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/AbstractXtextResourceSetTest.java
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/NullResource.java
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/ResourceSetTest.java
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/SynchronizedXtextResourceSetTest.java
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/resource/XtextResourceSetTest.java

Resource.setURI could access and modifiy the 
resource set in an unsynced manner

[462047] Fixed unsynchronized modification in SyncXtextResourceSet

---

intellij/org.eclipse.xtend.idea.tests/src/org/eclipse/xtend/idea/autoedit/XtendAutoEditTest.xtend
intellij/org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/autoedit/XtendAutoEditTest.java
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/editorActions/XtendTokenSetProvider.xtend
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/editorActions/XtendTokenSetProvider.java

Change-Id: I28b4a27aff9e08a3279160c82ffb4a2e31ad9ba3

[idea][xtend] Disabled auto completion of french quotes in rich strings' comments

---

maven/org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/ClassFileDebugInfoExtractor.java
maven/org.eclipse.xtend.maven.plugin/src/test/java/org/eclipse/xtend/maven/XtendInstallDebugInfoMojoIT.java

The tests were still based on the assumption that all
trace regions are relevant for debugging. Since this
information is now persisted, the expectations had to
be adjusted too.

[473079] Fixed mvn test expectations

---

intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/trace/VirtualFileBasedTrace.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/trace/VirtualFileBasedTrace.java
plugins/org.eclipse.xtext.builder/plugin.xml
plugins/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/trace/DebugTraceBasedRegion.java
plugins/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/trace/TraceEditor.java
plugins/org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/ui/trace/AbstractTraceWithoutStorage.java
plugins/org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/ui/trace/FolderAwareTrace.java
plugins/org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/ui/trace/TraceForTypeRootProvider.java
plugins/org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/ui/trace/ZipFileAwareTrace.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/generator/trace/AbstractEclipseTrace.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/generator/trace/StorageAwareTrace.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/output/AppendableBasedTraceRegion.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/AbstractTraceRegion.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/AbstractTraceRegionToString.xtend
plugins/org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/internal/AbstractTrace.java
plugins/org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/AbstractTraceRegionToString.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/SimpleTrace.java
tests/org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/trace/BaseTraceTest.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/trace/TraceRegionToStringTest.xtend
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/generator/trace/TraceRegionToStringTest.java
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/generator/trace/TraceRegionToStringTester.java
tests/org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/output/CompilerTraceTest.java

[trace] visualize traces in toString()

---

docs/org.eclipse.xtend.doc/META-INF/MANIFEST.MF
docs/org.eclipse.xtext.doc/META-INF/MANIFEST.MF
features/org.eclipse.xtend.gwt.feature/feature.xml
features/org.eclipse.xtext.build.feature/buckminster.cspex
features/org.eclipse.xtext.build.feature/feature.xml
features/org.eclipse.xtext.gwt.feature/feature.xml
releng/org.eclipse.xtext.releng/local-xtext-build.launch

[releng] Do not include xbase.lib into xbase.gwt feature Bug 474195

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/AbstractTraceRegionToString.xtend
plugins/org.eclipse.xtext/xtend-gen/org/eclipse/xtext/generator/trace/AbstractTraceRegionToString.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/trace/TraceRegionToStringTest.xtend
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/generator/trace/TraceRegionToStringTest.java

[trace] fixed a minor issue in trace#toString()

---

intellij/org.eclipse.xtend.idea.tests/src/org/eclipse/xtend/idea/config/XtendLibraryManagerTest.xtend
intellij/org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/config/XtendLibraryManagerTest.java
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/config/XtendLibraryDescription.xtend
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/config/XtendLibraryManager.xtend
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/config/XtendSupportConfigurable.xtend
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/intentions/XtendIntentionsProvider.xtend
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/config/XtendLibraryDescription.java
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/config/XtendLibraryManager.java
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/config/XtendSupportConfigurable.java
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/intentions/XtendIntentionsProvider.java
releng/org.eclipse.xtext.releng/distrobuilder/p2patchDslPackage.sh

[idea] Add Xtend Library quickfix. WIP - Bug 474218 Bug 474216 

---

tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/unorderedGroups/GrammarSerializerTest.java

[idea] fix IdeaGrammarSerializerTest

---

intellij/org.eclipse.xtend.idea.tests/src/org/eclipse/xtend/idea/autoedit/XtendAutoEditTest.xtend
intellij/org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/autoedit/XtendAutoEditTest.java
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/formatting/XtendChildAttributesProvider.xtend
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/formatting/XtendChildAttributesProvider.java
intellij/org.eclipse.xtext.idea.tests/src/org/eclipse/xtext/xbase/idea/formatting/AbstractXbaseAutoEditTest.xtend
intellij/org.eclipse.xtext.idea.tests/xtend-gen/org/eclipse/xtext/xbase/idea/formatting/AbstractXbaseAutoEditTest.java
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/formatting/DefaultChildAttributesProvider.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/xbase/idea/formatting/XbaseChildAttributesProvider.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/formatting/DefaultChildAttributesProvider.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/xbase/idea/formatting/XbaseChildAttributesProvider.java

Change-Id: Ice18e0d944db360dca08857392e8af3659a57ec0

[idea][bug 473917] fixed indentation before 'return'

---

tests/org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/autoedit/AutoEditInCodeBlockTest.java

Change-Id: I33d7d4cfd7c209064bd4df2cf41b78216e4e6118

[bug 473978] adjusted expectations of the failing test

---

plugins/org.eclipse.xtext.xbase.junit/src/org/eclipse/xtext/xbase/junit/evaluation/AbstractXbaseEvaluationTest.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/FeatureCallCompiler.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/XbaseCompiler.java
tests/org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/CompilerTests2.xtend
tests/org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/compiler/CompilerTests2.java

Change-Id: Ibe68a5f012267acf96f55e69300aa0761bb5f42e

[xbase][bug 466974] Create a variable for an argument if it has side effects and one of following arguments requires a variable declaration also

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/IssueCodes.java
plugins/org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/validation/ValidationTestHelper.java
plugins/org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/quickfix/JavaTypeQuickfixes.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/DefaultXbaseRuntimeModule.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/annotations/DefaultXbaseWithAnnotationsRuntimeModule.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/annotations/validation/UnresolvedAnnotationTypeAwareMessageProvider.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/annotations/validation/UnresolvedFeatureCallTypeAwareMessageProvider.xtend
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/annotations/validation/UnresolvedFeatureCallTypeAwareMessageProvider.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/FeatureCallValidationTest.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/XImportSectionValidationTest.xtend
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/XImportSectionValidationTest.java
tests/org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
tests/org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTestBuilder.xtend
tests/org.eclipse.xtend.ide.tests/longrunning/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java
tests/org.eclipse.xtend.ide.tests/longrunning/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTestBuilder.java

[validation] Some minor fixes regarding PR #440

---

plugins/org.eclipse.xtext.util/src/org/eclipse/xtext/util/MergeableManifest.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/AbstractReusableActiveAnnotationTests.xtend
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/AbstractReusableActiveAnnotationTests.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/AbstractXtendUITestCase.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/WorkbenchTestHelper.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/ActiveAnnotationsProcessingInIDETest.xtend
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/macros/MoreActiveAnnotationsTest.xtend
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/ActiveAnnotationsProcessingInIDETest.java
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/macros/MoreActiveAnnotationsTest.java

ActiveAnnotationsProcessingInIDETest from 280s to 30s

[tests][misc] Fixed remove Export Package. Reduced test execution time.

---

plugins/org.eclipse.xtext.xbase.junit/src/org/eclipse/xtext/xbase/junit/evaluation/AbstractXbaseEvaluationTest.java
plugins/org.eclipse.xtext.xbase.junit/testdata/testdata/ClassWithVarArgs.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/interpreter/impl/XbaseInterpreter.java

Change-Id: I60c6264fc32e600e26c0900a613b0fe403fbb60e

[bug 474784] Fixed assignment of a single value as a varargs argument

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/typesystem/XtendReentrantTypeResolver.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/AbstractPendingLinkingCandidate.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/ConstructorLinkingCandidate.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/XbaseIntegrationTest.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/FeatureCallValidationTest.java

Change-Id: If06af1be4ba46b8a25e91b228dd97e6fdb6cf9f3

[bug 474502] Infer varargs constructors for an anonymous class when necessary

---

intellij/org.eclipse.xtend.idea/src/liveTemplates/Xtend.xml

Change-Id: Id33772a2e425fa5b8101398cf772b582246f69a5

[xtend][idea][bug 475132] Added template proposals for def, val, var and etc.

---

intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/config/XtendLibraryManager.xtend
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/config/XtendSupportConfigurable.xtend
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/config/XtendLibraryManager.java
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/config/XtendSupportConfigurable.java

Change-Id: I44e785d35f15dd4c729a614412f16537451bae80

[idea][bug 475118] install Xtend library only when a project is initialized

---

intellij/org.eclipse.xtend.idea.tests/src/org/eclipse/xtend/idea/completion/XtendCompletionTest.xtend
intellij/org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/completion/XtendCompletionTest.java
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/xbase/idea/completion/XbaseCompletionContributor.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/xbase/idea/completion/XbaseLookupElementWeigher.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/xbase/idea/completion/XbaseCompletionContributor.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/xbase/idea/completion/XbaseLookupElementWeigher.java

Change-Id: If62115d981c284fc56bb4e72061aa116dbb3b0cc

[idea][bug 475130] Propose java types in the expression context

---

intellij/org.eclipse.xtend.idea.tests/src/org/eclipse/xtend/idea/autobuild/IdeaIntegrationTest.xtend
intellij/org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/autobuild/IdeaIntegrationTest.java
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/build/BuildEvent.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/build/XtextAutoBuilderComponent.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/build/BuildEvent.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/build/XtextAutoBuilderComponent.java

Change-Id: I1504078cbea9f000eb97f77eb3f6b22a74322981

[idea][bug 475122] Trigger the auto build for change property events

---

plugins/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/BuilderParticipant.java
plugins/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/EclipseResourceFileSystemAccess2.java
plugins/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/XtextBuilder.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/ResourceUtil.java
tests/org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/AbstractBuilderParticipantTest.java
tests/org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/AbstractFSSynchronizationTest.xtend
tests/org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/BuilderParticipantTest.java
tests/org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/FSSynchronizationTest.java
tests/org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/tests/MyGenerator.xtend
tests/org.eclipse.xtext.builder.tests/xtend-gen/org/eclipse/xtext/builder/impl/AbstractFSSynchronizationTest.java
tests/org.eclipse.xtext.builder.tests/xtend-gen/org/eclipse/xtext/builder/tests/MyGenerator.java

Change-Id: I05fb24d9d8fc40c67ba84d662077b15f3f94f7a3

[bug 475117] prevent async refresh when possible

---

intellij/org.eclipse.xtend.idea.tests/src/org/eclipse/xtend/idea/psi/XtextPsiReferenceTest.xtend
intellij/org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/psi/XtextPsiReferenceTest.java
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/linking/lazy/CrossReferenceDescription.java
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/psi/impl/PsiEObjectImpl.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/psi/impl/PsiEObjectReference.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/psi/impl/XtextPsiReferenceImpl.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/psi/impl/PsiEObjectImpl.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/psi/impl/PsiEObjectReference.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/psi/impl/XtextPsiReferenceImpl.java

Change-Id: Ib617d0bdb551dc2506e9123ac77e70427e1a4cd7

[idea][bug 472791] Use a significant offset of XtextPsiReference as a text offset of PsiEObject

---

intellij/org.eclipse.xtext.idea/META-INF/plugin.xml
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/execution/TraceBasedExceptionFilterFactory.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/execution/TraceBasedExceptionFilter.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/execution/TraceBasedExceptionFilterFactory.java

[idea][bug 475906] Provided TraceBasedExceptionFilter to fix navigation

---

intellij/org.eclipse.xtend.idea.tests/src/org/eclipse/xtend/idea/config/GradleBuildFileUtilTest.xtend
intellij/org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/config/GradleBuildFileUtilTest.java
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/config/GradleBuildFileUtility.xtend
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/config/XtendGradleFrameworkSupportProvider.xtend
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/config/XtendLibraryDescription.xtend
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/config/XtendLibraryManager.xtend
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/config/XtendSupportConfigurable.xtend
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/config/GradleBuildFileUtility.java
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/config/XtendGradleFrameworkSupportProvider.java
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/config/XtendLibraryManager.java
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/config/XtendSupportConfigurable.java
intellij/org.eclipse.xtext.idea.tests/src/org/eclipse/xtext/idea/tests/LibraryUtil.xtend
intellij/org.eclipse.xtext.idea.tests/src/org/eclipse/xtext/idea/tests/LightToolingTest.xtend
intellij/org.eclipse.xtext.idea.tests/src/org/eclipse/xtext/idea/tests/debug/AbstractDebuggerTestCase.xtend
intellij/org.eclipse.xtext.idea.tests/src/org/eclipse/xtext/idea/tests/parsing/AbstractLanguageParsingTestCase.xtend
intellij/org.eclipse.xtext.idea.tests/src/org/eclipse/xtext/idea/tests/parsing/NodeModelPrinter.xtend
intellij/org.eclipse.xtext.idea.tests/src/org/eclipse/xtext/idea/tests/parsing/XtextResourceAsserts.xtend
intellij/org.eclipse.xtext.idea.tests/src/org/eclipse/xtext/xbase/idea/formatting/AbstractXbaseAdjustLineIndentTest.xtend

[idea][gradle] Better support for gradle and android projects

---

plugins/org.eclipse.xtext.common.types.shared.jdt38/src/org/eclipse/xtext/common/types/shared/jdt38/OriginalEditorSelector.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/editor/XbaseEditorOpenClassFileTest.xtend
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/navigation/OpenEditorTest.java
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/editor/XbaseEditorOpenClassFileTest.java

- support nested types
- don’t respond on name conflicts (i.e. multiple matches per simple name)

[476292] Improve editor selector (WIP - tests missing)

---

plugins/org.eclipse.xtext.common.types.ui/.settings/.api_filters
plugins/org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/access/jdt/WorkingCopyOwnerProvider.java
plugins/org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
plugins/org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/descriptions/EObjectDescriptionBasedStubGenerator.java
plugins/org.eclipse.xtext.java/src/org/eclipse/xtext/java/resource/IndexAwareNameEnvironment.xtend
plugins/org.eclipse.xtext.java/xtend-gen/org/eclipse/xtext/java/resource/IndexAwareNameEnvironment.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/common/types/access/jdt/WorkingCopyOwnerProviderTest.xtend
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/common/types/access/jdt/WorkingCopyOwnerProviderTest.java
tests/org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/descriptions/EObjectDescriptionBasedStubGeneratorTest.java

Generate stubs for nested types as well
Change-Id: Idd1a071bfcb1790a621515e1ed038e0faf9eba71

[476810] [linking] method unreachable from Xtend

---

plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/javaconverter/ConversionProblemsDialog.java

[j2x] Allow to include / exclude multiple files from conversion at once

---

plugins/org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/descriptions/EObjectDescriptionBasedStubGenerator.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/common/types/access/jdt/WorkingCopyOwnerProviderTest.xtend
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/common/types/access/jdt/WorkingCopyOwnerProviderTest.java
tests/org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/descriptions/EObjectDescriptionBasedStubGeneratorTest.java

- fix failing test
- don't generate static on top-level class

[476810] cleanup

---

plugins/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/builderState/AbstractBuilderState.java
plugins/org.eclipse.xtext.ui.shared/src/org/eclipse/xtext/ui/shared/internal/JavaCoreListenerRegistrar.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperJavaImpl.java

Revert "[475368] Another approach to solve the deadlock issue"

---

intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/build/XtextAutoBuilderComponent.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/build/XtextAutoBuilderComponent.java

On project init (when the state gets loaded), the modules are not populated, so I changed the map to use the module names.

[477182] fixed NPE and IAE, on null entries and non existing projects.

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/WizardConfig.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorNaming.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/idea/IdeaPluginGenerator.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/WizardConfig.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorNaming.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/idea/IdeaPluginGenerator.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.java
plugins/org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/NewXtextProjectWizard.java
plugins/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend
plugins/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/UiProjectDescriptor.xtend
plugins/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/UiTestProjectDescriptor.xtend
plugins/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WizardConfiguration.xtend
plugins/org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
plugins/org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/UiProjectDescriptor.java
plugins/org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/UiTestProjectDescriptor.java
plugins/org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WizardConfiguration.java

Split test project into runtime and ui tests
don't overwrite IDEA plugin.xml
don't create a Tycho build if the user asked for PDE

More generator improvements

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/parser/AntlrGrammarWithTokens.xpt
plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/parser/antlr/AbstractAntlrGeneratorFragment.java
plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/parser/antlr/AntlrOptions.java
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/AbstractAntlrGrammarGenerator.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/AntlrOptions.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/AbstractAntlrGrammarGenerator.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/AntlrOptions.java

Also fixed grammar fragment for Xtend

Added option to discard unused rules

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/WizardConfig.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/WizardConfig.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/junit/Junit4Fragment2.java
plugins/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend
plugins/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend
plugins/org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
plugins/org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java

I can now successfully create a Maven-Layout project and run the tests with Maven

[generator] fix test code location for maven layout

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/JvmModelGenerator.xtend

Revert "Fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=478024"

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextValidator.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextValidationTest.java

Fixed validation of actions in fragments

---

plugins/org.eclipse.xtext.xbase/generator/org/eclipse/xtext/xbase/GenerateXbase.java
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/WizardConfig.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/WizardConfig.java

also add a validation so that this doesn't go unnoticed again

set rootpath and basename in GenerateXbase

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/GenerateXtend.mwe2
plugins/org.eclipse.xtend.ide/plugin.xml_gen
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/outline/QuickOutlineFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/outline/QuickOutlineFragment2.java
plugins/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend
plugins/org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
tests/org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.eclipsePlugin/org.xtext.example.eclipsePlugin/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2
tests/org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2
tests/org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2

Migration of the 'QuickOutlineFragment'

[xtext generator] Migration of the 'QuickOutlineFragment'

---

plugins/org.eclipse.xtend.ide/src-gen/org/eclipse/xtend/ide/AbstractXtendUiModule.java
plugins/org.eclipse.xtend.ide/src-gen/org/eclipse/xtend/ide/contentassist/AbstractXtendProposalProvider.java
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/contentAssist/ContentAssistFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/contentAssist/ContentAssistFragment2.java

replaced a usage of hashSet by arrayList to avoid ordering changes in generated code

[xtext generator] Minor improvement in 'ContentAssistFragement2'

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/WizardConfig.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/WizardConfig.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/generator/WizardConfigTest.xtend
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/generator/WizardConfigTest.java
tests/org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/lib/FunctionCompositionTest.xtend
tests/org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/lib/FunctionCompositionTest.java
web/org.eclipse.xtext.web.example.jetty/build.gradle

Also:
- adjusted orion download URI in example
- updated gradle preferences

[wizard] Fixed test project names with mvn config

---

intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/xbase/idea/completion/XbaseCompletionContributor.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/xbase/idea/imports/DocumentAwareRewritableImportSectionFactory.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/xbase/idea/completion/XbaseCompletionContributor.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/xbase/idea/imports/DocumentAwareRewritableImportSectionFactory.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/imports/RewritableImportSection.java

[idea][bug 473723] Use '\n' as a line separator for the rewritable

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/AntlrContentAssistGrammarGenerator.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/AntlrContentAssistGrammarGenerator.java

[antlr grammar generation] partial revert in 'compileParserMembers'

---

plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/parser/antlr/AntlrGrammarComparator.xtend
plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/parser/antlr/XtextAntlrGeneratorComparisonFragment.xtend
plugins/org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/parser/antlr/AntlrGrammarComparator.java
plugins/org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/parser/antlr/XtextAntlrGeneratorComparisonFragment.java

[antlr grammar comparison] integrated lexer evaluation in case of separate grammars

---

maven/org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/XtextGenerator.java

This is the same as the xtend-maven-plugin already.
When models are copied to target/classes, they used to be on the
classpath of the next generator run. This may lead to hard-to-diagnose
errors like "Foo cannot be cast to Foo".

Bug 474868 xtext-maven-plugin should ignore target/classes

---

intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/build/XtextAutoBuilderComponent.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/build/XtextAutoBuilderComponent.java

Previously when canceled, the no processed events were added to the tail of the queue. As a result the order got inverted (newer events were preceding older ones). This could potentially have a bad effect when you have add and delete events for the same URI.
This change keeps track of the order and also ensures that deleted URIs don’t show up in the changed set and vice versa.

[idea] keep order of events

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ImplicitFragment.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/generator/GeneratorFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/idea/IdeaPluginGenerator.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/AbstractAntlrGrammarGenerator.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/AntlrContentAssistGrammarGenerator.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/XtextAntlrGeneratorFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/scoping/ImportNamespacesScopingFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/contentAssist/ContentAssistFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ImplicitFragment.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/generator/GeneratorFragment2.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/idea/IdeaPluginGenerator.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/AbstractAntlrGrammarGenerator.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/AntlrContentAssistGrammarGenerator.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/XtextAntlrGeneratorFragment2.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/scoping/ImportNamespacesScopingFragment2.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/contentAssist/ContentAssistFragment2.java

contains a few bug fixes, supplements for java stubs, and some cosmetics to reduce (white space) differences to the formerly generated code

generator fixes & improvements

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ImplicitFragment.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ImplicitFragment.java

Do you agree with that kind of dependency clean-up?

[xtext generator] fine-tuning of '...xtend.lib' dependency addition in 'ImplicitFragment'

---

plugins/org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.xtend
plugins/org.eclipse.xtext.xtext.ui/xtend-gen/org/eclipse/xtext/xtext/ui/wizard/project/AdvancedNewProjectPage.java

https://bugs.eclipse.org/bugs/show_bug.cgi?id=481291

[wizard][generator] ide project has compile errors Bug 481291

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/GenerateXtend.mwe2
plugins/org.eclipse.xtext.xbase/generator/org/eclipse/xtext/xbase/GenerateXbase.java
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/StandardLanguage.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorLanguage.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorResourceSetInitializer.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/StandardLanguage.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorLanguage.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorResourceSetInitializer.java

[generator] StandaloneSetup{loadedResource=""} --> referencedResource=""

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/JavaProjectFactory.java

[xtext.ui] cannot determine JRE container Bug 467391

---

xtext-website/community.html

I have added entries for the EMF-IncQuery and VIATRA Eclipse projects to the Xtext Community page.
In addition, I have removed some + signs from an other entry that probably caused the strange plus signs at the top of the table.

Added EMF-IncQuery and VIATRA to community page

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorResourceSetInitializer.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorResourceSetInitializer.java

Also: make return types explicit

[482514] Fixed ConcurrentModException

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/AbstractExternalFolderAwareFragment.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/AbstractExternalFolderAwareFragment.java

Helps to implement generator fragments that write
to other locations on the disk, e.g to generate
plugins for other editors

[xtext][generator] Additional abstract base class

---

web/org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-resource.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-resource.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-resource.html
web/org.eclipse.xtext.web/src/main/js/xtext/xtext-ace.js
web/org.eclipse.xtext.web/src/main/js/xtext/xtext-codemirror.js
web/org.eclipse.xtext.web/src/main/js/xtext/xtext-orion.js

https://bugs.eclipse.org/bugs/show_bug.cgi?id=482161

[web] Added API to remove all Xtext services and listeners from an editor

---

web/org.eclipse.xtext.web.example.jetty/src/main/java/org/eclipse/xtext/web/example/jetty/StatemachineWebModule.xtend
web/org.eclipse.xtext.web.example.jetty/src/main/java/org/eclipse/xtext/web/example/jetty/resource/StatemachineContentTypeProvider.xtend
web/org.eclipse.xtext.web.example.jetty/src/main/xtend-gen/org/eclipse/xtext/web/example/jetty/StatemachineWebModule.java
web/org.eclipse.xtext.web.example.jetty/src/main/xtend-gen/org/eclipse/xtext/web/example/jetty/resource/StatemachineContentTypeProvider.java
web/org.eclipse.xtext.web.example.statemachine/src/org/eclipse/xtext/web/example/statemachine/generator/StatemachineGenerator.xtend
web/org.eclipse.xtext.web.example.statemachine/xtend-gen/org/eclipse/xtext/web/example/statemachine/generator/StatemachineGenerator.java
web/org.eclipse.xtext.web.servlet/src/main/java/org/eclipse/xtext/web/servlet/XtextServlet.xtend
web/org.eclipse.xtext.web.servlet/src/main/xtend-gen/org/eclipse/xtext/web/servlet/XtextServlet.java
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/XtextServiceDispatcher.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/generator/GeneratorResult.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/generator/GeneratorService.xtend
web/org.eclipse.xtext.web/src/main/js/xtext/ServiceBuilder.js
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/XtextServiceDispatcher.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/generator/GeneratorResult.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/generator/GeneratorService.java
web/org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/GeneratorTest.xtend
web/org.eclipse.xtext.web/src/test/xtend-gen/org/eclipse/xtext/web/server/test/GeneratorTest.java

Changed concept for accessing multiple generator artifacts: include the desired artifact in the request instead of returning all artifacts at once.

[web] More convenient access to generated artifacts

---

plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/serializer/SerializerFragment.xtend
plugins/org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/serializer/SerializerFragment.java
plugins/org.eclipse.xtext.xbase/generator/org/eclipse/xtext/xbase/GenerateXbase.java
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/serializer/SerializerFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/serializer/SerializerFragment2.java

see https://bugs.eclipse.org/bugs/show_bug.cgi?id=481865

[oldserializerfragment#481865] Support Deprecated ContextEObject

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/AbstractAntlrGrammarGenerator.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/AbstractAntlrGrammarWithActionsGenerator.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/AbstractAntlrGrammarGenerator.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/AbstractAntlrGrammarWithActionsGenerator.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/generator/AntlrGeneratorFragmentTest.xtend
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/generator/AntlrGeneratorFragmentTest.java

[482677] fixed issue in determining required parenthesizes of generated ANTLR grammars

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/resource/generic/XMLEncodingProvider.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/resource/ecore/XMLEncodingProviderTest.java

[409069] - Exception by XMLEncodingProvider

---

intellij/org.eclipse.xtext.xtext.idea/src/org/eclipse/xtext/idea/wizard/XtextModuleBuilder.xtend
intellij/org.eclipse.xtext.xtext.idea/src/org/eclipse/xtext/idea/wizard/XtextWizardStep.xtend
intellij/org.eclipse.xtext.xtext.idea/xtend-gen/org/eclipse/xtext/idea/wizard/XtextModuleBuilder.java
plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/batch/XtendBatchCompiler.java
plugins/org.eclipse.xtext.util/src/org/eclipse/xtext/util/JavaVersion.java

[idea] [wizard] Configure generator with selected JDK

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/serializer/SerializerFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/serializer/SerializerFragment2.java

this suppresses the symptoms of 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=482840 and
https://bugs.eclipse.org/bugs/show_bug.cgi?id=479400

[serializerFragment] avoid generating duplicate methods

---

intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/build/BuildProgressReporter.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/build/BuildProgressReporter.java

https://bugs.eclipse.org/bugs/show_bug.cgi?id=483095

[idea] Added guard for NPE in PhpStorm Bug 483095

---

plugins/org.eclipse.xtext.util/src/org/eclipse/xtext/util/formallang/NfaUtil.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/analysis/ContextPDAProvider.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/analysis/GrammarConstraintProvider.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/analysis/SemanticSequencerNfaProvider.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/analysis/SyntacticSequencerPDAProvider.java

https://bugs.eclipse.org/bugs/show_bug.cgi?id=481861

[serializer#481861] remove possible causes for nondeterminism

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/analysis/SerializationContext.java

see
https://bugs.eclipse.org/bugs/show_bug.cgi?id=482033

[serializer#482033] NPE at SerializationContext.forChild(...)

---

gradle/maven-deployment.gradle
maven/org.eclipse.xtext.xtext/pom.xml
plugins/org.eclipse.xtext.xtext.generator/pom.xml

Bug 483338 - Different versions of equinox.common dependency

---

web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/generator/GeneratorService.xtend
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/generator/GeneratorService.java

This allows to omit the DEFAULT_OUTPUT prefix in the 'artifact' parameter.

[web] Fixed search for generator artifacts

---

intellij/org.eclipse.xtend.idea/META-INF/plugin.xml
intellij/org.eclipse.xtext.idea.example.entities.ide/META-INF/MANIFEST.MF
intellij/org.eclipse.xtext.idea.example.entities.ide/pom.xml
intellij/org.eclipse.xtext.idea.example.entities.tests/META-INF/MANIFEST.MF
intellij/org.eclipse.xtext.idea.example.entities.tests/pom.xml
intellij/org.eclipse.xtext.idea.example.entities.ui/META-INF/MANIFEST.MF
intellij/org.eclipse.xtext.idea.example.entities.ui/pom.xml
intellij/org.eclipse.xtext.idea.example.entities/META-INF/MANIFEST.MF
intellij/org.eclipse.xtext.idea.example.entities/pom.xml
intellij/org.eclipse.xtext.idea.sdomain.tests/META-INF/MANIFEST.MF
intellij/org.eclipse.xtext.idea.sdomain.tests/pom.xml
intellij/org.eclipse.xtext.idea.sdomain.ui/META-INF/MANIFEST.MF
intellij/org.eclipse.xtext.idea.sdomain.ui/pom.xml
intellij/org.eclipse.xtext.idea.sdomain/META-INF/MANIFEST.MF
intellij/org.eclipse.xtext.idea.sdomain/pom.xml
intellij/org.eclipse.xtext.idea/META-INF/plugin.xml
intellij/org.eclipse.xtext.xtext.idea/META-INF/plugin.xml
web/org.eclipse.xtext.web.example.statemachine.ide/META-INF/MANIFEST.MF
web/org.eclipse.xtext.web.example.statemachine.ide/pom.xml
web/org.eclipse.xtext.web.example.statemachine/META-INF/MANIFEST.MF
web/org.eclipse.xtext.web.example.statemachine/pom.xml

2.9.0-SNAPSHOT is no longer the correct version to use

Fixed remaining version numbers on maintenance

---

web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/contentassist/ContentAssistService.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/hover/HoverService.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/persistence/ResourceBaseProviderImpl.xtend
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/contentassist/ContentAssistService.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/hover/HoverService.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/persistence/ResourceBaseProviderImpl.java

- Simplified sorting code in ContentAssistService
- Handled case of empty classes array in hover HTML
- Added check for invalid paths in ResourceBaseProviderImpl

[web] Small improvements

---

plugins/org.eclipse.xtext.xbase.ide/META-INF/MANIFEST.MF
plugins/org.eclipse.xtext.xbase/META-INF/MANIFEST.MF

Signed-off-by: Dennis Huebner <dennis.huebner@gmail.com>

Bug 484222 - xtext.xbase dependency on equinox.common obsolete

---

xtext-website/documentation/303_runtime_concepts.md

I noted that the parameter of the Check annotation is missing from the xtext docs. I added some docs.

Docs for parameters of Check

---

tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/serializer/GrammarConstraintProviderFeatureTest.xtend
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/serializer/GrammarConstraintProviderFeatureTest.java

[serializer] added another test case for grammar constraint provider

---

intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/build/IdeaOutputConfigurationProvider.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/facet/AbstractFacetConfiguration.java
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/facet/GeneratorFacetForm.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/xbase/idea/facet/XbaseFacetConfiguration.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/xbase/idea/facet/XbaseFacetForm.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/build/IdeaOutputConfigurationProvider.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/facet/GeneratorFacetForm.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/xbase/idea/facet/XbaseFacetConfiguration.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/xbase/idea/facet/XbaseFacetForm.java

Change-Id: Idce8fadc25afb9f70b81133d4b7bf6ccd6e0a667

[bug 483931] Relativize output paths even for non existent folders

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/naming/QualifiedName.java

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=484215 and original pull request #868

Bug 484215 - [builder] Performance and OOM problems with QualifiedName while building large projects

---

gradle/intellij-project.gradle
intellij/org.eclipse.xtend.idea.tests/src/org/eclipse/xtend/idea/macro/IdeaProcessorProviderTest.xtend
intellij/org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/macro/IdeaProcessorProviderTest.java
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/macro/IdeaProcessorProvider.xtend
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/macro/IdeaProcessorProvider.java
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/util/FilteringClassLoader.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/util/FilteringClassLoader.java

Change-Id: I105f93caac280fa9d1b8f011d08b5cfd027f2b9a

[bug 482380] Isolate Annotation Processor Classloader from annotations on plug-in class path

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/util/NodeModelUtils.java

fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=485211

[485211] fix getLinAndColumn for RootNodes

---

xtext-website/documentation/303_runtime_concepts.md

https://bugs.eclipse.org/bugs/show_bug.cgi?id=483580

[483580] IEncodingProvider documentation is incorrect

---

intellij/org.eclipse.xtend.idea.tests/src/org/eclipse/xtend/idea/javaconverter/IdeaJavaConverterTest.xtend
intellij/org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/javaconverter/IdeaJavaConverterTest.java
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/actions/ConvertJavaCodeAction.xtend
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/javaconverter/ConvertJavaCodeHandler.xtend
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/actions/ConvertJavaCodeAction.java
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/javaconverter/ConvertJavaCodeHandler.java

Signed-off-by: Dennis Huebner <dennis.huebner@gmail.com>

Bug 476557 - [j2x] Check that module has SDK before enable j2x action

---

intellij/org.eclipse.xtend.idea.tests/src/org/eclipse/xtend/idea/config/GradleBuildFileUtilTest.xtend
intellij/org.eclipse.xtend.idea.tests/xtend-gen/org/eclipse/xtend/idea/config/GradleBuildFileUtilTest.java
intellij/org.eclipse.xtend.idea/META-INF/plugin.xml
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/config/GradleBuildFileUtility.xtend
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/config/MavenArtifact.xtend
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/config/MavenUtility.xtend
intellij/org.eclipse.xtend.idea/src/org/eclipse/xtend/core/idea/config/XtendLibraryConfigurator.xtend
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/config/GradleBuildFileUtility.java
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/config/MavenArtifact.java
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/config/MavenUtility.java
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/config/XtendLibraryConfigurator.java
intellij/org.eclipse.xtend.idea/xtend-gen/org/eclipse/xtend/core/idea/framework/XtendGradleFrameworkSupportProvider.java
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/util/PlatformUtil.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/util/PlatformUtil.java
intellij/org.eclipse.xtext.xtext.idea/META-INF/plugin.xml
intellij/org.eclipse.xtext.xtext.idea/src/org/eclipse/xtext/idea/wizard/XtextWizardStep.xtend
intellij/org.eclipse.xtext.xtext.idea/xtend-gen/org/eclipse/xtext/idea/wizard/XtextWizardStep.java
plugins/org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.xtend
plugins/org.eclipse.xtext.util/xtend-gen/org/eclipse/xtext/util/XtextVersion.java

Signed-off-by: Dennis Huebner <dennis.huebner@gmail.com>

Bug 486262 - [idea] Make maven plugin dependency optional

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/scoping/impl/ImportedNamespaceAwareLocalScopeProvider.java

Reverts eclipse/xtext#931Michael will create a new PR for that

Revert "[409003] ImportedNamespaceAwareLocalScopeProvider public getQNC"

---

xtext-website/community.html

I've added a row for RAPID-ML, an API description language developed by RepreZen.  Please contact me at ted.epstein@reprezen.com if you have any questions.

Add RAPID-ML Language

---

tests/org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/BuilderParticipantTest.java

Fixed Test that does not clean up afterwards

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/findReferences/ReferenceFinder.java

Solves https://bugs.eclipse.org/bugs/show_bug.cgi?id=488589
Signed-off-by: Andreas Heiduk <asheiduk@gmail.com>

[488589] Fix NPE in ReferenceFinder.findLocalReferencesFromElement

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreInterpretationContext.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformerTest.xtend
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/ecoreInference/Xtext2EcoreTransformerTest.java

Change-Id: I58de6791ef95e907528bede10124a788ee6b13b8

[bug 479161] Invalidate boolean assignments of fragments

---

web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/XtextServiceDispatcher.xtend
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/XtextServiceDispatcher.java
web/org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/Bug489571Test.xtend
web/org.eclipse.xtext.web/src/test/xtend-gen/org/eclipse/xtext/web/server/test/Bug489571Test.java

Change-Id: I4591b5eee99a8155a494e7223137b80dd816e491

[bug 489571] Formatting service should use default formatting preferences

---

web/org.eclipse.xtext.web/src/main/js/xtext/ServiceBuilder.js
web/org.eclipse.xtext.web/src/test/js/ServiceBuilderTest.js

Change-Id: Ie71785b2f457a7cecd54b8229595d6f8d0c36115

[bug 489575] ServiceBuilder.mergeOptions should not expose defaultOptions

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.java

Change-Id: I102e9567bba1f604072f608e089d6fd363e48a40

[bug 489574][web][jetty] Don't lock static resources on Windows

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/linking/lazy/SyntheticLinkingSupport.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/linking/Bug437669Test.java

Change-Id: I4d723aa426e4f09a48cbee2187e98c5d60900920

[bug 489547] Allow to provide offset and length for SyntheticLinkingLeafNode

---

examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.arithmetics.ui/src/org/eclipse/xtext/example/arithmetics/ui/quickfix/ArithmeticsQuickfixProvider.xtend
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.arithmetics.ui/xtend-gen/org/eclipse/xtext/example/arithmetics/ui/quickfix/ArithmeticsQuickfixProvider.java
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel.ui/src/org/eclipse/xtext/example/domainmodel/ui/quickfix/DomainmodelQuickfixProvider.java
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.fowlerdsl.ui/src/org/eclipse/xtext/example/fowlerdsl/ui/quickfix/StatemachineQuickfixProvider.xtend
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.fowlerdsl.ui/xtend-gen/org/eclipse/xtext/example/fowlerdsl/ui/quickfix/StatemachineQuickfixProvider.java
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.homeautomation.ui/src/org/eclipse/xtext/example/homeautomation/ui/quickfix/RuleEngineQuickfixProvider.xtend
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.homeautomation.ui/xtend-gen/org/eclipse/xtext/example/homeautomation/ui/quickfix/RuleEngineQuickfixProvider.java
intellij/org.eclipse.xtext.idea.example.entities.ui/src/org/eclipse/xtext/idea/example/entities/ui/quickfix/EntitiesQuickfixProvider.xtend
intellij/org.eclipse.xtext.idea.example.entities.ui/xtend-gen/org/eclipse/xtext/idea/example/entities/ui/quickfix/EntitiesQuickfixProvider.java
intellij/org.eclipse.xtext.idea.sdomain.ui/src/org/eclipse/xtext/idea/sdomain/ui/quickfix/SDomainQuickfixProvider.xtend
intellij/org.eclipse.xtext.idea.sdomain.ui/xtend-gen/org/eclipse/xtext/idea/sdomain/ui/quickfix/SDomainQuickfixProvider.java
plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/ui/generator/quickfix/QuickfixProviderFragment.xpt
plugins/org.eclipse.xtext.purexbase.ui/src/org/eclipse/xtext/purexbase/ui/quickfix/PureXbaseQuickfixProvider.xtend
plugins/org.eclipse.xtext.purexbase.ui/xtend-gen/org/eclipse/xtext/purexbase/ui/quickfix/PureXbaseQuickfixProvider.java
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/quickfix/QuickfixProviderFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/quickfix/QuickfixProviderFragment2.java
tests/org.eclipse.xtext.testlanguages.ui/src/org/eclipse/xtext/testlanguages/noJdt/ui/quickfix/NoJdtTestLanguageQuickfixProvider.java
tests/org.eclipse.xtext.xbase.testlanguages.ui/src/org/eclipse/xtext/xbase/testlanguages/ui/quickfix/XImportSectionTestLangQuickfixProvider.xtend
tests/org.eclipse.xtext.xbase.testlanguages.ui/xtend-gen/org/eclipse/xtext/xbase/testlanguages/ui/quickfix/XImportSectionTestLangQuickfixProvider.java

Change-Id: Ie5c5527041f30f9f0ea9e4a2a4c3ae1f987b190f

[489133] Fix link to QuickFix docs

---

plugins/org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/access/jdt/JdtBasedTypeFactory.java

Change-Id: I13317deeb0718c04df42341c415a73b37fbc53f6

[490530] Change variable type of abortOnMissingSource

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/mwe/Reader.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/mwe/ReaderTest.java

[356750] addPath can also take a comma-separated list of paths

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.java

[490975] Fixed wrong Constructor in Java Ui Module Generator

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperJavaImpl.java
tests/org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJavaImplTest.xtend
tests/org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJavaImplTest.java

[490680] Handle deletion of two projects at the same time correctly

---

plugins/org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/imports/InteractiveUnresolvedTypeResolver.java
plugins/org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/imports/TypeChooser.java
tests/org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/imports/OrganizeImportsTest.xtend
tests/org.eclipse.xtend.ide.tests/longrunning/xtend-gen/org/eclipse/xtend/ide/tests/imports/OrganizeImportsTest.java

Change-Id: I95536cf610efd7d4808c841209fddf051205db43

[421967] Consider JDT Type Filter

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/XbaseCompiler.java
tests/org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/CompilerTests2.xtend
tests/org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/compiler/CompilerTests2.java

Task-Url: https://bugs.eclipse.org/bugs/show_bug.cgi?id=489037

489037: check isVariableDeclarationRequired for assignment's args

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/tokens/ValueSerializer.java

Signed-off-by: Moritz Eysholdt <moritz.eysholdt@typefox.io>

fixup for 40dbb428c55fcf150f901bfd14b64d854ec0589b

---

plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/generator/GeneratorFragment.xpt
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/generator/GeneratorFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/generator/GeneratorFragment2.java

Task-Url: https://bugs.eclipse.org/bugs/show_bug.cgi?id=491411

491411: Generated generator.Main uses createFileURI

---

xtext-website/documentation/310_eclipse_support.md

See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=490796

Document the newProjectWizardForEclipse fragment

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.java
plugins/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend
plugins/org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java
web/org.eclipse.xtext.web.example.jetty/build.gradle
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-resource-multi.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-resource.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-stateless.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-static-multi.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/ace-statemachine-static.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-resource-multi.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-resource.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-stateless.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-static-multi.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/codemirror-statemachine-static.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-entities-resource.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-entities-static.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-autogenerate.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-resource-multi.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-resource.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-stateless.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-static-multi.html
web/org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-static.html
web/org.eclipse.xtext.web.example.jetty/src/main/xtend-gen/org/eclipse/xtext/web/example/jetty/MyXtextServlet.java
web/org.eclipse.xtext.web.example.statemachine/src/org/eclipse/xtext/web/example/statemachine/StatemachineRuntimeModule.xtend
web/org.eclipse.xtext.xbase.web/.settings/org.eclipse.jdt.core.prefs

* Project wizard
* Generator fragment
* Examples included in our repository

[web] Updated JS libraries to current versions

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/XtextAntlrGeneratorFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/XtextAntlrGeneratorFragment2.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/tokens/IgnoreCaseKeywordSerializer.java

[492456] Added support for ignorecase-keywords to the new serializer

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/formatting/Formatter2Fragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/formatting/Formatter2Fragment2.java

 	[479367] Added formatting2 to the list of exported packages

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/StandardLanguage.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/StandardLanguage.java

[490871] Always register Ecore.genmodel

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/toggleComments/messages.properties

[430471] Fixed typo in error message

---

examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.fowlerdsl/src/org/eclipse/xtext/example/fowlerdsl/validation/StatemachineValidator.xtend
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.fowlerdsl/xtend-gen/org/eclipse/xtext/example/fowlerdsl/validation/StatemachineValidator.java
intellij/org.eclipse.xtext.idea.sdomain/src/org/eclipse/xtext/idea/sdomain/validation/SDomainValidator.xtend
intellij/org.eclipse.xtext.idea.sdomain/xtend-gen/org/eclipse/xtext/idea/sdomain/validation/SDomainValidator.java

[434624] validation rule has bogus name

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/jvmmodel/DispatchMethodCompileStrategy.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/DispatchCompilerTest.xtend
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/DispatchCompilerTest.java

[434982] Escape Java Keywords inside dispatch if else cascade

---

plugins/org.eclipse.xtext.xbase.lib/src/org/eclipse/xtend2/lib/StringConcatenationClient.java

Signed-off-by: Jan Koehnlein <jan.koehnlein@typefox.io>

[471147] make StringConcatenationClient.appendTo() accessible

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/StandardLanguage.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/model/TypeReference.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/StandardLanguage.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/model/TypeReference.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/TypeReferenceTest.xtend
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/generator/TypeReferenceTest.java

[490871]  Reverted previous change and applied a more local fix

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/GlobalURIEditorOpener.java

[437497] Prevent NPE in GlobalURIEditorOpener 

---

examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/ContentAssistTest.xtend
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/OrganizeImportsTest.xtend
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/tests/ContentAssistTest.java
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/tests/OrganizeImportsTest.java

a few typos in domain model tests comments

---

plugins/org.eclipse.xtext.xbase/.settings/.api_filters
plugins/org.eclipse.xtext/META-INF/MANIFEST.MF
plugins/org.eclipse.xtext/src/org/eclipse/xtext/findReferences/IReferenceFinder.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/findReferences/ReferenceAcceptor.xtend
plugins/org.eclipse.xtext/src/org/eclipse/xtext/findReferences/ReferenceFinder.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/findReferences/TargetURICollector.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/findReferences/TargetURISet.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/findReferences/TargetURIs.java
plugins/org.eclipse.xtext/xtend-gen/org/eclipse/xtext/findReferences/ReferenceAcceptor.java

Change-Id: I6a166f445ee1baa96183547e5c8e8c84ecaa30a2

[bug 490758] Postpone making the reference finder API public

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/ProjectFactory.java

Addresses the comments https://github.com/eclipse/xtext/pull/1029#discussion_r63526898

extracted protected method in project factory

---

plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/view/DerivedSourceView.java

 [439167] Use Monospace Font to view the generated code 

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/output/ErrorTreeAppendable.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug486838Test.xtend
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug486838Test.java

Signed-off-by: Christian Schneider <christian.schneider@typefox.io>
Please review!

[486838] fixed bug in ErrorTreeAppendable

---

plugins/org.eclipse.xtend.ide.common/src/org/eclipse/xtend/ide/common/highlighting/XtendHighlightingCalculator.java
plugins/org.eclipse.xtend.ide.common/src/org/eclipse/xtend/ide/common/highlighting/XtendHighlightingStyles.xtend
plugins/org.eclipse.xtend.ide.common/xtend-gen/org/eclipse/xtend/ide/common/highlighting/XtendHighlightingStyles.java
plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/XtendUiModule.xtend
plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/highlighting/TokenToAttributeIdMapper.java
plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/highlighting/XtendHighlightingConfiguration.java
plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/highlighting/XtendSyntaxColoringPreferencePage.xtend
plugins/org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/XtendUiModule.java
plugins/org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/highlighting/XtendSyntaxColoringPreferencePage.java
plugins/org.eclipse.xtext.xbase.ide/src/org/eclipse/xtext/xbase/ide/highlighting/XbaseHighlightingCalculator.java
plugins/org.eclipse.xtext.xbase.ide/src/org/eclipse/xtext/xbase/ide/highlighting/XbaseHighlightingStyles.xtend
plugins/org.eclipse.xtext.xbase.ide/xtend-gen/org/eclipse/xtext/xbase/ide/highlighting/XbaseHighlightingStyles.java
plugins/org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/highlighting/XbaseHighlightingConfiguration.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/highlighting/XtendHighlightingCalculatorExtendedColoringTest.xtend
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/highlighting/XtendHighlightingCalculatorTest.java
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/highlighting/XtendHighlightingCalculatorExtendedColoringTest.java

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=392705
The test class `XtendHighlightingCalculatorExtendedColoringTest.xtend` is just a stub for the moment, I plan to add more tests shortly.
After a bit of massage the existing tests are running, so I'm confident that I didn't break anything.

[392705] Fancy Xbase/Xtend syntax coloring

---

tests/org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/highlighting/HighlightingReconcilerTest.xtend
tests/org.eclipse.xtend.ide.tests/longrunning/xtend-gen/org/eclipse/xtend/ide/tests/highlighting/HighlightingReconcilerTest.java

… (due to the new extended syntax coloring).
To be merged once 2.10 is released.

Updates expectations of tests in 'HighlightingReconcilerTest'

---

releng/org.eclipse.xtext.sdk.feature/feature.xml
releng/org.eclipse.xtext.sdk.target/org.eclipse.xtext.sdk.target.target

Signed-off-by: Moritz Eysholdt <moritz.eysholdt@typefox.io>

fixed eclipse/xtext-eclipse#109 MWE2 SDK is missing

---

xtext-website/documentation/103_domainmodelnextsteps.md
xtext-website/documentation/104_jvmdomainmodel.md

Fixed jvm inferrer docs

---

xtend-website/documentation/203_xtend_expressions.md

[430767] Documentation of Template Comments

---

xtend-website/_config.yml
xtext-website/_config.yml

fixed edit on github links

---

xtext-website/documentation/330_web_support.md

Updated Documentation on Formating in CodeMirror https://github.com/eclipse/xtext-web/issues/31

Updated Documentation on Formating in CodeMirror

---

xtend-website/download.md
xtext-website/documentation/350_continuous_integration.md

updated docs to xtext 2.11

---

xtext-website/documentation/310_eclipse_support.md

added documentation https://github.com/eclipse/xtext-eclipse/issues/2

added documentation https://github.com/eclipse/xtext-eclipse/issues/2

---

README.md

I would like to propose using gitter for chats within the community

added gitter

---

xtext-website/documentation/303_runtime_concepts.md

changed documentation to use IGenerator2 instead of IGenerator #1122

---

xtext-website/index.html

Updated event teaser in index.html

---

QUALITY_GUIDELINES.md

Added review rule for committers

---

xtext-website/documentation/303_runtime_concepts.md
xtext-website/documentation/308_emf_integration.md
xtext-website/documentation/310_eclipse_support.md

[#1163] Fixed links to example projects

---

xtend-website/download.md
xtend-website/index.html

cleanup xtend website

---

xtext-website/documentation/103_domainmodelnextsteps.md

fixed typo

---

xtend-website/documentation/102_moviesexample.md
xtend-website/documentation/203_xtend_expressions.md
xtext-website/documentation/306_mwe2.md
xtext-website/documentation/310_eclipse_support.md

fixed double the the

---

xtend-website/index.html

moved videos to website and add resolution detection

---

xtext-website/documentation/302_configuration.md

Extend template "XtextGeneratorLanguage" with project and file wizard
fragments.
Signed-off-by: Arne Deutsch <Arne.Deutsch@itemis.de>

Extend template "XtextGeneratorLanguage".

---

xtext-website/documentation/303_runtime_concepts.md

Signed-off-by: Arne Deutsch <Arne.Deutsch@itemis.de>

Document JUnit 5 support in addtition to JUnit 4.

---

xtext-website/_posts/releasenotes/2018-05-23-version-2-14-0.md

Signed-off-by: Titouan Vervack <titouan.vervack@sigasi.com>

Fixed typo in link syntax

---

xtend-website/documentation/204_activeannotations.md
xtend-website/download.md

[eclipse/xtext-xtend#456] fixed outdated docs

---

xtend-website/_posts/releasenotes/2018-09-04-version-2-15-0.md
xtext-website/_posts/releasenotes/2018-09-04-version-2-15-0.md

[eclipse/xtext#1168] added hints to the releasenotes

---

xtext-website/documentation/310_eclipse_support.md

[#1240] fixed typos in documentation of templates

---

xtext-website/documentation/103_domainmodelnextsteps.md

Signed-off-by: psuzzi <psuzzi@itemis.com>

Fix Typo error in the Xtext 15 minutes tutorial extended

---

xtend-website/documentation/204_activeannotations.md
xtend-website/download.md

updated versions in documentation to 2.15

---

xtext-website/index.html

Add Eclipse GEF to the list of 'Compatible Graphical Editors'.

---

xtend-website/documentation/203_xtend_expressions.md
xtend-website/js/lang-xtend.js

document ELSE and ELSEIF in templates

document ELSE and ELSEIF in templates

---

xtend-website/download.md

updated docs regarding gradle

---

Jenkinsfile
xtend-website/Gemfile
xtext-website/Gemfile

- Configure build in Jenkinsfile
- Configure Javascript runtime in Gemfile

[#1246] Adapt website deploy to move to Gerrit

---

xtext-website/_posts/releasenotes/2018-09-04-version-2-15-0.md

Add Improved Testing Support section to the release notes, fixing typos.

---

xtext-website/css/style.css
xtext-website/index.html

better handling of fork button on small screens

---

CONTRIBUTING.md

[#1317] made requirements for non commiter contributions more clear

[#1317] made requirements for non commiter contributions more clear

---

xtend-website/documentation/204_activeannotations.md
xtend-website/download.md

updated xtend documentation to the new version

---

xtend-website/_posts/releasenotes/2018-12-04-version-2-16-0.md
xtext-website/_posts/releasenotes/2018-12-04-version-2-16-0.md

fixed markdown lint issues

---

xtext-website/_posts/releasenotes/2018-12-04-version-2-16-0.md

Fix link to AbstractQuickfixTest

---

xtend-website/_posts/releasenotes/2018-12-04-version-2-16-0.md

Update issue & PR count

---

xtext-website/_posts/releasenotes/2018-12-04-version-2-16-0.md

removed tycho 1.3 snapshot hint
note: dont merge before tycho 1.3 is out

removed tycho 1.3 snapshot hint

---

Builds.md

Updated release process

---

xtend-website/_posts/releasenotes/2019-03-05-version-2-17-0.md
xtext-website/_posts/releasenotes/2019-03-05-version-2-17-0.md

added java 11 to release notes

---

dev-doc/GradleWrapperVersionBump.md

documented GradleWrapperVersionBump

---

xtend-website/documentation/204_activeannotations.md
xtend-website/download.md

bumped version in docs

---

xtext-website/_posts/releasenotes/2019-03-05-version-2-17-0.md

fixed typos

---

xtext-website/documentation/350_continuous_integration.md

Updated CI docs

---

xtend-website/_posts/releasenotes/2019-03-05-version-2-17-0.md
xtext-website/_posts/releasenotes/2019-03-05-version-2-17-0.md

[releng] Mark 2.17 release notes published

---

xtend-website/_posts/releasenotes/2019-04-03-version-2-17-1.md
xtext-website/_posts/releasenotes/2019-04-03-version-2-17-1.md

prepared releasenotes for 2.17.1

prepared releasenotes for 2.17.1

---

xtend-website/documentation/203_xtend_expressions.md

added ?: and try-with-resources to xtend docs

---

Builds.md

- document using the release-prepare-branches job
- document upstream trigger for CBI.Jenkinsfile
- remove xtext-idea section
- update description for Marketplace (fixes #1439)

Update section 'Preparing Milestones and Releases'

---

xtend-website/documentation/204_activeannotations.md
xtend-website/download.md
xtext-website/documentation/350_continuous_integration.md

bumped xtext versions in docs

---

xtext-website/_posts/releasenotes/2019-06-04-version-2-18-0.md

added link to xtend release notes

added link to xtend release notes

---

CBI.Jenkinsfile

- use xtext-buildenv container for jekyll
- use jnlp container for ssh/git commands

[eclipse/xtext#1468] Add Jenkinsfile for JIRO environment

---

xtend-website/_posts/releasenotes/2019-06-04-version-2-18-0.md
xtext-website/_posts/releasenotes/2019-06-04-version-2-18-0.md

Signed-off-by: Nico Prediger <mail@nicoprediger.de>

[#1419] updated contributer list for 2.18.0 release

---

xtend-website/_posts/releasenotes/2019-09-03-version-2-19-0.md
xtext-website/_posts/releasenotes/2019-09-03-version-2-19-0.md

created stubs for 2.19 release notes #1483

created stubs for 2.19 release notes #1483

---

xtext-website/documentation/350_continuous_integration.md

mwe bump in docs

---

xtend-website/documentation/204_activeannotations.md
xtend-website/download.md
xtext-website/documentation/350_continuous_integration.md

bumped versions for 2.19

---

Builds.md

added hint to update api diff on major releases

---

Builds.md

fixed builds.md regarding changed api-diff job

---

CONTRIBUTING.md

[#1092] added hint about methods to clone with oomph

[#1092] added hint about methods to clone with oomph

---

xtend-website/_posts/releasenotes/2019-12-03-version-2-20-0.md
xtext-website/_posts/releasenotes/2019-12-03-version-2-20-0.md

[#1542] created 2019-12 / 2.20 releasenotes

[#1542] created 2019-12 / 2.20 releasenotes

---

xtend-website/documentation/204_activeannotations.md
xtend-website/download.md
xtext-website/documentation/350_continuous_integration.md

prepared 2.20 versions

---

xtext-website/index.html

merge website-published -> website master

---

xtend-website/download.md

use xtext-gradle-plugin 2.0.8

---

xtext-website/index.html

Change the link of the event to point to the Xtext talks directly.

---

xtext-website/index.html

removed eclipsecon banner
DO NOT MERGE BEFORE ECLIPSECON IS OVER

removed eclipsecon banner

---

dev-doc/GradleWrapperVersionBump.md

added hint to wrapper source code creation scripts

added hint to wrapper source code creation scripts

---

xtext-website/_posts/releasenotes/2019-12-03-version-2-20-0.md

added hints about deprecations to release notes

added hints about deprecations to release notes

---

xtext-website/documentation/350_continuous_integration.md

updated docs to mwe 2.11.1

---

xtext-website/_posts/releasenotes/2019-12-03-version-2-20-0.md

[#1542] Add New Project Wizard / New File Wizard improvements.

---

xtend-website/_posts/releasenotes/2019-12-03-version-2-20-0.md

[#1542] Xtend release notes: add Improved JUnit test case recognition.

---

xtext-website/_posts/releasenotes/2019-12-03-version-2-20-0.md

[#1542] Xtext release notes: add Xtext-Web Entities Example improvements

---

xtend-website/_posts/releasenotes/2020-03-03-version-2-21-0.md
xtext-website/_posts/releasenotes/2020-03-03-version-2-21-0.md

[#1612] created 2.21 release notes

[#1612] created 2.21 release notes

---

xtend-website/documentation/204_activeannotations.md
xtend-website/download.md
xtext-website/documentation/350_continuous_integration.md

prepared versions for 2.21

---

Builds.md

Update release process description

---

dev-doc/MaintenanceTasks.md

[#1606] Update doc for eclipse.target.platform variable

---

Builds.md
dev-doc/MaintenanceTasks.md

[eclipse/xtext#1632] Document update of Marketplace composite site

---

xtend-website/_posts/releasenotes/2020-03-03-version-2-21-0.md

[eclipse/xtext-xtend#942] Document compiler optimization

---

xtext-website/community.html

[#1541] Fix invalid hyperlinks on the Xtext community page.

---

xtext-website/community.html

[#1541] Use consistent indentation in the community.html page.

---

xtext-website/community.html

[#1541] Add GEF DOT youtube link to the recorded ECE18 session.

---

xtext-website/community.html

[#1541] Sort the Xtext projects on the community website alphabetically.

---

xtend-website/_posts/releasenotes/2020-03-03-version-2-21-0.md
xtext-website/_posts/releasenotes/2020-03-03-version-2-21-0.md

[#1176] added hint about EPL 2.0 to release notes

[#1176] added hint about EPL 2.0 to release notes

---

xtext-website/community.html

[#1541] Add Xtext-based projects to the Xtext Community Website.

---

xtext-website/_posts/releasenotes/2020-03-03-version-2-21-0.md
xtext-website/documentation/350_continuous_integration.md

added mwe 2.11.2 to docs

---

xtext-website/_posts/releasenotes/2020-03-03-version-2-21-0.md

[#1613] Add 'Updating the Xtext community website' to the release notes.

---

xtext-website/_posts/releasenotes/2020-03-03-version-2-21-0.md

added hints on deprecations/removals

added hints on deprecations/removals

---

xtext-website/community.html

published -> master

---

xtext-website/_posts/releasenotes/2020-03-03-version-2-21-0.md

Signed-off-by: Arne Deutsch <Arne.Deutsch@itemis.de>

Write release notes for 2.21.

---

xtend-website/_posts/releasenotes/2020-03-03-version-2-21-0.md
xtext-website/_posts/releasenotes/2020-03-03-version-2-21-0.md

finalized releasenotes

---

xtend-website/_posts/releasenotes/2020-06-02-version-2-22-0.md
xtext-website/_posts/releasenotes/2020-06-02-version-2-22-0.md

[#1689] created initial releasenotes

[#1689] created initial releasenotes

---

xtend-website/documentation/204_activeannotations.md
xtend-website/download.md
xtext-website/documentation/350_continuous_integration.md

[#1696] prepared docs for 2.22/2020-06

[#1696] prepared docs for 2.22/2020-06

---

xtext-website/community.html

Signed-off-by: Titouan Vervack <titouan.vervack@sigasi.com>

Fixed typo on community website

---

xtext-website/community.html

Signed-off-by: Ashpak Shaikh <ashpak_shaikh@intuit.com>

Adding graphql-xtext project to xtext community page.

---

xtext-website/community.html

[#1541] Fix eMoflon project hyperlinking on the Xtext Community Website.

---

xtext-website/_posts/releasenotes/2020-06-02-version-2-22-0.md

added hints on removals to release notes

added hints on removals to release notes

---

xtext-website/documentation/310_eclipse_support.md

[#1140] Add Multi Quick Fixes documentation to the "Eclipse Support".

---

xtext-website/documentation/103_domainmodelnextsteps.md
xtext-website/documentation/310_eclipse_support.md

- Add documentation about testing custom generators using the
CompilationTestHelper utility class.
- Add documentation about automated UI testing using the abstract base
classes in the org.eclipse.xtext.ui.testing package.

https://github.com/eclipse/xtext-core/issues/253 Document testing API.

---

xtend-website/community.html

- Add new presentations and articles to the Xtend community website.

https://github.com/eclipse/xtext-xtend/issues/1028 Update Xtend website.

---

xtext-website/documentation/102_domainmodelwalkthrough.md
xtext-website/documentation/103_domainmodelnextsteps.md

Update documentation of the Xtext Domainmodel tutorial.

---

xtext-website/documentation/104_jvmdomainmodel.md

Xtext website: Fix broken html rendering due to whitespace changes.

---

xtext-website/documentation/310_eclipse_support.md

[#1731] Fixing invalid links on the Eclipse Support website.

---

xtext-website/_posts/releasenotes/2020-06-02-version-2-22-0.md

added asm8 hint to release notes

added asm8 hint to release notes

---

xtext-website/documentation/303_runtime_concepts.md

[#1731] Updating the Unit Testing section of the Xtext website.

---

xtext-website/_posts/releasenotes/2018-12-04-version-2-16-0.md

[#1731] Fixing invalid links on the Xtext documentation website.

---

xtend-website/_posts/releasenotes/2020-06-02-version-2-22-0.md
xtext-website/_posts/releasenotes/2020-06-02-version-2-22-0.md

[#1689] Add Xtext/Xtend website update to the release notes.

---

dev-doc/RegenerateLanguages.md

RegenerateLanguages.md: fix ordered list numbering.

---

xtext-website/_posts/releasenotes/2020-06-02-version-2-22-0.md

ICU & Postprocessor in Release Notes

ICU & Postprocessor in Release Notes

---

xtext-website/_posts/releasenotes/2020-06-02-version-2-22-0.md

[#1689] Add "Maven Tycho update to 1.7.0" to the release notes.

---

xtext-website/_posts/releasenotes/2020-06-02-version-2-22-0.md

Add 'Code Generation improvements' section to the release notes.

---

xtext-website/community.html

[#1541] Update Project Licences to EPL-2.0

---

LICENSE

[#1176] Update LICENSE file to EPL-2.0

---

xtext-website/documentation/350_continuous_integration.md

[eclipse/xtext#1770] update to mwe 2.11.3 final

[eclipse/xtext#1770] update to mwe 2.11.3 final

---

xtend-website/_posts/releasenotes/2020-06-02-version-2-22-0.md
xtext-website/_posts/releasenotes/2020-06-02-version-2-22-0.md

added cta to release notes

---

xtext-website/community.html

- Removing archived EMF IncQuery project.

[#1541] Removing archived projects from the Xtext Community Website.

---

xtext-website/_posts/releasenotes/2020-06-02-version-2-22-0.md

[#1689] Add 'RegenerateLanguages documentation' to the Release notes.

---

xtext-website/index.html

Activate banner pointing to the Xtext talks on the EclipseCon 2020.

---

xtend-website/_posts/releasenotes/2020-06-02-version-2-22-0.md
xtext-website/_posts/releasenotes/2020-06-02-version-2-22-0.md

publish 2.22

---

xtend-website/documentation/204_activeannotations.md
xtend-website/download.md
xtext-website/documentation/350_continuous_integration.md

[#1787] version bump in docs

---

xtext-website/documentation/310_eclipse_support.md

- Add documentation about the AbstractMultiQuickfixTest base class to
the Eclipse UI testing section.

https://github.com/eclipse/xtext-eclipse/issues/1447 MultiQuickfix Test

---

xtext-website/documentation/310_eclipse_support.md

Add documentation about the AbstractCodeMiningTest base class to
the Eclipse UI testing section

https://github.com/eclipse/xtext-eclipse/issues/1497 CodeMining Test

---

xtext-website/_posts/releasenotes/2020-09-01-version-2-23-0.md

- AbstractCodeMiningTest
- AbstractMultiQuickfixTest

[#1786] Add UI Testing chapter to the release notes.

---

xtext-website/_posts/releasenotes/2020-09-01-version-2-23-0.md

more on J11

---

xtend-website/documentation/204_activeannotations.md
xtend-website/download.md
xtext-website/documentation/350_continuous_integration.md

[#1834] adapted documentation for 2.24
do not merge before 2.23 docs is published

[#1834] adapted documentation for 2.24

---

xtend-website/_posts/releasenotes/2020-12-01-version-2-24-0.md
xtext-website/_posts/releasenotes/2020-12-01-version-2-24-0.md

[#1833] initial creation of 2.24 release notes
do not merge before 2.23 release notes are published

[#1833] initial creation of 2.24 release notes

---

xtext-website/_posts/releasenotes/2020-12-01-version-2-24-0.md

[#1848] added dep update hint to rel notes

[#1848] added dep update hint to rel notes

---

xtext-website/community.html

[#1541] Add EMF.cloud Coffee Editor to the Xtext Community Website.

---

xtext-website/_posts/releasenotes/2020-12-01-version-2-24-0.md

added hint on quickfix code actions to rel notes

added hint on quickfix code actions to rel notes

---

xtend-website/_includes/footer.html
xtext-website/_includes/footer.html

replaced live.eclipse.org link with Xtext forum link

replaced live.eclipse.org link with Xtext forum link

---

xtend-website/community.html
xtext-website/community.html

[#1891] removed broken links

---

xtext-website/index.html

Signed-off-by: miklossy <miklossy@itemis.de>

Fixing typo: Occurences -> Occurrences

---

xtend-website/documentation/204_activeannotations.md
xtend-website/download.md
xtext-website/documentation/350_continuous_integration.md

[#1888] Adapted Docs for 2021-03 / Xtext 2.25

[#1888] Adapted Docs for 2021-03 / Xtext 2.25

---

xtend-website/_posts/releasenotes/2021-03-02-version-2-25-0.md
xtext-website/_posts/releasenotes/2021-03-02-version-2-25-0.md

[#1887] created 2.25 release notes

[#1887] created 2.25 release notes

---

xtext-website/index.html

Website published -> Master

---

xtend-website/_posts/releasenotes/2021-03-02-version-2-25-0.md
xtext-website/_posts/releasenotes/2021-03-02-version-2-25-0.md
xtext-website/documentation/350_continuous_integration.md

mwe and guava update in release notes

mwe and guava update in release notes

---

xtend-website/download.md

sunset jcenter

---

xtext-website/community.html

[#1541] Add GTSMorpher to the Xtext Community Website.

---

xtext-website/_posts/releasenotes/2021-03-02-version-2-25-0.md

Signed-off-by: miklossy <miklossy@miklossy>

[#1887] Add LSP Support documentation to the Xtext 2.25 release notes.

---

xtend-website/_posts/releasenotes/2021-03-02-version-2-25-0.md
xtext-website/_posts/releasenotes/2021-03-02-version-2-25-0.md

[#1887] enhance release notes

---

Builds.md

Signed-off-by: Karsten Thoms <karsten.thoms@karakun.com>

Note on sign-and-deploy & Maven Central

---

xtend-website/documentation/204_activeannotations.md
xtend-website/download.md
xtext-website/documentation/350_continuous_integration.md

[#1950] Adapt documentation for 2.26.0 release

[#1950] Adapt documentation for 2.26.0 release

---

dev-doc/Xtext-Maintenance-Manual.mm

added Maintenance Manual Mindmap (Freemind|Freeplace)

added Maintenance Manual Mindmap (Freemind|Freeplace)

---

xtend-website/_posts/releasenotes/2021-12-31-version-2-26-0.md
xtext-website/_posts/releasenotes/2021-12-31-version-2-26-0.md

[#1949] create release notes initially

[#1949] create release notes initially

---

xtext-website/_posts/releasenotes/2021-12-31-version-2-26-0.md
xtext-website/documentation/350_continuous_integration.md

https://github.com/eclipse/xtext-maven/issues/139

Add documentation for https://github.com/eclipse/xtext-maven/issues/139

---

xtext-website/community.html

[#1541] Add ThingML to the Xtext Community Website.

---

xtext-website/community.html

[#1541] Add Xtext-XMI to the Xtext Community Website.

---

xtext-website/index.html

Signed-off-by: miklossy <miklossy@itemis.de>

Update from "EclipseCon 2020" to "EclipseCon 2021".

---

xtext-website/community.html

https://github.com/raghvendra-v/tosca-yaml-lsp/issues/2#issuecomment-869426195

[#1541] Add TOSCA DSL to the Xtext Community Website.

---

xtext-website/_posts/releasenotes/2021-12-31-version-2-26-0.md

upgrades of tycho and gson

---

xtext-website/_config.yml
xtext-website/community.html
xtext-website/documentation/301_grammarlanguage.md

Fix broken website links
Fixes #1998

Fix broken website links

---

xtext-website/documentation/103_domainmodelnextsteps.md

Make more clear how to inject IQualifiedNameProvider into Generator
Fixes #2022

Make more clear how to inject IQualifiedNameProvider into Generator

---

xtext-website/community.html

[#1541] Add Tinyscript to the Xtext Community Website.

---

xtend-website/_posts/releasenotes/2022-02-28-version-2-26-0.md
xtext-website/_posts/releasenotes/2022-02-28-version-2-26-0.md

more release notes

---

xtend-website/documentation/204_activeannotations.md
xtend-website/download.md
xtext-website/documentation/350_continuous_integration.md

[#2040] prepare docs for 2.27

---

xtext-website/_posts/releasenotes/2022-05-30-version-2-27-0.md

more version changes

---

xtend-website/community.html

drop dead link

---

xtext-website/_posts/releasenotes/2022-05-30-version-2-27-0.md

[eclipse/xtext-core#1902]update to lsp4j 0.14.0

[eclipse/xtext-core#1902]update to lsp4j 0.14.0

---

xtend-website/_posts/releasenotes/2022-05-30-version-2-27-0.md
xtext-website/_posts/releasenotes/2022-05-30-version-2-27-0.md

[#2040] Prepare 2.27 release notes

[#2040] Prepare 2.27 release notes

---

xtend-website/_posts/releasenotes/2022-12-31-version-2-28-0.md
xtend-website/documentation/204_activeannotations.md
xtend-website/download.md
xtext-website/_posts/releasenotes/2022-12-31-version-2-28-0.md
xtext-website/documentation/350_continuous_integration.md

[#2072] Prepare 2.28 release notes + bump versions in docs

[#2072] Prepare 2.28 release notes + bump versions in docs

---

xtext-website/index.html

Signed-off-by: miklossy <miklossy@itemis.de>

Update from "EclipseCon 2021" to "EclipseCon 2022".

---

xtext-website/_posts/releasenotes/2022-12-31-version-2-28-0.md

[eclipse/xtext-core#1904] update to lsp4j 0.15.0

[eclipse/xtext-core#1904] update to lsp4j 0.15.0

---

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java

[#2141] Prepare Wizard for 2023-06

[#2141] Prepare Wizard for 2023-06

---

releng/org.eclipse.xtext.contributor/Xtext.setup

[#2141] add 2023-06 to Xtext.setup

[#2141] add 2023-06 to Xtext.setup

---

Jenkinsfile

remove downstream build leftovers

remove downstream build leftovers

---

org.eclipse.xtext.web.example.jetty/pom.xml

fix jetty inconsistency

---

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/pom.xml
org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend
org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java

update to tycho 3.0.4 in wizard

update to tycho 3.0.4 in wizard

---

org.eclipse.xtext.web/package-lock.json
org.eclipse.xtext.web/package.json

another attempt to fix #2193

---

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
releng/org.eclipse.xtext.contributor/Xtext.setup
xtext-latest.target
xtext-r202203.target
xtext-r202206.target
xtext-r202209.target
xtext-r202212.target
xtext-r202303.target

[#2142] update to orbit 2023-06

[#2142] update to orbit 2023-06

---

org.eclipse.xtext.dev-bom/pom.xml
releng/org.eclipse.xtext.contributor/Xtext.setup
xtext-latest.target
xtext-r202203.target
xtext-r202206.target
xtext-r202209.target
xtext-r202212.target
xtext-r202303.target

[#2177] update to lsp4j 0.20.1

[#2177] update to lsp4j 0.20.1

---

org.eclipse.xtend.sdk.feature/feature.xml
org.eclipse.xtext.p2repository/category.xml

Closes #2169 
- Publish also "Xtend Lib" feature
- "Xtend SDK" includes "Xtend Lib" instead of requiring its contents

Lb 2169 xtend sdk feature

---

releng/org.eclipse.xtext.contributor/Xtext.setup

Replaces https://github.com/eclipse/xtext/pull/2206

[Setup] Simplify WorkingSets task and exclude unrelated projects

---

releng/org.eclipse.xtext.contributor/Xtext.setup

https://github.com/eclipse/xtext/issues/2225

Ensure that targlets are performed after project imports

---

releng/org.eclipse.xtext.contributor/Xtext.setup

make 2023-06 default tp in oomph. Fixes #2141

make 2023-06 default tp in oomph. Fixes #2141

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/AddJunitLibToClasspathQuickfixTest.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/buildpath/AbstractJunitLibClasspathAdderTestCase.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/buildpath/AbstractJunitLibClasspathAdderTestCase.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/AddJunitLibToClasspathQuickfixTest.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/buildpath/AbstractLibClasspathAdder.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/buildpath/Junit4LibClasspathAdder.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/buildpath/Junit5LibClasspathAdder.java
org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/buildpath/XtendLibClasspathAdder.java

[#2571] update add junit5 quickfix to use package imports

[#2571] update add junit5 quickfix to use package imports

---

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/gradle/wrapper/gradle-wrapper.properties
org.eclipse.xtext.tests/testdata/wizard-expectations/gradle/gradle.parent/gradle/wrapper/gradle-wrapper.properties
org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleApp/lsGradleApp.parent/gradle/wrapper/gradle-wrapper.properties
org.eclipse.xtext.tests/testdata/wizard-expectations/lsGradleFatjar/lsGradleFatjar.parent/gradle/wrapper/gradle-wrapper.properties
org.eclipse.xtext.xtext.wizard/resources/gradlew/gradle-wrapper.properties

update to gradle 8.1.1

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/buildpath/XtendClasspathContainer.java

[#2627] fix XtendClasspathContainer to work with the new maven based project setup

[#2627] fix XtendClasspathContainer to work with the new maven based project setup

---

jenkins/milestone-deploy/Jenkinsfile
org.eclipse.xtext.p2repository/packaging-p2composite.ant
org.eclipse.xtext.p2repository/pom.xml
pom.xml

See also https://github.com/eclipse/xtext/issues/2624

Building 2.31.0.M1

---

org.eclipse.xtext.dev-bom/pom.xml

bump junit5 to 5.9.3

---

pom.xml

bootstrap against 2.31.0.M2

---

Jenkinsfile

also archive rolling logs

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/html/DefaultEObjectHoverProvider.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/html/IXtextBrowserInformationControl.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/html/XtextBrowserInformationControl.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/hover/html/XtextBrowserInformationControlAdapter.java
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseHoverProvider.java
org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseInformationControl.java

[#2653] Support Browser Dispose Timeouts in Hovers

[#2653] Support Browser Dispose Timeouts in Hovers

---

pom.xml

bootstrap against 2.31.0.M3

---

org.eclipse.xtext.maven.plugin/Run ITs from Maven.launch
org.eclipse.xtext.maven.plugin/pre-integration-test.launch
org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/AbstractXtextGeneratorMojo.java
org.eclipse.xtext.maven.plugin/src/test/java/org/eclipse/xtext/maven/plugin/XtextGeneratorIT.java
org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/simple-lang-plugin-dependencies/pom.xml
org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/simple-lang-plugin-dependencies/simple-lang-model/pom.xml
org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/simple-lang-plugin-dependencies/simple-lang-model/src/main/java/Model.nojdt
org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/simple-lang-plugin-dependencies/simple-lang-ref-model/pom.xml
org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/simple-lang-plugin-dependencies/simple-lang-ref-model/src/main/java/RefModel.nojdt

Add option includePluginDependencies to xtext-maven-plugin

---

jenkins/release-deploy/Jenkinsfile
org.eclipse.xtext.p2repository/pom.xml
pom.xml
scripts/prepare-for-release.sh

[#2625] prepare Jenkinsfile and Scripts for release builds

[#2625] prepare Jenkinsfile and Scripts for release builds

---

jenkins/milestone-deploy/Jenkinsfile

remove GA=release from new milestones job

remove GA=release from new milestones job

---

xtext-latest.target
xtext-r202203.target
xtext-r202206.target
xtext-r202209.target
xtext-r202212.target
xtext-r202303.target

[#2687] add missing mwe2.launch.ui to tps

[#2687] add missing mwe2.launch.ui to tps

---

pom.xml

bootstrap against 2.31

---

Builds.md

[#2184] document milestone and release process

[#2184] document milestone and release process

---

Jenkinsfile
xtext-r202306.target

prepare 2023-06 target

---

.mvn/wrapper/maven-wrapper.properties

updated Maven wrapper to 3.9.2

---

org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/StandaloneBuilder.java
org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/incremental/ResourceURICollector.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/SourceAttachmentPackageFragmentRootWalker.java

Handle empty bundle symbolic name

---

Jenkinsfile
xtext-latest.target

[#2693] use 4.29 in latest

---

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
xtext-latest.target

[#2693] update to Eclipse 2023-09

[#2693] update to Eclipse 2023-09

---

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
xtext-latest.target
xtext-r202203.target
xtext-r202206.target
xtext-r202209.target
xtext-r202212.target
xtext-r202303.target
xtext-r202306.target

prepare orbit for 2023-09

---

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/pom.xml
org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend
org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
pom.xml

Update to Tycho 3.0.5. Fixes #2709

Update to Tycho 3.0.5. 

---

org.eclipse.xtext.p2repository/category.xml

package also args4j to update site

package also args4j to update site

---

org.eclipse.xtext.web.example.jetty/.settings/org.eclipse.pde.core.prefs
org.eclipse.xtext.xbase.web/.settings/org.eclipse.pde.core.prefs

Remove pde.prefs from maven projects. the prefs leads pde try to launch it as plugins in launch configs

Remove pde.prefs from maven projects.

---

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
xtext-latest.target
xtext-r202203.target
xtext-r202206.target
xtext-r202209.target
xtext-r202212.target
xtext-r202303.target
xtext-r202306.target

[#2721] use maven gson instead of orbit gson

[#2721] use maven gson instead of orbit gson

---

xtext-r202203.target
xtext-r202206.target

[#2722] workaround for junit 5.9.1 removal from orbit

[#2722] workaround for junit 5.9.1 removal from orbit

---

org.eclipse.xtext.dev-bom/pom.xml

[#2759] update to junit 5.10

---

org.eclipse.xtext.p2repository/category.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
xtext-latest.target
xtext-r202203.target
xtext-r202206.target
xtext-r202209.target
xtext-r202212.target
xtext-r202303.target
xtext-r202306.target

adapt to latest orbit changes

---

org.eclipse.xtext.dev-bom/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/pom.xml
org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml
xtext-latest.target
xtext-r202203.target
xtext-r202206.target
xtext-r202209.target
xtext-r202212.target
xtext-r202303.target
xtext-r202306.target

bootstrap agaist MWE 2.15.0.M2

bootstrap agaist MWE 2.15.0.M2

---

pom.xml

bootstrap against 2.32.0.M2

---

org.eclipse.xtext.dev-bom/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/pom.xml
org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml
xtext-latest.target
xtext-r202203.target
xtext-r202206.target
xtext-r202209.target
xtext-r202212.target
xtext-r202303.target
xtext-r202306.target

update to mwe 2.15.0.M3

---

org.eclipse.emf.mwe2.language.sdk.dummy/feature.xml
org.eclipse.emf.mwe2.language.sdk.dummy/pom.xml
org.eclipse.xtext.dev-bom/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/pom.xml
org.eclipse.xtext.util/src/org/eclipse/xtext/util/XtextVersion.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml
xtext-latest.target
xtext-r202203.target
xtext-r202206.target
xtext-r202209.target
xtext-r202212.target
xtext-r202303.target
xtext-r202306.target

[#2716] bootstrap against mwe 2.15.0 release

[#2716] bootstrap against mwe 2.15.0 release

---

Jenkinsfile
xtext-r202309.target

[#2754] provide r2023-09 tp

---

releng/org.eclipse.xtext.contributor/Xtext.setup
xtext-latest.target

[#2754] prepare latest for 4.30

[#2754] prepare latest for 4.30

---

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
xtext-latest.target
xtext-r202203.target
xtext-r202206.target
xtext-r202209.target
xtext-r202212.target
xtext-r202303.target
xtext-r202306.target
xtext-r202309.target

[#2754] prepare 2023-12 tps

---

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target
org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
xtext-latest.target
xtext-r202203.target
xtext-r202206.target
xtext-r202212.target
xtext-r202303.target
xtext-r202306.target
xtext-r202309.target

[#2754] update to orbit 2023-12

[#2754] update to orbit 2023-12

---

org.eclipse.xtext.dev-bom/pom.xml
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ide/pom.xml
org.eclipse.xtext/META-INF/MANIFEST.MF_gen
org.eclipse.xtext/pom.xml
xtext-latest.target
xtext-r202203.target
xtext-r202206.target
xtext-r202209.target
xtext-r202212.target
xtext-r202303.target
xtext-r202306.target
xtext-r202309.target

remove xpand from targets and poms. See #2811

remove xpand from targets and poms. See #2811

---

NOTICE.md
org.eclipse.xtend.ide.tests/batch-compiler-data/ant/test.ant
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
org.eclipse.xtend.sdk.feature/feature.xml
org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
org.eclipse.xtext.dev-bom/pom.xml
org.eclipse.xtext.p2repository/category.xml
org.eclipse.xtext.redist.feature/feature.xml
org.eclipse.xtext.runtime.feature/feature.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
xtext-latest.target
xtext-r202203.target
xtext-r202206.target
xtext-r202209.target
xtext-r202212.target
xtext-r202303.target
xtext-r202306.target
xtext-r202309.target

Fix antlr,classgraph,log4j and guava versions
Fixes #2819

Fix antlr,classgraph,log4j and guava versions

---

org.eclipse.xtext.common.types/META-INF/MANIFEST.MF

use import for classgraph dependency

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml

build dm with tycho 3

---

org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/validation/AbstractValidatorTester.java
org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/validation/ValidatorTester.java
org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/ValidatorTesterTest.java

Reintroduced ValidatorTester in xtext.testing bundle

---

releng/org.eclipse.xtext.contributor/Xtext.setup

Java 17 in Oomph

---

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/pom.xml
org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend
org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java

[2909] xtext.logging versionRange 0.0.0 in extraRequirements

---

Jenkinsfile
full-build.sh
full-deploy.sh
jenkins/milestone-deploy/Jenkinsfile
jenkins/nightly-deploy/Jenkinsfile
jenkins/other-experiments/Jenkinsfile-maven-deploy
jenkins/other-experiments/Jenkinsfile-p2-deploy
jenkins/other-experiments/Jenkinsfile-p2-deploy-nightly
jenkins/release-deploy/Jenkinsfile
maven-build.sh
pom.xml
releng/jenkins/release-simrel-update/Jenkinsfile
scripts/fixVersions.sh
scripts/prepare-for-milestone.sh
scripts/prepare-for-release.sh
tycho-sign.sh
tycho-test.sh

Use Maven wrapper consistently and the Maven enforcer plugin

---

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
xtext-latest.target
xtext-r202203.target
xtext-r202206.target
xtext-r202209.target
xtext-r202212.target
xtext-r202303.target
xtext-r202306.target
xtext-r202309.target
xtext-r202312.target

force org.apache.commons.logging 1.2.0 in target platforms

---

.github/workflows/maven.yml

macOS in GitHub Actions switched to arm by default

use stable tags for GitHub Actions virtual environments

---

NOTICE.md
org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
org.eclipse.xtext.dev-bom/pom.xml
org.eclipse.xtext.p2repository/category.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
xtext-latest.target
xtext-r202203.target
xtext-r202206.target
xtext-r202209.target
xtext-r202212.target
xtext-r202303.target
xtext-r202306.target
xtext-r202309.target
xtext-r202312.target
xtext-r202403.target

io.github.classgraph 4.8.172

---

org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/JvmExecutableDeclarationImpl.java

follow-up of https://github.com/eclipse/xtext/pull/2784
see also https://github.com/eclipse/xtext/pull/2784#issuecomment-2077712599

regenerated file with Xtend annotation

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractContentAssistTest.java

Fix Regression in AbstractContentAssistTest breaking customizations

---

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J21/mavenTychoP2J21.parent/mavenTychoP2J21.target/mavenTychoP2J21.target.target
org.eclipse.xtext.web.servlet/pom.xml
org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
xtext-latest.target
xtext-r202203.target
xtext-r202206.target
xtext-r202209.target
xtext-r202212.target
xtext-r202303.target
xtext-r202306.target
xtext-r202309.target
xtext-r202312.target
xtext-r202403.target

Update GSON to 2.11.0

---

.github/workflows/maven.yml
pom.xml

This is meant to do a bit of cleanup.
Please see the two commits messages for more details.

Cleanup of GitHub Actions

---

.mvn/maven.config

-Dsurefire.rerunFailingTestsCount=5

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/buildpath/JavaClasspathTest.java

Ignore Test on JDT > 3.39 / Eclipse 4.33 / 2024-09

---

org.eclipse.xtext.java/META-INF/MANIFEST.MF
org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF

attempt to fix #3193

---

org.eclipse.xtext.sdk.feature/feature.xml

org.apache.commons.commons-logging as dep in SDK feature

---

org.eclipse.xtext.web/pom.xml
org.eclipse.xtext.xbase.web/pom.xml

Pin core.runtime as test dependency in first position in the POM

---

.github/workflows/maven.yml

see the comments in https://github.com/eclipse/xtext/pull/3212

removed check for internal PRs

---

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJUnit5/mavenTychoJUnit5.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J21/mavenTychoP2J21.parent/pom.xml
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/pom.xml
org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend
org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
pom.xml

update to tycho 4.0.10

---

org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.web/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJUnit5/mavenTychoJUnit5.parent/mavenTychoJUnit5.web/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.web/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J21/mavenTychoP2J21.parent/mavenTychoP2J21.web/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/plainMaven/plainMaven.parent/plainMaven.web/pom.xml
org.eclipse.xtext.web.example.jetty/pom.xml
org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.xtend
org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WebProjectDescriptor.java

See https://github.com/eclipse-xtext/xtext/issues/3272#issuecomment-2515133495

maven-war-plugin 3.4.0

---

org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJUnit5/mavenTychoJUnit5.parent/mavenTychoJUnit5/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2/pom.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J21/mavenTychoP2J21.parent/mavenTychoP2J21/pom.xml
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/pom.xml
org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend
org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java

Closes https://github.com/eclipse-xtext/xtext/issues/3304

xtext.generator.dependencies for exec-maven-plugin

---

Contribute.md
README.md

As suggested in https://github.com/eclipse-xtext/xtext-website/issues/13

Update Xtext homepage links

---

README.md

Otherwise no issues are found.

Fix the Issues query string and update version

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/EqualsWithNullMultiQuickfixTest.xtend
org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/RemoveUnnecessaryModifiersMultiQuickfixTest.xtend
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/AbstractXtendUITestCase.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/compiler/QuickDebugSourceInstallingCompilationParticipantTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/EqualsWithNullMultiQuickfixTest.java
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/RemoveUnnecessaryModifiersMultiQuickfixTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJdtImplTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/hover/ProblemHoverTest.java
org.eclipse.xtext.xbase.ui.tests/src/org/eclipse/xtext/xbase/ui/tests/editor/AbstractXbaseContentAssistBugTest.java

Closes #3343 
and should fix other flaky tests I saw recently.
In particular, this reverts one of your older commits, @cdietrich

Addressing other flaky tests

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/domainmodel.target

fix dm target 

---

org.eclipse.xtext/src/org/eclipse/xtext/EcoreUtil2.java

A few minor fixes, cleanups and modernisations for EcoreUtil2.

Improvements for EcoreUtil2
