plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/validation/XbaseJavaValidator.java
tests/org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/validation/XbaseValidationTest.xtend
tests/org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/validation/XbaseValidationTest.java

No warning for null-safe feature call of primitive featue if the result isn't used

[xbase] Bug 458742

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/analysis/ContextPDAProvider.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/serializer/ContextTypePDAProviderTest.java

Change-Id: I25a55027dc588b41b70a4cb94ca2b81282c31f4e

[serializer] bugfix: never break datatype rules into individual tokens

---

plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/types/TypesGeneratorFragment.java

...when TypesGeneratorFragment is used
Change-Id: I774e95b1cedeb6c1a9c471d1ad77e815b4b5d5f9

[462037] Restore binding for TypesAwareGlobalScopeProvider 

---

plugins/org.eclipse.xtext.util/src/org/eclipse/xtext/util/Strings.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/output/AppendableBasedTraceRegion.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/AbstractNode.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/RootNode.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/resource/XtextSyntaxDiagnosticWithRange.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/tasks/DefaultTaskParser.xtend
plugins/org.eclipse.xtext/src/org/eclipse/xtext/validation/DiagnosticConverterImpl.java
plugins/org.eclipse.xtext/xtend-gen/org/eclipse/xtext/tasks/DefaultTaskParser.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/tasks/DefaultTaskParserTest.xtend
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/tasks/DefaultTaskParserTest.java

Instead of using countLines with a substring, the start and endOffset
an be passed as an argument to the methods that deal with line
counting.

[461939]: Fixed performance problem with Strings.countLines

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/sequencer/AssignmentFinder.java

Because rule calls can refer to DataType rules which again may
contain keywords.
Change-Id: If128a1fa89330df970fe5a076ec7db0dc8e01e64

[serializer] keywords don't have precedence over rule calls

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocumentProvider.java

Avoid logging of error already that is already reported well to the user
Change-Id: Id6756e8af138ae6bf91c39e4bc19bae16bc0122c

[461765] IAE in BaseCSorASDocumentProvider.setDocumentContent

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendJavaValidator.java

The message's first line (shown in problems view) said only "The class
X must be defined abstract because it does not implement", which is a
bit confusing. Adding "its inherited abstract method(s)" as suggested
by Sebastian

Fix bug 462217: improve message for undefined abstract methods

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/jvmmodel/IXtendJvmAssociations.java
plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/typesystem/XtendReentrantTypeResolver.java
plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendJavaValidator.java
plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/editor/OverrideIndicatorRulerAction.java
plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/hover/XtendHoverDocumentationProvider.java
plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/hover/XtendHoverSignatureProvider.java
plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/labeling/XtendLabelProvider.xtend
plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/quickfix/CreateMemberQuickfixes.java
plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/quickfix/XtendQuickfixProvider.java
plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/refactoring/ExtractMethodRefactoring.java
plugins/org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/labeling/XtendLabelProvider.java
plugins/org.eclipse.xtext.common.types/src/org/eclipse/xtext/common/types/impl/JvmIdentifiableElementImplCustom.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/jvmmodel/JvmTypesBuilder.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/Bug446364Test.xtend
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/Bug446364.java
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/Bug446364Processor.java
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/Bug446364Test.java

- `IXtendJvmAssociations.getDirectlyInferredOperation(XtendFunction)` now returns the first associated JVM operation if no directly matching operation is found (an AA might have renamed it).
- The helper method above can return null (e.g. an AA removes the operation); this has already been considered in several places where it is used. Added missing null checks.
- Added a workaround for [bug 462451](https://bugs.eclipse.org/bugs/show_bug.cgi?id=462451) to `JvmTypesBuilder.removeExistingBody(JvmMember)`
- Made `JvmIdentifiableElement.toString()` more robust for easier debugging.

[xtend] Bug 446364: Problems when manipulating declared methods in AA

---

tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/serializer/GenericSemanticSequencerTest.java

...because BacktrackingSemanticSequencer can handle them
Change-Id: I83ac829a43a5623dbb38e8086ab462c89e7e0a2d

[serializer] excluded tests from old GenericSemanticSequencer

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/SourceAttachmentPackageFragmentRootWalker.java

Change-Id: I
A PFR with a broken jar. This is likely detected and reported by JDT as well, so we should not log this as an error.

[462121] don't log broken JARs during indexing as errors

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/sequencer/GenericSemanticSequencer.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/sequencer/ISemanticSequencer.java

This also changes the just-in-time-binding for ISemanticSequencer from
GenericSemanticSequencer to BacktrackingSemanticSequencer. I'm not
expecting this it have an impact because the RuntimeModule overrides
this binding for ISemanticSequencer
Change-Id: I8eb0d71124bef43edee40101851e044e831f66d0

[serializer] bug 462536: deprecate GenericSemanticSequencer

---

plugins/org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/validation/ProjectAwareUniqueClassNameValidator.xtend
plugins/org.eclipse.xtext.xbase.ui/xtend-gen/org/eclipse/xtext/xbase/ui/validation/ProjectAwareUniqueClassNameValidator.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/generator/IContextualOutputConfigurationProvider.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/generator/IOutputConfigurationProvider.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/generator/OutputConfiguration.java

ProjectAwareUniqueClassNameValidator injected IOutputConfigurationProvider, which gives only the default configurations without project-specific settings. This is fixed by injecting IContextualOutputConfigurationProvider instead.

[xbase] Bug 462172: Avoid "Type is already defined" errors

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/formatting2/ContentFormatter.java

The expected behaviour is that when a document with syntax errors is 
formatted, all exceptions should be ignored. 

[formatter] Bug 450458: Can not edit non-white space

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/serializer/XbaseSemanticSequencer.java

[serializer/xbase] be more robust regarding unresolved references

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/CachingResourceValidatorImpl.xtend
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/validation/CachingResourceValidatorImpl.java
plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/validator/XtendResourceValidator.xtend
plugins/org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/validator/XtendResourceValidator.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/validation/ValidationJob.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/ElementIssueProvider.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/service/OperationCanceledManager.xtend
plugins/org.eclipse.xtext/src/org/eclipse/xtext/validation/IResourceValidator.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/validation/ResourceValidatorImpl.java
plugins/org.eclipse.xtext/xtend-gen/org/eclipse/xtext/service/OperationCanceledError.java

The IResourceValidator is not supposed to throw a platform
specific cancellation exception but should wrap it in an
OperationCanceledError instead.
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=461764

[461764]: Fixed wrongly propagated exception

---

plugins/org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/access/jdt/JdtBasedTypeFactory.java

This is a workaround for a bug in JDT.
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=462911
Signed-off-by: Sebastian Zarnekow <Sebastian.Zarnekow@itemis.de>

[462911]: Fix: Catch NPE from JDT

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/AnnotationProcessor.xtend
plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/XAnnotationExtensions.xtend
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/AnnotationProcessor.java
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/XAnnotationExtensions.java
tests/org.eclipse.xtend.core.tests/smoke-suites/org/eclipse/xtend/core/tests/smoke/FormatterSmokeSuite.java

Instead a thread pool is used.
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=463059

 [463059]: Avoid spawning new threads in annotation processor

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/xtext/KeywordInspector.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/KeywordInspectorTest.java

Terminal fragments cannot shadow keywords
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=462486

[462486]: Fixed bogus grammar validation

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/XtendGenerator.xtend
plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/jvmmodel/XtendJvmModelInferrer.java
plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/ActiveAnnotationContext.xtend
plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/CachingResourceValidatorImpl.xtend
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/compiler/XtendGenerator.java
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/ActiveAnnotationContextProvider.java
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/validation/CachingResourceValidatorImpl.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/service/OperationCanceledManager.xtend
plugins/org.eclipse.xtext/xtend-gen/org/eclipse/xtext/service/OperationCanceledManager.java

Active annotation processors used to swallow all cancellation
information.
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=463095

 [463095]: Fixed accidentally ignored OperationCancelErrors

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/declaration/JvmAnnotationReferenceImpl.xtend
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/JvmAnnotationReferenceImpl.java
plugins/org.eclipse.xtend.lib.macro/src/org/eclipse/xtend/lib/macro/declaration/AnnotationReference.java
plugins/org.eclipse.xtext.common.types/emf-gen/org/eclipse/xtext/common/types/JvmAnnotationReference.java
plugins/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/AbstractReusableActiveAnnotationTests.xtend
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/AbstractReusableActiveAnnotationTests.java

JvmAnnotationReferenceImpl.getExpression violated the
contract of the AnnotationReference.getExpression.
For external elements, null is to be returned.
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=463161

[463161]: Fixed NPE during annotation processing

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/javaconverter/ASTFlattenerUtils.xtend
plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/javaconverter/JavaASTFlattener.xtend
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/ASTFlattenerUtils.java
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/javaconverter/JavaASTFlattener.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/javaconverter/JavaConverterTest.xtend
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/javaconverter/JavaConverterTest.java

- Bug 462099: use `===` for comparisons with `null`
- Bug 462100: omit `@Override` for method declarations
- Added parentheses to fallback solution of lambda generation
- Added a space before the opening brace of a method declaration
- Renamed isOverrideMethode &rarr; isOverrideMethod
- Renamed appendModifieres &rarr; appendModifiers
- Fixed indentation in ASTFlattenerUtils

[xtend] Fixed some Java converter bugs and cleaned up the code

---

plugins/org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/ui/contentassist/XtextProposalProvider.java
tests/org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/contentassist/XtextContentAssistTest.java

- Prefix matching didn't work properly for the super grammar reference.
- The comma after the first super grammar should not be proposed since only one super grammar is supported.

[grammar][contentAssist] Fixed two cosmetic issues

---

tests/org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJdtImplTest.java
tests/org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/model/JavaClassPathResourceForIEditorInputFactoryTest.java

Maybe an OS specific invariant?
see https://hudson.eclipse.org/xtext/job/xtext-xtend-tests-maintenance/111/testReport/junit/org.eclipse.xtext.ui.tests.editor.model/JavaClassPathResourceForIEditorInputFactoryTest/testBug463258_02/

 [463258]: Zip files must have at least one entry

---

plugins/org.eclipse.xtext.ui.codetemplates/model/generated/Codetemplates.ecore
plugins/org.eclipse.xtext.ui.codetemplates/model/generated/Codetemplates.genmodel
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/JdtClasspathUriResolver.java
plugins/org.eclipse.xtext.ui/xtend-gen/org/eclipse/xtext/ui/editor/reconciler/CancelIndicatorBasedProgressMonitor.java
plugins/org.eclipse.xtext/build.properties
plugins/org.eclipse.xtext/org/eclipse/xtext/Xtext.ecore
plugins/org.eclipse.xtext/org/eclipse/xtext/Xtext.genmodel
tests/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/metamodelreferencing/tests/MetamodelRefTestLanguage.ecore
tests/org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/util/JdtClasspathUriResolverTest.java

Moved Xtext.ecore and Xtext.genmodel to a folder
org/eclipse/xtext which is not a source folder but
a model folder.
Change-Id: I6e5fea5f34bf3e52a36c59099162e20e1783fb38
Signed-off-by: Sebastian Zarnekow <Sebastian.Zarnekow@itemis.de>

[460696]: Fixed erroneous genmodel declaration

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/ImportManager.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug406066Test.xtend
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.xtend
tests/org.eclipse.xtend.core.tests/suites/org/eclipse/xtend/core/tests/compiler/CompilerSuite.java
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug406066Test.java
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.java

When the import manager is created with a type that collides with java.lang, the flag thisCollidesWithJavaLang is set. But in method allowsSimpleName it is not considered that the actual type name that should be shortened is different from the one with that the ImportManager was created.

[bug 406066] Improve usage of simple names for java.lang classes

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/ClosureWithExpectationHelper.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/AbstractLinkingCandidate.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/ResolvedTypes.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/references/FunctionTypes.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/references/UnboundTypeReference.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/util/BoundTypeArgumentSource.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/util/ExpectationTypeParameterHintCollector.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug460963Test.xtend
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/linking/LinkingTest.java
tests/org.eclipse.xtend.core.tests/suites/org/eclipse/xtend/core/tests/compiler/CompilerSuite.java
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug460963Test.java

The expected type contributed to unresolved type parameters as if
it was directly inferred which caused trouble, e.g. with the overload
of IterableExtensions.filter
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=460191

[460191]: [xtend][linking] Expected type had too high prio when linking

---

maven/org.eclipse.xtend.maven.archetype/pom.xml
maven/org.eclipse.xtend.maven.archetype/src/test/resources/projects/first/archetype.properties
maven/org.eclipse.xtend.maven.archetype/src/test/resources/projects/first/goal.txt
maven/org.eclipse.xtext.parent/pom.xml

Hi guys, perhaps this is useful? It adds an integration test to the xtend.maven.archetype, as in with this the build actually "instantiates" the archetype template, and runs a 'mvn package' on it, to make sure it cleanly builds.
PS: I built this because I suspect the archetype was broken, and meant to contribute a fix, but then later found it was another problem on my end, as I had already built this test, I though I'd contribute it anyway, as you may find this useful for future non-regression?
PPS: This doesn't actually pass on current master head for me, but the failure I'm getting is probably because you're working on something new on 2.9 and probably already know that it seems to be currently broken?

Added integration test for xtend.maven.archetype

---

plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/validator/XtendUIValidator.java

If the JME #isDoesNotExist, it should not be propagated
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=463383

[463383]: Fixed thrown JavaModelException

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/CollectionLiteralsTypeComputer.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/AmbiguityBug463407Test.xtend
tests/org.eclipse.xtend.core.tests/suites/org/eclipse/xtend/core/tests/validation/AmbiguityValidationSuite.java
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/AmbiguityBug463407Test.java

Collection literals cannot be used to implement a 
Function0 even though an Iterable can be coerced to
a Function0.
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=463407

[463407]: Fixed bogus ambiguity validation

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/impl/DefaultReferenceUpdater.java

If the target element cannot be found with the new URI, add
information to the refactoring status about that.
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=463257

[463257]: Add error to the refactoring status

---

plugins/org.eclipse.xtext.ui.codetemplates.ui/src/org/eclipse/xtext/ui/codetemplates/ui/contentassist/CodetemplatesProposalProvider.java

If the template variable resolver is not available,
no proposal for it should be shown when editing 
templates.
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=462917#c10

[462917]: Don’t show cross reference proposal

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/TextReplacerContext.java
tests/org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.xtend
tests/org.eclipse.xtend.ide.tests/longrunning/xtend-gen/org/eclipse/xtend/ide/tests/quickfix/QuickfixTest.java

- assume the document is formattet after applying a semantic quickfix
- in the formatter, make sure only 'unknown' hidden regions are
formatted. 'unknown' regions are the regions that didn't exist before
the model was programmatically modified.

[formatter][xtend][quickfix] assume formatted doc after sem qucikfix :)

---

examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/formatting2/DomainmodelFormatter.xtend
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel/xtend-gen/org/eclipse/xtext/example/domainmodel/formatting2/DomainmodelFormatter.java
plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/formatting2/XtendFormatter.xtend
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/XtendFormatter.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/formatting2/IndentOnceAutowrapFormatter.xtend
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.xtend
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting2/IndentOnceAutowrapFormatter.java
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/AbstractFormatter2.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/IAutowrapFormatter.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/IFormattableDocument.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/IHiddenRegionFormatter.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/IHiddenRegionFormatting.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/AbstractHiddenRegionFormatter.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/DoubleHiddenRegionFormatter.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/FormattableDocument.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/HiddenRegionFormatting.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/SingleHiddenRegionFormatter.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/SinglelineCodeCommentReplacer.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/WhitespaceReplacer.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/ITextRegionAccess.java

The API useed to have the methods increaseIndentation() and
decreaseIndentation(). While this is quite flexible, it is also quite
likely that the two methods are not called symmetrically.
This can happen, if
- the developer forgets to call one of the methods
- due to a bug in the code's logic that calls one of the methods
- due to an exception that's being thrown after inc() has been called
and before dec() would be called. Exceptions are likely to be thrown
because formatter may be executed on syntactically broken documents.
If inc() and dec() aren't called symmetrically, the indenteation for the
remaining part of the document will be wrong which makes any formatter
look broken. Therefore, we can consider it to be the better solution to
apply one level of intention properly or not at …

[formatter] improve indent api

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/formatting2/ContentFormatter.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/FormatterRequest.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/impl/Serializer.java

* Fixed endless recursion in Serializer
* Renamed `FormatterRequest.formatUndenfinedTokensOnly` &rarr; `formatUndefinedHiddenRegionsOnly`

[xtext] Small fixes in Serializer and Formatter

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextEditor.java

Changed to instance scope to get events when syntax coloring changes.

[464591] [editor] Coloring not refreshed after a preference change

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/declaration/AnnotationReferenceProviderImpl.xtend
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/declaration/AnnotationReferenceProviderImpl.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/macro/declaration/DeclarationsTest.xtend
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/declaration/DeclarationsTest.java

[bug 465007] active annotations API - only copy explicit annotation values

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/impl/DefaultReferenceUpdater.java

https://bugs.eclipse.org/bugs/show_bug.cgi?id=463773

[463773] fixed "don't use ...parsetree.reconstr.ITransientValueService"

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/JdtClasspathUriResolver.java
tests/org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/util/JdtClasspathUriResolverTest.java

Resources from the project root may also be considered
to be on the classpath thus the JDT based resolver
finds those, too.
This is a shortcut since we’d need to introspect the
build.properties, too. OTOH different build technologies
may chose different description formats so the shortcut
seems to be a valid assumption.

[465080] Fixed classpath URI resolution

---

web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/XtextServiceDispatcher.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/model/DocumentSynchronizer.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/model/XtextWebDocumentAccess.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/XtextServiceDispatcher.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/model/DocumentSynchronizer.java

[web] handle operation canceled in async background process, use cancel-manager to check whether an exception is an operation-canceled-exception.

---

examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/formatting2/DomainmodelFormatter.xtend
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel/xtend-gen/org/eclipse/xtext/example/domainmodel/formatting2/DomainmodelFormatter.java
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.homeautomation/src/org/eclipse/xtext/example/homeautomation/formatting2/RuleEngineFormatter.xtend
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.homeautomation/xtend-gen/org/eclipse/xtext/example/homeautomation/formatting2/RuleEngineFormatter.java
plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/formatting2/XtendFormatter.xtend
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/XtendFormatter.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/annotations/formatting2/XbaseWithAnnotationsFormatter.xtend
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.xtend
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/formatting2/XtypeFormatter.xtend
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/annotations/formatting2/XbaseWithAnnotationsFormatter.java
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.java
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting2/XtypeFormatter.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/AbstractFormatter2.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/IFormattableDocument.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/FormattableDocument.java

- on exception, only cancel formatting of the current subtree
- don't format EObjects located outside the requested regions
- introduce document.interior(EObject, )
- introduce document.format for convenience
- introduce formatter.shouldFormat()

[formatter] several smaller improvements

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/JdtClasspathUriResolver.java

During classpath URI resolution, we may need to check project
roots if the file is not in a source folder but will be packaged.
Therefore we need to check the current project and all referenced
projects for a resource in the project root. To determine the
referenced projects, we need to unfold classpath containers like
the plugin classpath container.
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=465080

[465080] Unpack classpath containers when scanning projects

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/AbstractHiddenRegion.java

[466265|formatter] Precondition fails in textReplContext.withReplacer

---

plugins/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/smap/DerivedResourceMarkerCopier.java

- Reduced log level to warning
- Check IFile != null && IFile.exists
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=463338

[463338] Remaining work after fix for bug 462414

---

plugins/org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/access/jdt/JdtBasedTypeFactory.java
tests/org.eclipse.xtext.common.types.tests/tests/org/eclipse/xtext/common/types/access/jdt/SourceBasedJdtTypeProviderTest.java

JDT may expose an internal represenation of a missing annotation
value wrapped in an array.
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=467477

[467477] Guard against the internal NoValue: java.lang.Object

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/scoping/batch/ITypeImporter.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/DefaultBatchTypeResolver.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/naming/QualifiedName.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/scoping/IScope.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/scoping/IScopeProvider.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/scoping/impl/AbstractScope.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/naming/QualifiedNameTest.java

- Use QualifiedName.equalsIgnoreCase if appropriate
- Deserialize lowercase QN as lowercase instances from index
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=467565

[467565] Improved performance for case insensitive languages

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/analysis/GrammarConstraintProvider.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/sequencer/GenericSyntacticSequencer.java

- fixed GenericSyntacticSequencer
- didn't modify behaviour of GrammarConstraintProvider to avoid 
regressions; I'd rather deprecate the GrammarConstraintProvider.

[serilizer] fixed two bugs spotted by findbugs

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/batch/XtendBatchCompiler.java
plugins/org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/StandaloneBuilder.xtend
plugins/org.eclipse.xtext.builder.standalone/src/org/eclipse/xtext/builder/standalone/incremental/ResourceURICollector.xtend
plugins/org.eclipse.xtext.builder.standalone/xtend-gen/org/eclipse/xtext/builder/standalone/StandaloneBuilder.java
plugins/org.eclipse.xtext.builder.standalone/xtend-gen/org/eclipse/xtext/builder/standalone/incremental/ResourceURICollector.java
plugins/org.eclipse.xtext.util/src/org/eclipse/xtext/util/UriUtil.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/build/BuildRequest.xtend
plugins/org.eclipse.xtext/src/org/eclipse/xtext/workspace/FileWorkspaceConfig.xtend
plugins/org.eclipse.xtext/xtend-gen/org/eclipse/xtext/build/BuildRequest.java
plugins/org.eclipse.xtext/xtend-gen/org/eclipse/xtext/workspace/FileWorkspaceConfig.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/util/UriUtilTest.xtend
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/util/UriUtilTest.java

makes sure that folder URIs end with a trailing slash, so that they can
be used with isPrefix(), resolve() and deresolve()

add createFileUri(File) helper method

---

intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/build/BuildProgressReporter.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/build/BuildProgressReporter.java

I couldn’t reproduce it, but it could be that we hold a reference to a problemsView that was disposed (or even the project was already disposed) and keep adding messages. I changed the code to always go through getContainer() which internally checks for cancellation and dispose.
"AWT-EventQueue-0 14.1.3#IC-141.SNAPSHOT, eap:true 14.1.3#IC-141.SNAPSHOT, eap:true":
at com.intellij.ide.util.treeView.AbstractTreeUpdater.cancelAllRequests(AbstractTreeUpdater.java:326)
- waiting to lock <0x00000007eb866038> (a com.intellij.ide.util.treeView.AbstractTreeUpdater)
at com.intellij.ide.util.treeView.AbstractTreeUi.releaseNow(AbstractTreeUi.java:467)
at com.intellij.ide.util.treeView.AbstractTreeUi.access$1400(AbstractTreeUi.java:62)
at com.intellij.ide.util.treeView.AbstractTreeUi$12.perform(Abstract …

[idea] executing tests causes a deadlock in rare cases. (see thread dump below)

---

releng/org.eclipse.xtext.releng/releng/ant/xtext-build.ant

It would be useful to have an ant target that executes also the tests (I
took the launch configuration from
https://xtext-builds.itemis.de/jenkins/job/xtext-pull-request-verifier,
so that this should mimic what is executed for testing pull requests).

ant target for executing tests

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/DirtyStateEditorSupport.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/reconciler/XtextDocumentReconcileStrategy.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/XbaseCompiler.java
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/resource/BatchLinkableResourceStorageLoadable.xtend
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/resource/BatchLinkableResourceStorageWritable.xtend
plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/util/CustomTypeParameterSubstitutor.java
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/resource/BatchLinkableResourceStorageLoadable.java
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/resource/BatchLinkableResourceStorageWritable.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/ResourceStorageFacade.xtend
plugins/org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/ResourceStorageLoadable.xtend
plugins/org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/ResourceStorageWritable.xtend
plugins/org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/StorageAwareResource.xtend
plugins/org.eclipse.xtext/xtend-gen/org/eclipse/xtext/resource/persistence/ResourceStorageFacade.java
plugins/org.eclipse.xtext/xtend-gen/org/eclipse/xtext/resource/persistence/ResourceStorageLoadable.java
plugins/org.eclipse.xtext/xtend-gen/org/eclipse/xtext/resource/persistence/ResourceStorageWritable.java
plugins/org.eclipse.xtext/xtend-gen/org/eclipse/xtext/resource/persistence/StorageAwareResource.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerBug472142Test.xtend
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/CompilerTest.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/resource/ResourceStorageTest.xtend
tests/org.eclipse.xtend.core.tests/suites/org/eclipse/xtend/core/tests/compiler/CompilerSuite.java
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/CompilerBug472142Test.java
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/resource/ResourceStorageTest.java

Don’t write streams with bogus content to the stored resource. [1]
Also revert incomplete state that was read from storage. See bug 471535 [2]
[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=469679
[2] https://bugs.eclipse.org/bugs/show_bug.cgi?id=471535

[469679] Guard against missing adapter

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/findReferences/XtendReferenceFinder.xtend
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/findReferences/XtendReferenceFinder.java

IResourceAccess may be null thus we have to check
it before we access the resource

[470451] Fixed XtendReferenceFinder

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/conversion/IValueConverter.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/conversion/impl/AbstractLexerBasedConverter.java

If an AbstractLexerBasedConverter is configured
with a datatype rule, it will be disabled and an
error will be logged.

[469805] Handle bogus value converter configuration

---

plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/xbase/XbaseGeneratorFragment.xpt

The generated JvmModelInferrer was still referring to the deprecated
IJvmDeclaredTypeAcceptor.IPostIndexingInitializing#initializeLater in
the comment section.

updated comment in the generated JvmModelInferrer

---

plugins/org.eclipse.xtext.common.types.shared.jdt38/src/org/eclipse/xtext/common/types/shared/jdt38/OriginalEditorSelector.java

see: 
org.eclipse.xtend.ide.tests.editor.XbaseEditorOpenClassFileTest
https://xtext-builds.itemis.de/jenkins/job/xtend-ide-tests-master-latest/401/testReport/junit/

fixed regression in XbaseEditorOpenClassFileTest

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextScopeProvider.java

...instead of GlobalResourceDescriptionProvider. 
Because when the grammar is loaded from an .xtextbin file, 
the GlobalResourceDescriptionProvider returns null, because there
is no IResourceServiceProvider registered for *.xtextbin.

[xtext.xtext] use IResourceDescription.Manager for scoping

---

intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/debug/TraceBasedPositionManagerFactory.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/execution/ConfigurationProducerExtensions.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/trace/TraceForVirtualFileProvider.xtend
intellij/org.eclipse.xtext.idea/src/org/eclipse/xtext/idea/trace/VirtualFileInProject.xtend
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/debug/TraceBasedPositionManagerFactory.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/execution/ConfigurationProducerExtensions.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/trace/TraceForVirtualFileProvider.java
intellij/org.eclipse.xtext.idea/xtend-gen/org/eclipse/xtext/idea/trace/VirtualFileInProject.java

Change-Id: I70b24538cd241dfef4417a65b66543ac0e94902a

[idea][bug 475120] don't throw NPE for a psi element without an associated virtual file, e.g. PsiDirectory

---

plugins/org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/macro/JdtBasedProcessorProvider.xtend
plugins/org.eclipse.xtend.ide/xtend-gen/org/eclipse/xtend/ide/macro/JdtBasedProcessorProvider.java

Hi guys, how about this? If you were to accept this, then I could simplify http://git.eclipse.org/c/emf/org.eclipse.emf.eson.git/tree/plugins/org.eclipse.emf.eson/src/org/eclipse/emf/eson/generators/JdtBasedClassLoaderProvider.java to just do @Override isOutputFolderIncluded() { return true; } for what I need, instead of copy/pasting the entire createClassLoaderForJavaProject() .. so then I would not have to "catch up" doing https://git.eclipse.org/r/#/c/54483/1/plugins/org.eclipse.emf.eson/src/org/eclipse/emf/eson/generators/JdtBasedClassLoaderProvider.java when you do https://github.com/eclipse/xtext/commit/5d3aa9798fc1b04eac08e645b0022821af433e14 ... ;-)

JdtBasedProcessorProvider isOutputFolderIncluded()

---

plugins/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/builderState/AbstractBuilderState.java
plugins/org.eclipse.xtext.ui.shared/src/org/eclipse/xtext/ui/shared/internal/JavaCoreListenerRegistrar.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperJavaImpl.java

Reduced the lock size and deferred code that may need
the ws lock to another thread such that deadlocks should
become less likely.

[475368] Another approach to solve the deadlock issue

---

plugins/org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/NewXtextProjectWizard.java
plugins/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.xtend
plugins/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.xtend
plugins/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/WizardConfiguration.xtend
plugins/org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/ParentProjectDescriptor.java
plugins/org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/RuntimeProjectDescriptor.java
plugins/org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/WizardConfiguration.java

This is what most Maven/Gradle users are used to. It also allows Gradle
users to run tasks from subprojects (the root project is always searched
for by going up the directory chain)

[wizard] create a hierarchical project layout for Maven/Gradle

---

plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/parser/antlr/ex/ExternalAntlrLexerFragment.java
plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/parser/antlr/splitting/AntlrLexerSplitter.java
plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/parser/antlr/splitting/internal/LexerSpecialStateTransitionSplitter.java

Support for class splitting of lexer class in ExternalAntlrLexerFragment, 
requested by  [472489](https://bugs.eclipse.org/bugs/show_bug.cgi?id=472489).
Since Antlr predicates in custom lexer can reference non-static fields or methods,
DFA classes must stay non-static when class splitting is run from ExternalAntlrLexerFragment.
Signed-off-by: Jan Sebechlebsky <jan.sebechlebsky@cz.ibm.com>

[472489] Support class splitting in ExternalAntlrLexerFragment

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/jvmmodel/JvmTypesBuilder.java
tests/org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/jvmmodel/JvmTypesBuilderTest.xtend
tests/org.eclipse.xtext.xbase.tests/xtend-gen/org/eclipse/xtext/xbase/tests/jvmmodel/JvmTypesBuilderTest.java

The type reference could be null and a NPE should be avoided; this is
called by toGetter, and the problem is a regression due to my commit
4308750

Null guard in JvmTypesBuilder.isPrimitiveBoolean

---

examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel/src-gen/org/eclipse/xtext/example/domainmodel/validation/AbstractDomainmodelJavaValidator.java
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/GenerateDomainmodel.mwe2
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel/src/org/eclipse/xtext/example/domainmodel/validation/DomainmodelJavaValidator.java

With this commit, the DomainmodelJavaValidator extends the generated
AbstractDomainmodelJavaValidator (which, in turn, extends
XbaseJavaValidator) instead of extending XbaseJavaValidator directly (as
it is usual in other DSLs, as far as I know). I think the only reason
why it wasn't so before is that in the workflow the
NamesAreUniqueValidator was enabled, making the generated validator use
also NamesAreUniqueValidator, which is known to cause problems with
Xbase model inferred elements. So I disabled the NamesAreUniqueValidator
in the workflow as well.
Tests are still green.

Domainmodel validator should extend generated validator

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/JvmModelGenerator.xtend

Makes organizing imports in the JvmModelGenerator better configurable

Fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=478024

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/resource/XtendResourceDescriptionManager.xtend
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/resource/XtendResourceDescription.java
plugins/org.eclipse.xtext.java/src/org/eclipse/xtext/java/resource/JavaResource.xtend
plugins/org.eclipse.xtext.java/src/org/eclipse/xtext/java/resource/JavaResourceDescriptionManager.xtend
plugins/org.eclipse.xtext.java/xtend-gen/org/eclipse/xtext/java/resource/JavaResource.java
plugins/org.eclipse.xtext.java/xtend-gen/org/eclipse/xtext/java/resource/JavaResourceDescriptionManager.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/build/Indexer.xtend
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/build/XtendIncrementalBuilderTest.xtend
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/build/XtendIncrementalBuilderTest.java

JavaResources do not unload their derived state after indexing. They only do so when their getContents()-method is called the next time. That is too late when some referencing file is compiled first and fetches the stubs from the index. See the attached test case. 
We should mimic DerivedStateAwareResource(DescriptionManager).

Stale JvmTypes in the incremental builder

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/macro/ProcessorInstanceForJvmTypeProvider.xtend
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/ProcessorInstanceForJvmTypeProvider.java

Some alternate SDKs like the Android SDK don't just replace the JDK, but
add additional classes. Annotation processors like those from the
Xtendroid project may depend on this extended bootclasspath.

add bootclasspath to annotation processor classloader

---

plugins/org.eclipse.xtext.util/src/org/eclipse/xtext/util/formallang/PdaUtil.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/analysis/ContextTypePDAProvider.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/impl/FeatureFinderUtil.java
tests/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/serializer/XtextGrammarTestLanguageSemanticSequencer.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/serializer/ContextTypePDAProviderTest.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/serializer/GrammarConstraintProviderTest.java

[serializer] fixed 479397: compute types of wildcard fragments properly

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/compare/CompareFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/compare/CompareFragment2.java

Fixes a mistake in migration of 'CompareFragment'.

[xtext generator] added missing dependency addition in 'CompareFragment2'

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/analysis/ContextTypePDAProvider.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/serializer/ContextTypePDAProviderTest.java

A Grammar fragment invocation does only instantiate the current object
if the current object has not yet been instantiated.

[serializer] fix 479397#c10: Problem with Grammar Fragment Invocations

---

plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/serializer/SerializerFragment.xtend
plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/terminals/SyntheticTerminalDetector.java
plugins/org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/serializer/SerializerFragment.java

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=479919

[generator] Old SyntheticTerminalDetector inherits the new copy

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/grammarAccess/GrammarAccessExtensions.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/grammarAccess/GrammarAccessExtensions.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/grammarAccess/GrammarAccessUtilTest.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/generator/GrammarAccessExtensionsTest.xtend
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/xtext/generator/GrammarAccessExtensionsTest.java

Not all valid java identifiers are valid in Antlr
action contexts.

[480118] Fixed regression in new grammar access fragment

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/quickfix/QuickfixProviderFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/validation/ValidatorFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/validation/ValidatorNaming.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/quickfix/QuickfixProviderFragment2.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/validation/ValidatorFragment2.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/validation/ValidatorNaming.java

... from 'ValidatorFragment2' to 'ValidatorNaming'm updated 'QuickfixProviderFragment2' correspondingly.
This is just a follow-up on the migration of the 'QuickfixProviderFragment', which has been suggested by @oehme

[xtext generator] Extracted the composition of the generated validator classes' names

---

plugins/org.eclipse.xtext.util/src/org/eclipse/xtext/util/formallang/PdaUtil.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/analysis/GrammarPDAProvider.java
tests/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/serializer/XtextGrammarTestLanguageSemanticSequencer.java
tests/org.eclipse.xtext.tests/src-gen/org/eclipse/xtext/serializer/XtextGrammarTestLanguageSyntacticSequencer.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/serializer/GrammarPDAProviderTest.xtend
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/serializer/GrammarPDAProviderTest.java

when two unassigned rules calls followed one another, the second 
one was not properly considered

[serializer] fixed a bug in PDA construction

---

plugins/org.eclipse.xtext.util/src/org/eclipse/xtext/util/formallang/PdaUtil.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/fragments/AbstractFragmentsPlainParsingTest.xtend
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/parser/fragments/AbstractFragmentsPlainParsingTest.java

An immutable StackItem (implemented as linked list) that falls back to
an Iterator (which is mutable) really was a bug waiting to happen.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=479400#c5

[serializer] fixed an NPE

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/acceptor/SequenceFeeder.java

this avoids potential compile errors when users upgrade to Xtext 2.9.0

[serializer] reintroduce a deleted constructor as deprecated

---

plugins/org.eclipse.xtext.xbase/generator/org/eclipse/xtext/xbase/GenerateXbase.java
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/AbstractStubGeneratingFragment.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/IXtextGeneratorLanguage.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ImplicitFragment.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorLanguage.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/generator/GeneratorFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/scoping/ImportNamespacesScopingFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/serializer/SerializerFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/contentAssist/ContentAssistFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/labeling/LabelProviderFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/outline/OutlineTreeProviderFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/quickfix/QuickfixProviderFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/validation/ValidatorFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/AbstractStubGeneratingFragment.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/IXtextGeneratorLanguage.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ImplicitFragment.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorLanguage.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/generator/GeneratorFragment2.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/scoping/ImportNamespacesScopingFragment2.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/serializer/SerializerFragment2.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/contentAssist/ContentAssistFragment2.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/labeling/LabelProviderFragment2.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/outline/OutlineTreeProviderFragment2.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/quickfix/QuickfixProviderFragment2.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/validation/ValidatorFragment2.java

* addition of dedicated field + getter in 'AbstractStubGeneratingFragment'
* addition of dedicated flag 'generateXtendStubs' + getter in 'XtextGeneratorLanguage'
* update of using generator fragments
* update of 'GenerateXbase' Workflow

[xtext generator] fragment-wise selection of Java vs. Xtend stubs beyond 'preferXtendStubs'

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/AbstractStubGeneratingFragment.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/StandardLanguage.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/formatting/Formatter2Fragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/generator/GeneratorFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/grammarAccess/GrammarAccessFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/XtextAntlrGeneratorFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/scoping/ImportNamespacesScopingFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/serializer/SerializerFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/contentAssist/ContentAssistFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/labeling/LabelProviderFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/outline/OutlineTreeProviderFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/quickfix/QuickfixProviderFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/ui/refactoring/RefactorElementNameFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/util/BooleanGeneratorOption.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/util/GeneratorOption.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/validation/ValidatorFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/AbstractStubGeneratingFragment.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/StandardLanguage.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/grammarAccess/GrammarAccessFragment2.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/XtextAntlrGeneratorFragment2.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/scoping/ImportNamespacesScopingFragment2.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/types/TypesGeneratorFragment2.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/quickfix/QuickfixProviderFragment2.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/ui/refactoring/RefactorElementNameFragment2.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/util/BooleanGeneratorOption.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/util/GeneratorOption.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/web/WebIntegrationFragment.java

Solved problem: when using the StandardLanguage and overriding a fragment with its corresponding setter, the default options of the fragment were used instead of the default options of the StandardLanguage. Now it can detect whether explicit values have been set by the user, and apply its own default if not.

[generator] Introduced GeneratorOption

---

examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel/xtend-gen/org/eclipse/xtext/example/domainmodel/formatting2/DomainmodelFormatter.java
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.homeautomation/xtend-gen/org/eclipse/xtext/example/homeautomation/formatting2/RuleEngineFormatter.java
plugins/org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/formatting2/XtendFormatter.java
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/annotations/formatting2/XbaseWithAnnotationsFormatter.java
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting2/XbaseFormatter.java
plugins/org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/formatting2/XtypeFormatter.java
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/formatting/Formatter2Fragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/formatting/Formatter2Fragment2.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/AbstractFormatter2.java
tests/org.eclipse.xtext.testlanguages/xtend-gen/org/eclipse/xtext/testlanguages/backtracking/formatting2/BeeLangTestLanguageFormatter.java
tests/org.eclipse.xtext.testlanguages/xtend-gen/org/eclipse/xtext/testlanguages/noJdt/formatting2/NoJdtTestLanguageFormatter.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/formatting2/internal/GenericFormatterTester.xtend
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/internal/FormatterSerializerIntegrationTest.java
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/formatting2/internal/GenericFormatter.java
web/org.eclipse.xtext.web.example.statemachine/xtend-gen/org/eclipse/xtext/web/example/statemachine/formatting2/StatemachineFormatter.java

This incorporates two changes:
- for the generate-once stub, the formatter will only generate 
methods for the first two EClasses. Generating more will most
likely create code that breaks the next time the grammar is changed.
- have a generic _format(EObject) method in AbstractFormatter2 that 
does nothing but invoke the formatter-dispatch-method for all
direct children of the EObject.
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=480737

[formatter#480737] improve FormatterFragment.

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/analysis/ContextPDAProvider.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/analysis/ContextTypePDAProvider.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/analysis/GrammarPDAProvider.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/analysis/SemanticSequencerNfaProvider.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/analysis/SyntacticSequencerPDAProvider.java

If there are exceptions, they're likely to only affect individual parser
rules. Furthermore, partial output makes it much easier to diagnose
errors.

[serializer/analysis] on exception, log and try to continue

---

plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/parser/antlr/AbstractAntlrGeneratorFragment.java
plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/parser/antlr/ex/ExternalAntlrLexerFragment.java
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/AntlrOptions.xtend
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/splitting/AntlrLexerSplitter.java
plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/parser/antlr/splitting/internal/LexerSpecialStateTransitionSplitter.java
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/parser/antlr/AntlrOptions.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/parser/splitting/LexerSpecialStateTransitionSplitterTest.java

Switch in lexer in specialStateTransition can get really big, even after pulling code from case statements into separate methods.
Somewhere slightly over 1500 cases the specialStateTransition method can exceed 64kB limit. 
Implemented transformation will split such a method into several methods with defined maximal number of case statements (1000 by default).
Signed-off-by: Jan Sebechlebsky <jan.sebechlebsky@cz.ibm.com>

Conditionaly split switch in specialStateTransition method

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/parser/antlr/Lexer.java

I believe input should be consumed also when FailedPredicateException is thrown from the lexer. If not the while may keep spinning infinitely.

Fix freeze on FailedPredicateException

---

plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/parser/antlr/AntlrGrammarComparator.xtend
plugins/org.eclipse.xtext.generator/xtend-gen/org/eclipse/xtext/generator/parser/antlr/AntlrGrammarComparator.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/parser/AntlrGrammarComparatorTest.xtend
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/generator/parser/AntlrGrammarComparatorTestHelper.xtend
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/generator/parser/AntlrGrammarComparatorTest.java
tests/org.eclipse.xtext.tests/xtend-gen/org/eclipse/xtext/generator/parser/AntlrGrammarComparatorTestHelper.java

* comparator now ignores single & multi line comments (still counts line numbers),
* added corresponding tests
* moved test helper methods & classes into new helper class

[grammar comparison] enhanced grammar comparator to ignore comments

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/FeatureCallCompiler.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/XtendCompilerErrorHandlingTest.xtend
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/XtendCompilerErrorHandlingTest.java

Bug 482845 - [compiler] NPE in ScopeStack when building malformed Xtend

---

plugins/org.eclipse.xtext.xbase.lib/src/org/eclipse/xtext/xbase/lib/Pair.java

This PR simply makes the class org.eclipse.xtext.xbase.lib.Pair implements Serializable.
Signed-off-by: Miguel Jiménez <migueljimenezachinte@gmail.com>

Make the org.eclipse.xtext.xbase.lib.Pair class serializable

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/computation/XbaseTypeComputer.java

This method can be overridden in DSLs that introduce new containers for
variable declarations.  Currently, in such contexts, the whole
_computeTypes for the container, e.g., XBlockExpression, must be
overridden to intercept possible variable declarations.
This also reduces some code duplication ;)
This was also discussed with @szarnekow in chat.

Extracted method for adding possible var decl to the scope

---

tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.xtend
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/XtendCompilerTest.java

With PR #827 xbase.lib.Pair has been made Serializable (change 78096c12), which breaks two Xtend compiler tests. I updated the expectations.

Fixed Xtend compiler tests

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/TextReplacerContext.java
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/XtendFileFormatterTest.xtend
tests/org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/XtendFormatterBugTests.xtend
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendFileFormatterTest.java
tests/org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendFormatterBugTests.java

Modified the bigger than check to bigger than or equal on
isInRequestedRange as it would otherwise skip the last whitespace region
in a document.
Link to original bug : 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=482665

Fix for #482665

---

xtext-website/download.html

The `Release` button for the IntelliJ plugin on the download site still targeted version `2.9.0`. Updated the link to version `2.9.1` to prevent other users running into the issues described [here](https://www.eclipse.org/forums/index.php/m/1720259/#msg_1720259).

Updated IntelliJ plugin download link

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/service/ProviderModule.java

https://bugs.eclipse.org/bugs/show_bug.cgi?id=485263

Bug 485263: Allow javax.inject.Provider in provideX() methods of reflective modules

---

plugins/org.eclipse.xtend.core/src/org/eclipse/xtend/core/compiler/batch/Main.java

https://bugs.eclipse.org/bugs/show_bug.cgi?id=486491 Add Support for WriteTraceFiles to BatchCompiler-Main

Add Support for WriteTraceFiles to BatchCompiler-Main

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/parser/impl/TokenRegionProvider.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/PartialParserTest.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/TokenRegionProviderTest.java

The problem is in `TokenRegionProvider#getTokenRegion(String, ITextRegion)`: line 51 sets `currentEnd` to `currentStart`, resulting in a region length of zero, which does not cover the whole input region in that particular case.
I tried to simplify the code, please review.

Bug 486454: TokenRegionProvider computes a wrong region

---

plugins/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/contentassist/AbstractIdeTemplateProposalProvider.xtend
plugins/org.eclipse.xtext.ide/xtend-gen/org/eclipse/xtext/ide/editor/contentassist/AbstractIdeTemplateProposalProvider.java
web/org.eclipse.xtext.web.example.statemachine.ide/src/org/eclipse/xtext/web/example/statemachine/ide/StatemachineTemplateProposalProvider.xtend
web/org.eclipse.xtext.web.example.statemachine.ide/src/org/eclipse/xtext/web/example/statemachine/ide/StatemachineWebContentProposalProvider.xtend
web/org.eclipse.xtext.web.example.statemachine.ide/xtend-gen/org/eclipse/xtext/web/example/statemachine/ide/StatemachineTemplateProposalProvider.java
web/org.eclipse.xtext.web.example.statemachine.ide/xtend-gen/org/eclipse/xtext/web/example/statemachine/ide/StatemachineWebContentProposalProvider.java
web/org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/ContentAssistTest.xtend
web/org.eclipse.xtext.web/src/test/xtend-gen/org/eclipse/xtext/web/server/test/ContentAssistTest.java

Example:
```xtend
class StatemachineTemplateProposalProvider extends AbstractIdeTemplateProposalProvider {
def void createStateProposal(ContentAssistContext context, IIdeContentProposalAcceptor acceptor) {
val StringConcatenationClient template = '''
state «variable('name')»
«cursor»
end
'''
acceptProposal('state', 'Create a new state', template, context, acceptor)
}
}
```

[web] Added API for template proposals

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextConfigurableIssueCodes.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextValidator.java
tests/org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextValidationTest.java

Fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=488458
Add warning for keywords containing spaces

Add warning for keywords containing spaces

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/scoping/impl/ImportedNamespaceAwareLocalScopeProvider.java

https://bugs.eclipse.org/bugs/show_bug.cgi?id=409003
Signed-off-by: Michael Vorburger <mike@vorburger.ch>

[409003] ImportedNamespaceAwareLocalScopeProvider public getQualifiedNameConverter()

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/analysis/GrammarConstraintProvider.java

In one specific example with partial serialization via `XtextDocument.modify(..)` the average time for applying the modification was reduced from 80.7 seconds (before this change) to 5.8 seconds (after this change). Cloning the array and hash set seems to keep the GC quite busy in some cases.

Bug 484465: Improved serializer performance

---

web/org.eclipse.xtext.web/src/main/js/xtext/xtext-ace.js

The problem: when `xtext.createServices()` is called a second time, the new completer is not applied by Ace. This change makes the completer independent of its closure variables.

Bug 486615: completer function fetches the services from the given editor

---

web/org.eclipse.xtext.web.servlet/src/main/java/org/eclipse/xtext/web/servlet/XtextResourcesServlet.xtend
web/org.eclipse.xtext.web.servlet/src/main/xtend-gen/org/eclipse/xtext/web/servlet/XtextResourcesServlet.java

Also avoided usage of Servlet 3.0 API method `ServletRequest.getServletContext()`.

Bug 488635: Removed leading '/' in resource path

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/DirtyStateEditorSupport.java
tests/org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/editor/DirtyStateEditorSupportIntegrationTest.xtend
tests/org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/editor/DirtyStateEditorSupportIntegrationTest.java

Possible fix. We should defer the updating of the IResourceDescription of a dirty resource when the editor is marked as clean to the moment when the appropriate change is reconciled.

[bug 488380]  revised dirty state support

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/contentassist/AbstractContentProposalProvider.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/contentassist/AbstractJavaBasedContentProposalProvider.java

... in AbstractContentProposalProvider; switched to that method in AbstractJavaBasedContentProposalProvider.DefaultProposalCreator, fixes bug [488463]
Signed-off-by: Christian Schneider <christian.schneider@typefox.io>

[488463] [xtext.ui] introduced hook method 'getImage(IEObjectDescription)'

---

plugins/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/javasupport/ProjectClasspathChangeListener.java
plugins/org.eclipse.xtext.ui.shared/src/org/eclipse/xtext/ui/shared/internal/SharedContributionWithJDT.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/containers/AbstractJavaProjectsState.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/resource/Storage2UriMapperJavaImpl.java
plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/JavaProjectClasspathChangeAnalyzer.java
tests/org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/Bug486584Test.java
tests/org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJavaImplTest.xtend
tests/org.eclipse.xtext.ui.tests/xtend-gen/org/eclipse/xtext/ui/tests/core/resource/Storage2UriMapperJavaImplTest.java

Do not trigger FullBuild if ClasspathChange is a SourceAttachmentChange only. Fixes https://bugs.eclipse.org/bugs/show_bug.cgi?id=486584

Fix for Bug 486584

---

examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/ContentAssistTest.xtend
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/OutlineTest.xtend
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/tests/ContentAssistTest.java
examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/tests/OutlineTest.java
plugins/org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/ui/AbstractOutlineTest.java

https://bugs.eclipse.org/bugs/show_bug.cgi?id=488966
This allows to easily test the outline of a DSL: it gives an indented string representation of the outline that can be easily compared with multiline strings.

488966: provide an AbstractOutlineTest

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/LanguageSpecificURIEditorOpener.java

This fixes two problems:
- an invalid entry was put into the navigation history
- the UI was flickering a little, i.e. the editor displayed 
a wrong selection before it highlighted the right selection
The bug is fixed by running selectAndRevel() directly and not 
inside a job.
Make sure to read the comments in 
org.eclipse.ui.internal.NavigationHistory.markEditor(IEditorPart)
to understand this fix.
Possible drawbacks of this fix:
- if an editor takes a lot of time to selectAndReveal(), the UI may now
seem frozen during that time.
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=490385
Signed-off-by: Moritz Eysholdt <moritz.eysholdt@typefox.io>

fixes bug 490385: don't pollute navigation history

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/formatting2/regionaccess/internal/NodeHidden.java

Fixes an index guard that prevents
org.eclipse.xtext.formatting2.regionaccess.internal.NodeHidden#getPreviousHiddenPart()
from returning the first part of a hidden region.
Old behavior:
Given a hidden region consisting of two or more parts
When getPreviousHiddenPart() is called on the second part
Then null is returned
New behaviour:
Given a hidden region consisting of two or more parts
When getPreviousHiddenPart() is called on the second part
Then first part ist returned
Signed-off-by: Moritz Heindl <lenidh@gmail.com>

Fix index guard in getPreviousHiddenPart()

---

plugins/org.eclipse.xtext/src/org/eclipse/xtext/linking/impl/LinkingHelper.java
plugins/org.eclipse.xtext/src/org/eclipse/xtext/serializer/tokens/ValueSerializer.java

---Example---
Rule: name=FQN | name=STRING;
-------------
When FQN has been parsed but the serializer decided to write out 
STRING it was calling the IValueConverter with FQN's INode and rule 
STRING. That's obviously wrong input for the ValueConverter. 
The fix just prevents the IValueConverter to be called in this scenario,
causing the INode's text to be ignored; Instead fresh output is
generated via IValueConverter.toString(...) 
Signed-off-by: Moritz Eysholdt <moritz.eysholdt@typefox.io>

[serializer] never attempt to call ValueConverter with wrong rule

---

gradle/wrapper/gradle-wrapper.properties

Signed-off-by: Michael Vorburger <mike@vorburger.ch>

Upgrade Gradle wrapper version from 2.9 to 2.12

---

plugins/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.xtend
plugins/org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TestProjectDescriptor.java
tests/org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.ui.tests/pom.xml
tests/org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.ui.tests/pom.xml
tests/org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.ui.tests/pom.xml

If you have a ui test that needs the workbench or an editor, if you do
not have org.eclipse.osgi.compatibility.state, introduced in Luna, in
the dependencies the workbench and editors will be null and the UI tests
will fail. By adding org.eclipse.rcp feature as a dependency, then
org.eclipse.osgi.compatibility.state will be dragged in and UI tests
will work, since the workbench will be available.  Adding
org.eclipse.rcp is safe also for previous Eclipse target platforms,
while adding org.eclipse.osgi.compatibility.state only will not work in
Eclipse versions earlier than Luna.
At least, that's what I do to run UI tests that require the workbench.

Explicit dependency on org.eclipse.rcp in ui.tests

---

plugins/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
plugins/org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
tests/org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.target/org.xtext.example.full.target.target
tests/org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.full/org.xtext.example.full.parent/org.xtext.example.full.web/build.gradle
tests/org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.gradle/org.xtext.example.gradle.parent/org.xtext.example.gradle.web/build.gradle
tests/org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.target/org.xtext.example.mavenTycho.target.target
tests/org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTycho/org.xtext.example.mavenTycho.parent/org.xtext.example.mavenTycho.web/pom.xml
tests/org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.target/org.xtext.example.mavenTychoP2.target.target
tests/org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.mavenTychoP2/org.xtext.example.mavenTychoP2.parent/org.xtext.example.mavenTychoP2.web/pom.xml
tests/org.eclipse.xtext.tests/testdata/wizard-expectations/org.xtext.example.plainMaven/org.xtext.example.plainMaven.parent/org.xtext.example.plainMaven.web/pom.xml

The target definition file generated by the Xtext project wizard is not set to include the sources, that is, includeSource="false".
Instead, I think that sources should be included by default in a target definition file: if the developer uses the .target file for defining the target platform of his workbench, then having the sources while developing is really helpful.  I know that for some features the generated .target file includes the .sdk which already includes sources (e.g., Xtext and EMF), but that's not the case for the platform, pde and jdt.
On the other hand, including sources will not disturb the Tycho build, since the includeSource is ignored by default.  This means that sources will not have to be downloaded during the target platform resolution of the Maven/Tycho build. …

Bug 492234 - [wizard] Include sources in the generated .target file

---

web/org.eclipse.xtext.web.example.jetty/src/main/webapp/orion-statemachine-autogenerate.html
web/org.eclipse.xtext.web.servlet/src/main/java/org/eclipse/xtext/web/servlet/XtextServlet.xtend
web/org.eclipse.xtext.web.servlet/src/main/xtend-gen/org/eclipse/xtext/web/servlet/XtextServlet.java
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/IUnwrappableServiceResult.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/XtextServiceDispatcher.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/generator/GeneratorResult.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/generator/GeneratorService.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/model/AbstractCachedService.xtend
web/org.eclipse.xtext.web/src/main/js/xtext/ServiceBuilder.js
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/IUnwrappableServiceResult.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/XtextServiceDispatcher.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/generator/GeneratorResult.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/generator/GeneratorService.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/model/AbstractCachedService.java
web/org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/GeneratorTest.xtend
web/org.eclipse.xtext.web/src/test/xtend-gen/org/eclipse/xtext/web/server/test/GeneratorTest.java

If `allArtifacts` is set to `true`, the generator service returns all artifacts instead of a specific one. If `includeContent` is set to `false`, only the name and the content type of the requested artifact(s) is returned. That can be useful if the artifact names are not known in the client, e.g. when the JvmModelInferrer is used to generate Java types and the names of these types depend on the document contents. Then you can either fetch all generated types at once or first fetch their names and then send a dedicated request for each type.
Please review.

[web] Added generator service options 'allArtifacts' and 'includeContent'

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/ProjectFactory.java
plugins/org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/XtextProjectCreator.java

The Xtext project wizard does not work together with Buildship when selecting Intellij Plugin and Gradle: Buildship throws an exception because it can't find org.xtext.example.mydsl.parent/org.xtext.example.mydsl.idea/.settings/org.eclipse.buildship.core.prefs
This PR generates that file instead of gradle.prefs (which, anyway, would be converted to org.eclipse.buildship.core.prefs. The convertion would not take place for the .idea project because JavaProjectFactory.enhanceProject would fail to set the classpath, since Buildship throws the above exception).
ATTENTION: this also requires ProjectCreator.createProject to enhance the project ONLY AFTER having called all the contributors.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=492728

Bug 492728 - [wizard][gradle] Project Wizard, IntelliJ Plugin, Gradle and Buildship problems

---

plugins/org.eclipse.xtext.xbase/META-INF/MANIFEST.MF

https://bugs.eclipse.org/bugs/show_bug.cgi?id=492661

[492661] add missing javax.annotation package import

---

plugins/org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/xbase/XbaseGeneratorFragment2.xtend
plugins/org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/xbase/XbaseGeneratorFragment2.java

The generated JvmModelInferrer was still referring to the deprecated
IJvmDeclaredTypeAcceptor.IPostIndexingInitializing#initializeLater in
the comment section.
This corresponds to the old PR https://github.com/eclipse/xtext/pull/435
whose fix had not been ported to the new generator infrastructure.

updated comment in the generated JvmModelInferrer for the new generator infrastructure

---

examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel.ui/build.properties

Recently, Xtend files has been added to domainmodel.ui, and the
xtend-gen folder was not in the build.properties

missing xtend-gen source folder in domainmodel.ui

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/util/ProjectFactory.java
plugins/org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/XtextProjectCreator.java

I'm afraid that with this PR https://github.com/eclipse/xtext/pull/1015 for bug 492728 I introduced a small bug that makes the Xtext project wizard generate a build.properties where plugin.xml is always bin.included, leading to warnings in the generated projects. Sorry about that O:)
In the PR I swapped the execution of project contributors and enhanceProject (aa766a03f3a346d25152e634cc8a5cfed8719cea), and the latter will always generate a build.properties with that inclusion, overriding what the project contributors have generated.
To fix this, while keeping the fix for bug 492728 (which requires that the buildship properties file is generated *before* enhancing the projects) I introduced early contributors, which are executed before enhancing the project.
Thus the workflow would be: …

493399: [wizard] plugin.xml in bin.includes in all generated projects

---

plugins/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/internal/ExpressionScope.java
tests/org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/contentassist/Bug448483Test.xtend
tests/org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/contentassist/Bug448483Test.java

[448483] prevent npe in content assist for zero param operator_* methods

---

web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/model/XtextWebDocument.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/syntaxcoloring/HighlightingService.xtend
web/org.eclipse.xtext.web/src/main/java/org/eclipse/xtext/web/server/validation/ValidationService.xtend
web/org.eclipse.xtext.web/src/main/js/xtext/ServiceBuilder.js
web/org.eclipse.xtext.web/src/main/js/xtext/services/XtextService.js
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/model/XtextWebDocument.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/syntaxcoloring/HighlightingService.java
web/org.eclipse.xtext.web/src/main/xtend-gen/org/eclipse/xtext/web/server/validation/ValidationService.java

* Made `XtextWebDocument.clearCachedServiceResults()` public: in some applications it is necessary to recompute the cached services on changes of the environment, not only on text change.
* Updated JavaDoc.
* Added overloaded variant of `XtextService.initialize()`: This function is used frequently for custom services, so a shorter version has been added for convenience.
* Changed XtextService implementation so it adds to the function prototype instead of replacing it.

[web] Several improvements

---

plugins/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/findrefs/LoadingResourceAccess.java

Change-Id: I03b3bc26a8335ca7638e217d7aac1f80787b3fcd

[bug 494120]: Trim a uri's fragment to load a resource in LoadingResourceAccess

---

examples/org.eclipse.xtext.xtext.ui.examples/contents/org.eclipse.xtext.example.domainmodel.tests/src-gen/org/eclipse/xtext/example/domainmodel/DomainmodelInjectorProvider.java
plugins/org.eclipse.xtext.generator/src/org/eclipse/xtext/generator/junit/Junit4Fragment.xpt

While working on https://github.com/eclipse/xtext/pull/1040 the generated injector provider for the old mwe2 contains an additional useless
```
import com.google.inject.Injector;
```
This fixes it

fixed generated injector provider for old mwe2

---

xtext-website/community.html

Accent character in an author name was not well formatted.

Fixing typo error in author's name.

---

CONTRIBUTING.md

As discussed in the committer meeting of July 22nd, I wrote a proposal for how we could leverage milestones and labels in the Xtext project.
I investigated the usage of labels in [vscode](https://github.com/Microsoft/vscode/labels), [jupyterlab](https://github.com/jupyter/jupyterlab/labels), and [guava](https://github.com/google/guava/labels). You can see the result in [this table](https://drive.google.com/file/d/0B7HlHK64o5nLLW5EQ2x0Ymc0QUE/view?usp=sharing). All three projects have three kinds of labels in common:
* Type (`bug`, `enhancement`, etc.)
* Status (`help wanted`, `duplicate`, etc.)
* Component (`build system`, `editor`, etc.)
My proposal follows this categorization and includes all labels that are created by GitHub for new repositories. This is meant as a starting point and …

Workflow for milestones and issue labels

---

xtend-website/Gemfile

Fixed Broken Code Highlighting on Xtend Website. #1091

Fixed Broken Code Highlighting on Xtend Website. #1091

---

CONTRIBUTING.md

Due to a [bug in EGit](https://bugs.eclipse.org/bugs/show_bug.cgi?id=526867), Eclipse could not clone the Xtext repos on startup in my installation. However, I did not know that the setup will clone the repos automatically and set up the workspace for you. To make that clear, I added the following sentence:
```
When you run your freshly installed Eclipse IDE for the first time it will clone the relevant repositories and automatically set up your workspace with a number of projects.
```

Add info about the finiseh setup process to contrib. guide

---

CONTRIBUTING.md

Add information about two factor authorisation needing to be disabled on Github and the need for a Eclipse account.
Fixes #1144

Add more information about GitHub/Eclipse accounts to  contributing guidelines 

---

CONTRIBUTING.md

The change:
```
9. [Sign off](https://git-scm.com/docs/git-commit#git-commit--s) your commits using the same email address you are using for your Eclipse account.
```

Add info about signing off commits to quality guide

---

xtext-website/index.html

Remove logos from companies not member of eclipse foundation.
Also update link to EclipseCon from 2017 to 2018.
Signed-off-by: Arne Deutsch <Arne.Deutsch@itemis.de>

Bug 539605: Remove logos from companies not member of eclipse

---

xtext-website/documentation/103_domainmodelnextsteps.md
xtext-website/documentation/303_runtime_concepts.md
xtext-website/documentation/310_eclipse_support.md

[eclipse/xtext-core#1223] adapted documentation snippets to use Java  instead of Xtend to align with wizard

[eclipse/xtext-core#1223] adapted documentation snippets to use Java  instead of Xtend to align with wizard

---

xtext-website/_posts/releasenotes/2020-03-03-version-2-21-0.md

added hint to new lsp4j to release notes
https://github.com/eclipse/xtext-core/issues/1244

added hint to new lsp4j to release notes

---

xtext-website/_posts/releasenotes/2020-03-03-version-2-21-0.md

generalized deprecation hint

---

xtext-website/documentation/302_configuration.md

- Update the link to the MWE2 documentation to point to the
documentation located in the own MWE2 repository.

[#1095] Update link to the MWE2 documentation on the Xtext website.

---

dev-doc/RegenerateLanguages.md

- This document describes things that need to be done when regenerate
the test- and production languages.

Add 'Regenerate Languages' documentation to the 'dev-doc'.

---

xtend-website/_posts/releasenotes/2020-09-01-version-2-23-0.md
xtext-website/_posts/releasenotes/2020-09-01-version-2-23-0.md

[#1804] added hint about Java 11 move to release notes

[#1804] added hint about Java 11 move to release notes

---

xtext-website/_posts/releasenotes/2020-09-01-version-2-23-0.md

Signed-off-by: nbhusare <neerajbhusare@gmail.com>

Added notes related to the quick-fix improvements made in xtext-eclipse/issues/1448

---

xtext-website/_posts/releasenotes/2020-12-01-version-2-24-0.md
xtext-website/documentation/350_continuous_integration.md

[eclipse/xtext#1861] update to MWE(2) 1.6.0/2.12.0

[eclipse/xtext#1861] update to MWE(2) 1.6.0/2.12.0

---

xtext-website/_posts/releasenotes/2020-12-01-version-2-24-0.md

[#1697] added hint about new Java Formatter API in rel notes

[#1697] added hint about new Java Formatter API in rel notes

---

xtend-website/_config.yml

Update Google Guava version from 27.1.0 to 30.1.0
Signed-off-by: miklossy <miklossy@itemis.de>

https://github.com/eclipse/xtext/issues/1862 Guava 30.1.0

---

xtext-website/_includes/header.html

The Typefox link in the training menu was old.

Changed the link to the Typefox website 

---

org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/feature/.project
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/repository/.project
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.releng/tp/.project

Note that I renamed only the projects' names, not the directories, so from the Maven point of view nothing changes. Moreover, we only zip the releng project with its contents in the examples, so the ant script for zipping the examples doesn't need to be changed
Closes #2166

Rename releng projects in Domainmodel example

---

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/contentassist/IdeContentProposalProvider.java

this way the employed services can be replaced in a subclass

rely on the getters like 'getScopeProvider()' instead of the corresponding fields in 'IdeContentProposalProvider'

---

.github/workflows/maven.yml
full-build.sh

Closes #2199 
Looks like it's working as expected.
For example, in JIRO I see:
```
17:24:26  testUiTestBetweenTwoRuntimeTests(org.eclipse.xtext.ui.tests.InjectorProviderTest)  Time elapsed: 0.037 s
17:24:26  
17:24:26  Results:
17:24:26  
17:24:26  Flakes: 
17:24:26  org.eclipse.xtext.ui.tests.editor.occurrences.MarkOccurrencesTest.testMarkOccurrencesCrossFile(org.eclipse.xtext.ui.tests.editor.occurrences.MarkOccurrencesTest)
17:24:26    Run 1: MarkOccurrencesTest.testMarkOccurrencesCrossFile:132 » NullPointer
17:24:26    Run 2: PASS
17:24:26  
17:24:26  
17:24:26  Tests run: 1753, Failures: 0, Errors: 0, Skipped: 21, Flakes: 1
```
So it reran a failed test, the second time it passed, and it has been recorded in the log as "flake", as documented here …

For flaky tests: -Dsurefire.rerunFailingTestsCount=2

---

pom.xml

While waiting for https://github.com/eclipse/xtext/pull/2205 to be merged, I cherry picked the commit for bootstrapping against 2.31.0.M0

xtend-maven-plugin-version 2.31.0.M0

---

.github/workflows/external-pr.yml

This is the only solution I've found to build PRs only from external forks.
This is not directly supported by GitHub Actions, so we have to use this "trick".
The job for our internal PRs is started, but all the steps are skipped.

Build only external PRs

---

org.eclipse.xtext.common.types.edit/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.common.types.shared.jdt38/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.common.types.shared/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.common.types.ui/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.junit4/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.m2e/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.ui.codemining/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.ui.codetemplates.ide/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.ui.codetemplates.ui/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.ui.codetemplates/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.ui.ecore/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.ui.shared/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.ui.testing/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.ui/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.web/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.xbase.junit/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.xbase.ui.testing/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.xbase.ui/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.xbase.web/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.xtext.ui.examples/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.xtext.ui.graph/.settings/org.eclipse.jdt.core.prefs
org.eclipse.xtext.xtext.ui/.settings/org.eclipse.jdt.core.prefs
pom.xml

Quoting from https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-release.html
> The --release option ensures that the code is compiled following the rules of the programming language of the specified release, and that generated classes target the release as well as the public API of that release. This means that, unlike the [-source and -target options](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html), the compiler will detect and generate an error when using APIs that don't exist in previous releases of Java SE.
This means that we can forget about compiling with Java 11 and safely compile with Java 17 always. If we tried to use API not present in Java 11 we would get a compilation error.
This would allow us to …

compiler release option

---

.github/workflows/external-pr.yml
.github/workflows/maven.yml
Jenkinsfile
jenkins/nightly-deploy/Jenkinsfile

This PR only contains a few minor simplifications of Xtext Github workflows and Jenkins pipeline that do not change the result.

Minor simplifications and clean-ups of build pipeline/workflows

---

releng/org.eclipse.xtext.contributor/Xtext.setup

As suggested in https://github.com/eclipse/xtext/pull/2207 this PR aims to simplify Xtext's Oomph setup by using the xtext-target files used in the Tycho/Maven build also in the Target-Platform of the development workspace.
This avoids the need to replicate and maintain all different target platforms as pure Oomph Targlets.
Use one TargletTask for each xtext-target file (the targlet-task contains the target-file as 'composedTarget') and use a corresponding filter to activate that task if the 'eclipse.target.platform' variable has a corresponding value.
Only for the o.e.cbi.p2repo.analyzers dependencies a always active TargletTask with corresponding Targlet is created, because they are not contained in the target-definition specified by the target-files. That targlet is merged with the one …

[Setup] Reference xtext target-files in Xtext's Oomph Setup directly

---

org.eclipse.xtext.common.types.tests/pom.xml

Closes #2229 
I think that listing transitive dependencies of mwe2 is a better approach, but I still think mwe2 POMs should be fixed under that respect

macOS failure in GitHub Actions

---

org.eclipse.xtext.junit5.tests/pom.xml
org.eclipse.xtext.testing.junit5.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.testing.junit5.tests/pom.xml
org.eclipse.xtext.testing.junit5.tests/src/org/eclipse/xtext/testing/tests/junit5/ComposedInjectAnnotationTest.java
pom.xml
xtext-latest.target
xtext-r202209.target
xtext-r202212.target
xtext-r202303.target

align junit5 in target platforms with eclipse jdts

align junit5 in target platforms with eclipse jdts

---

Jenkinsfile
pom.xml

@cdietrich @HannesWell I had a few spare time and I wanted to try my idea to deal with Tycho 3 on Java 17 and Tycho 2.7.5 on Java 11.
The parameterization of the Jenkinsfile is pretty simple, IMHO. Whether it works it's still under testing.
I've only tested it on my fork and GitHub actions with a dedicated job for Java 11, overriding `tycho-version` and it works like a charm.
This is a temporary workaround to switch to Tycho 3 until the toolchain stuff is ready.

Tycho 3 and parameterized Jenkins job

---

Jenkinsfile
jenkins/nightly-deploy/Jenkinsfile
org.eclipse.xtend.maven.parent/pom.xml
org.eclipse.xtext.maven.parent/pom.xml
pom.xml
releng/toolchains.xml

This PR migrates the xtext Maven+Tycho build to use Tycho 3.0.4 and sets up Maven toolchains. By using Maven toolschains one can ensure that all Plugins that only require Java-11 are build with a Java-11 JDK while at the same time the build is running in a Java-17 JRE (which is required since Tycho 3).
To enable that the `toolchains.xml` specifies a list of available JDK installations, which java version they implement and where they are located. The maven-toolchain-plugin then reads that file and tells all toolchain aware plugins, like the `maven-compiler/surefire-plugin` or `tycho-compiler/surefire-plugin` (when configured accordingly), where to find the corresponding JDK installation.
With this change the `JDK_VERSION` parameter of Xtext's Jenkins-Pipeline only specifies the JDK …

Build with Tycho 3.0.4 and set up Maven toolchains

---

Jenkinsfile

Initially suggested in https://github.com/eclipse/xtext/pull/2223, but reverted to make that PR simpler to review, I now want to suggest again in a smaller scope to simplify the `JDK_VERSION` parameter of the Xtext's Jenkins pipeline.
Furthermore I assume that, although Xtext is compiled against Java-11 testing with Java-17 is often more interesting and therefore suggest to use 17 as default (and therefore as first). 
Or do you want to leave the Java-17 testing to the GH-workflows?
In the same sense it could also be considered to make the latest TP the default/first.

Simplify JDK_VERSION parameter and make 17 the default value

---

releng/org.eclipse.xtext.contributor/Xtext.setup

After the attempt to remove the itemis feature from Xtext's target files in https://github.com/eclipse/xtext/pull/2219 failed, this PR removes the itemis feature from Xtext's Oomph setup to avoid having it defined one more time than necessary.

Remove 'de.itemis.xtext.antlr.feature' from Setup targlet

---

.github/workflows/maven.yml

As desribed in the [GH workflow docs for the push event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push), if one specifies the `branches` filter all non-matching refs are ignored by the workflow.
Consequently when running on any branch, all tags are excluded.
Tested it in my fork and it worked as expected.
Fixes https://github.com/eclipse/xtext/issues/2644

Don't run 'Build' GH workflow when tags are pushed

---

org.eclipse.xtend.maven.parent/pom.xml
org.eclipse.xtext.dev-bom/pom.xml
org.eclipse.xtext.maven.parent/pom.xml

This ensures that the `deploy-maven-plugin` is consistently used with the same version to avoid problems like https://github.com/eclipse/xtext/pull/2620#issuecomment-1550441789

harmonized maven-deploy-plugin

---

Jenkinsfile
jenkins/nightly-deploy/Jenkinsfile

Closes #2669 
Instead of triggering the nightly deployment job nightly, we trigger it from the main Jenkinsfile when something is pushed to `main`. Note that the trigger takes place only for the `main` branch and when the main job is NOT triggered manually nor on schedule.
This also removes the nightly schedule from the nightly job.
Of course, maybe we could rename the nightly job since it's not nightly anymore ;)
Maybe in another PR?
I would not rename the URL of the nightly update site, though.

Continuous deployment of the main branch

---

org.eclipse.xtend.core/pom.xml
org.eclipse.xtext.builder.standalone/pom.xml
org.eclipse.xtext.common.types.tests/pom.xml
org.eclipse.xtext.dev-bom/pom.xml
org.eclipse.xtext.java/pom.xml
org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/bug463946/pom.xml
org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml
org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/xcore-lang/pom.xml
org.eclipse.xtext.xbase.testing/pom.xml

[#2174] bump platform maven artifacts to 2023-03

[#2174] bump platform maven artifacts to 2023-03

---

org.eclipse.xtext.xtext.wizard/META-INF/MANIFEST.MF

[#2720] use import package for args4j in manifest
this wont solve the same problem in category.xml / targets / features

[#2720] use import package for args4j in manifest

---

org.eclipse.xtext/src/org/eclipse/xtext/resource/persistence/ResourceStorageFacade.java

as these are not simple getter methods.

Avoid repeated calls to getBinaryStorageURI and getURIConverter

---

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/util/PositionReaderTest.java
org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/util/PositionReader.java

The previous implementation of PositionReader extended LineNumberReader. Unfortunately, the implementation of PositionReader.read() compresses line endings. In other words, both "\n" and "\r\n" contribute one character to the document offset count. This behavior is undesired, and can lead to the production of incorrect line and column offsets.
This commit changes PositionReader to extend BufferedReader instead. Now, calling read() always reads exactly one character. We also implement logic specific to PositionReader to correctly handle both "\r\n" and "\n" line endings.
The PositionReader class now also keeps track of both the line and column values internally. The mark() and reset() functions have been updated accordingly, to correctly fulfill the contract.

[#2715] Fix PositionReader's handling of files with CRLF line endings

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/tasks/TaskMarkerContributor.java

Restore old exception handling for

Restore old exception handling for

---

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/XtextBuilder.java
org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/access/jdt/JdtTypeProvider.java

Added getter for workingCopyOwner and toBeBuiltComputer with protected access for https://github.com/eclipse/xtext/issues/2756
Signed-off-by: Shashwat Anand <shashwat.work@gmail.com>

Added getter for workingCopyOwner and toBeBuiltComputer with protected

---

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/DocumentSymbolTest.java
org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.java
org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/symbol/DocumentSymbolMapper.java
org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/symbol/DocumentSymbolService.java
org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/symbol/HierarchicalDocumentSymbolService.java
org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/symbol/IDocumentSymbolService.java
org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/symbol/WorkspaceSymbolService.java
org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/AbstractLanguageServerTest.xtend
org.eclipse.xtext.testing/xtend-gen/org/eclipse/xtext/testing/AbstractLanguageServerTest.java

I didn't add any new tests as all ide tests were green. Please let me know if I can add any tests for any missing coverage for this issue (https://github.com/eclipse/xtext/issues/2179).

Removed usage of SybmolInformation from IDocumentSymbolServer and adapted other classes

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractQuickfixTest.java

See: https://github.com/eclipse/xtext/issues/2808

#2808: Fix possible NPE in AbstractQuickFixTest

---

org.eclipse.xtext.xbase.ide/src/org/eclipse/xtext/xbase/ide/highlighting/XbaseHighlightingCalculator.java

We have a customized language where we inject extra objects into the AST that don't have a corresponding text node.
Consequently the node is null, which breaks the standard `XbaseHighlightingCalculator`. In all other cases null nodes are ignored too.

Ignore NumberLiterals without CompositeNode in HighlightingCalculator

---

org.eclipse.xtext.testlanguages/src/org/eclipse/xtext/testlanguages/backtracking/formatting/BeeLangTestLanguageFormatter.java
org.eclipse.xtext.testlanguages/src/org/eclipse/xtext/testlanguages/backtracking/formatting/ExBeeLangTestLanguageFormatter.java
org.eclipse.xtext.testlanguages/src/org/eclipse/xtext/testlanguages/backtracking/formatting/SimpleBeeLangTestLanguageFormatter.java
org.eclipse.xtext.ui.codetemplates/src/org/eclipse/xtext/ui/codetemplates/formatting/CodetemplatesFormatter.java
org.eclipse.xtext.ui.codetemplates/src/org/eclipse/xtext/ui/codetemplates/formatting/TemplatesFormatter.java
org.eclipse.xtext.web/src/test/java/org/eclipse/xtext/web/server/test/languages/formatting/StatemachineFormatter.java

The `XtextFormattingTokenSerializer` referred to in JavaDocs no longer exists and it seems to have been refactored into the [`XtextFormatter`](https://github.com/eclipse/xtext/blob/main/org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextFormatter.java).

Update `XtextFormattingTokenSerializer` references in JavaDocs

---

org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/project/XtextProjectCreator.java

https://github.com/eclipse/xtext/issues/2498
Closes #2498 
Note that our Cli tests do not use the XtextProjectCreator, so they don't generate .classpath.
So, I tested this manually.

Plugin test projects should not use "target/test-classes" in .classpath

---

org.eclipse.xtend.ide/META-INF/MANIFEST.MF

The bundle `o.e.osgi.services` is deprecated for removal as part of https://github.com/eclipse-equinox/equinox/issues/18 and already has been changed to be empty and only re-export the 'official' OSGi artifacts published to Maven-Central.
It should be replaced by imports of the desired org.osgi.service.* packages so that the runtime can choose a suitable provider independently of the bundle name.

Replace dependency to org.eclipse.osgi.services

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java

Xtend: fixed strange error message for `void` as a field type

---

org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/JvmModelGenerator.xtend
org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/compiler/output/TreeAppendable.java
org.eclipse.xtext.xbase/xtend-gen/org/eclipse/xtext/xbase/compiler/JvmModelGenerator.java

Since we already assume that the import manager is part of the appendable, which is a TreeAppendable, I think it's better to do the case and expose getImportManager in TreeAppendable than to call that method with two reflective calls.
This would also allow clients to provide a custom TreeAppendable; with the reflective call this latter use-case would not be supported

don't retrieve the ImportManager by reflection

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/AbstractXtendTestCase.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/java8/validation/Java8ValidationTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/OverrideValidationTest.java
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/ValidationBug435020Test.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/XtendValidationTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/java8/validation/Java8ValidationTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/validation/ValidationBug435020Test.java

WIP
while working on #2349 I noted that some situations were not tested

Added additional Xtend validator tests

---

org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/refactoring/ProgressReportingTest.java

Closes #2836 
I created an easier way to specify the expectation as a string.

[2836] adapt to changes in ltk.refactoring

---

org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/AbstractXtendCompilerMojo.java
org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/XtendCompile.java
org.eclipse.xtend.maven.plugin/src/main/java/org/eclipse/xtend/maven/XtendTestCompile.java

Closes #2332 
We were using the deprecated `getCompileArtifacts` and `getTestArtifacts` and they would add nothing to what we already retrieved for the classpath with `getCompileClasspathElements` and `getTestClasspathElements`; by the way, the latter already return strings, while the former returned `Artifact` that then we turned into strings.
Having a look at the Maven sources of `MavenProject` you can see that:
```java
public List<String> getCompileClasspathElements()
throws DependencyResolutionRequiredException
{
List<String> list = new ArrayList<>( getArtifacts().size() + 1 );
String d = getBuild().getOutputDirectory();
if ( d != null )
{
list.add( d );
}
for ( Artifact a : getArtifacts() )
{
if ( a.getArtifactHandler().isAddedToClasspath() )
{
// TODO let the scope handler deal with …
```

Fix maven deprecations in xtend-maven-plugin

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/validation/MarkerCreator.java

Closes #2792 
This allows the Problems View to be correctly sorted according to Location (line numbers).
The current situation wrongly sorts according to the location because we set it with a line number and the path of the resource:
with this patch, we get the correct behavior:

[2792] don't set marker.LOCATION and just set LINE_NUMBER

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/compiler/AccessorsCompilerTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/OverrideValidationTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/compiler/AccessorsCompilerTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java

While working on #2349 I discovered that Xtend puts an INCOMPATIBLE_RETURN_TYPE marker on the whole field; this happens, e.g., when an active annotation like `Accessors` is put on a field in a subclass of another class; the `Accessors` creates a getter or setter that might conflict with an inherited getter or setter:
This PR, independently from #2349, allows the marker to be put on the incompatible type, just like it happens for overridden methods:
This PR also improves a few other Xtend tests checking also the position of the error marker. The relevant change in Xtend is this one: https://github.com/eclipse/xtext/compare/main...LorenzoBettini:lb_xtend_validation_tests?expand=1#diff-7eccd6f746520f0ceab7a1355467b7ca7009462eec0d4efa65b4e23749e40f95R886

[Xtend] put INCOMPATIBLE_RETURN_TYPE marker on field's type 

---

org.eclipse.xtext.web.servlet/pom.xml
org.eclipse.xtext.web/pom.xml
org.eclipse.xtext.xbase.web/pom.xml
pom.xml

To avoid classloading problems
and API incompatibility when running in a Tycho build.
Closes https://github.com/eclipse/xtext/issues/2914

use maven-bundle-plugin with extensions=true

---

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/SemanticTokensTest.java
org.eclipse.xtext.ide.tests/testlang-src/org/eclipse/xtext/ide/tests/testlanguage/syntaxcoloring/SemanticHighlightingCalculator.java
org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/editor/syntaxcoloring/HighlightingStyles.java
org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/semantictokens/SemanticTokensService.java

TokenType is 0 based and represents the index in the list of supported token types.
0 is valid for TokenType and TokenModifiers, so we do not need to check for 0 here.
I added all supported TokenTypes and TokenModifiers from the specification to the List of possible types and modifiers.

Adjust SemanticTokensService to LSP specification

---

org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/INode.java
org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/INodeReference.java
org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/GrammarElementsInterner.java
org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/impl/NodeModelBuilder.java
org.eclipse.xtext/src/org/eclipse/xtext/nodemodel/util/NodeModelUtils.java

Node lookup can be customized by implementing INodeReference on the EMF model. Node storage by means of specializing the NodeModelBuilder. Common operations on nodes by provding custom implementations of INode and overriding INode.utils().

Allow customizing the NodeModelUtils and the way to obtain an INode

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/builder/JavaEditorExtension.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/builder/JavaEditorExtension.java

Maybe due to a bug in Platform not correctly closing or saving editors.
This avoids the busy waiting loop and getting into an infinite loop.
The idea is to sleep a bit, giving the listener some time to create the event. Moreover, it gives up after a few retries.
The test becomes flaky when the but above appears, but at least it doesn't exhaust the CI CPU and does not get stuck.
Locally, I haven't seen significant performance changes during the execution.
Closes #2895

Avoid busy and possibly infinite loop in JavaEditorExtension

---

org.eclipse.xtext.builder.tests/META-INF/MANIFEST.MF
org.eclipse.xtext.builder.tests/plugin.xml
org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/impl/GH2920Test.java
org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/tests/internal/TestsActivatorCustom.java
org.eclipse.xtext.builder.tests/src/org/eclipse/xtext/builder/tests/ui/BuilderTestLanguageExecutableExtensionFactoryGH2920.java
org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/impl/XtextBuilder.java

Inconsistent handling of files in an output folder - full vs. incremental build

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/internal/XtextPluginImages.java

Closes #2807 
I could only test it manually.
I reproduced the problem using the steps of #2807; with this patch, the NPE is not thrown, and the code minings are correctly shown.

[2807] avoid NPE in XtextPluginImages when initialized from non-UI thread

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/XtendValidationTest.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/IssueCodes.java
org.eclipse.xtend.core/src/org/eclipse/xtend/core/validation/XtendValidator.java

Closes #2928 
The errors are now as follows (I took inspiration from JDT, which shows the error starting from the first duplicate on):

[Xtend] check for duplicate interface specification

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/validation/XtendValidationTest.java

Some additional verifications in Xtend tests to make sure nothing is broken by #2349 
Similar to those already merged in https://github.com/eclipse/xtext/pull/2873

Some additional checks in xtend validation tests

---

org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextDiagnosticConverter.java

Make Pattern and Splitter static fields so that they do not need to created every time a new DiagnosticConverter is injected.

Make Pattern and Splitter static fields

---

.github/workflows/maven.yml
Jenkinsfile
full-build.sh
full-deploy.sh
jenkins/milestone-deploy/Jenkinsfile
jenkins/nightly-deploy/Jenkinsfile
jenkins/release-deploy/Jenkinsfile
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/compiler/QuickDebugSourceInstallingCompilationParticipantTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/compiler/QuickDebugSourceInstallingCompilationParticipantTest.java
org.eclipse.xtend.maven.plugin/src/test/resources/it/compile/filesystemaccess/src/main/java/myannotation/MyAnnotation.xtend
org.eclipse.xtext.maven.plugin/src/test/java/org/eclipse/xtext/maven/plugin/XtextGeneratorIT.java

This contributes two main features:
- The Windows GitHub Actions workflow is re-enabled. It's slower than Linux but faster than macOS (about 1:10 instead of 1:30). Note that two tests had to be adjusted to deal with Windows eols
- By retrieving the home of the installed Maven wrapper, the same Maven wrapper installation is used to run all our Maven plugins ITs, enforcing consistency and reproducibility and allowing us to rely only on the wrapper instead of the possibly installed Maven (in Jenkins, I modified the workflows accordingly).

Re-enable Windows GitHub Actions and use Maven Wrapper also for Maven plugins ITs

---

org.eclipse.xtext.ide.tests/src/org/eclipse/xtext/ide/tests/server/UriExtensionsTest.java
org.eclipse.xtext.util/src/org/eclipse/xtext/util/UriExtensions.java

Fix incorrect encoding for URIs that contain escaped sequences and a fragment

---

org.eclipse.xtext.testlanguages/META-INF/MANIFEST.MF
org.eclipse.xtext.testlanguages/build.properties

Closes #2982 
First of all, I reproduced locally the problem of #2982 with Tycho 4.0.7; after applying the changes of this PR, the problem went away.
I think I understand what the problem was:
- `org.eclipse.xtext.tests` depends on `org.eclipse.emf.mwe2.launch` (see its MANIFEST)
- `org.eclipse.emf.mwe2.launch` depends on `org.eclipse.xtext.common.types`
- `org.eclipse.xtext.testlanguages` does the same
- `org.eclipse.xtext.tests` also depends on `org.eclipse.xtext.testlanguages`
In the reactor, `org.eclipse.xtext.testlanguages` is built before `org.eclipse.xtext.tests`, but `org.eclipse.xtext.common.types` is built later, since it is not a direct dependency. Thus, it is taken from the target platform through `org.eclipse.emf.mwe2.launch`. Since new we are building 2.35.0.M1, I guess …

Explicit dep on `org.eclipse.xtext.common.types` in `org.eclipse.xtext.testlanguages`

---

org.eclipse.xtend.doc/META-INF/MANIFEST.MF
org.eclipse.xtext.doc/META-INF/MANIFEST.MF

It is deprecated in favor of 'Bundle-ActivationPolicy: lazy', which is already present.

Remove deprecated Eclipse-LazyStart headers

---

org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/AbstractXtendFormatterTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/AnonymousClassFormatterTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/TypeVariableFormatterTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/XtendAnnotationTypeFormatterTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/XtendAnnotationsFormatterTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/XtendClassFormatterTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/XtendCommentFormatterTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/XtendEnumFormatterTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/XtendFileFormatterTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/XtendFormatterBugTests.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/XtendInterfaceFormatterTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/XtendOnelinersFormatterTest.xtend
org.eclipse.xtend.core.tests/src/org/eclipse/xtend/core/tests/formatting/XtendRichStringFormatterTest.xtend
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/AbstractXtendFormatterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/AnonymousClassFormatterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/TypeVariableFormatterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendAnnotationTypeFormatterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendAnnotationsFormatterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendClassFormatterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendCommentFormatterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendEnumFormatterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendFileFormatterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendFormatterBugTests.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendInterfaceFormatterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendOnelinersFormatterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendRichStringFormatterTest.java
org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/formatter/AbstractFormatterTest.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/src/org/eclipse/xtext/example/domainmodel/tests/FormatterTest.xtend
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/tests/FormatterTest.java

- Add the org.eclipse.xtext.testing.AbstractFormatterTest class.
- Modify the FormatterTest class of the Domainmodel example to demonstrate the usage of the AbstractFormatterTest class.
- Modify the AbstractXtendFormatterTest base class to inherit from the newly created AbstractFormatterTest class and adapt the Xtend formatter test cases to use the inherited members/methods.
Closes #2965

Provide an abstract base class to be able to test the formatter.

---

org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/AnonymousClassFormatterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendAnnotationTypeFormatterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendAnnotationsFormatterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendClassFormatterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendEnumFormatterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendFileFormatterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendFormatterBugTests.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendInterfaceFormatterTest.java
org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/formatting/XtendOnelinersFormatterTest.java
org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.tests/xtend-gen/org/eclipse/xtext/example/domainmodel/tests/FormatterTest.java

concerning the changes applied here
https://github.com/eclipse/xtext/pull/2966#issuecomment-2033806041
Closes #2965

updated Xtend generated classes

---

org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/symbol/DocumentSymbolService.java

If one entry cannot be processed due to exceptions, catch such exceptions and log them, but still return other found references.

Catch exceptions while finding references

---

org.eclipse.xtext.builder.standalone.tests/build.properties
org.eclipse.xtext.extras.tests/META-INF/MANIFEST.MF_gen
org.eclipse.xtext.extras.tests/build.properties
org.eclipse.xtext.web.example.entities/pom.xml
org.eclipse.xtext.web.example.statemachine/pom.xml

Closes #2998
I also added the small chances after running generators

fixed generators for test and example languages

---

releng/org.eclipse.xtext.contributor/Xtext.setup

This should deal with the problem of always getting a clean build in Windows, each time you open the development workspace.
See https://github.com/eclipse/xtext/issues/2778#issuecomment-2071963236

Oomph clean build onlyNewProjects="true"

---

org.eclipse.xtend.core.tests/xtend-gen/org/eclipse/xtend/core/tests/macro/InsertParameterMiniHelperAnnoProcessor.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/TransformationContextImpl.java
org.eclipse.xtend.core/xtend-gen/org/eclipse/xtend/core/macro/ValidationContextImpl.java

After installing the new Xtend in Eclipse I get a few changed files.
While this https://github.com/eclipse/xtext/commit/341050e055a9054582e74efea4b2b0da781c2dda comes surely from https://github.com/eclipse/xtext/pull/2993 (cc @HannesWell) I'm not quite sure about https://github.com/eclipse/xtext/commit/bc51517d56ee56516c095a097875185c8f35cfc5. Can it be due to https://github.com/eclipse/xtext/pull/2784? (cc @dvojtise)

Regenerated Xtend files

---

org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/CompilationTestHelper.java
org.eclipse.xtext.xbase.tests/src/org/eclipse/xtext/xbase/tests/compiler/CompilationTestHelperTest.java

I often check for errors/issues when using CompilationTestHelper, and I always have to retrieve errors/warnings, do the filtering, and check for emptiness.
I thought adding such methods to `Result` would be worthwhile.
`assertNoWarnings` doesn't seem necessary to me, but I can add it in case.

assertNoErrors/Issues in CompilationTestHelper.Result

---

org.eclipse.xtext.java/src/org/eclipse/xtext/java/resource/IndexAwareNameEnvironment.java
org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/InMemoryJavaCompiler.java

Instantiate ClassFileReader via reflection

---

org.eclipse.xtext.java/src/org/eclipse/xtext/java/resource/IndexAwareNameEnvironment.java
org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/InMemoryJavaCompiler.java

This reverts commit 2e889ab89d01d6308bb9b9ffa28dbb4cfee58e5e.
Now that https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2578 has been merged, we don't need to use the reflection trick anymore.

Revert "Instantiate ClassFileReader via reflection"

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/AbstractLinkedEditingIntegrationTest.java
org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/refactoring/ToSaveOrNotToSaveTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/refactoring/LinkedEditingRefactoringIntegrationTest.java
org.eclipse.xtext.xtext.ui.tests/src-longrunning/org/eclipse/xtext/xtext/ui/refactoring/XtextGrammarRefactoringIntegrationTest.java

- Deprecate the `waitForDisplay()` method in the `AbstractLinkedEditingIntegrationTest` class in favor of the `waitForEventProcessing()` method in the `AbstractWorkbenchTest` class.
- Modify the test cases inherited from the `AbstractLinkedEditingIntegrationTest` base class to use the preferred method instead of the deprecated one.

Refactoring the AbstractLinkedEditingIntegrationTest test cases.

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/IResourcesSetupUtil.java

- Extend the IResourcesSetupUtil class by a createTempFile method that accepts a charset as a parameter to be able to configure the encoding.

[#2844] Add encoding to the IResourcesSetupUtil.createTempFile method.

---

org.eclipse.xtext.ui.codemining/src/org/eclipse/xtext/ui/codemining/AbstractXtextCodeMiningProvider.java

The NPE is happening when the Editor is closed and the worker thread is trying to access the document object, which is not existing anymore.
see https://github.com/eclipse/xtext/issues/3110

Fixed NPE when code minings are enabled and the editor closed

---

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/BuilderParticipant.java

The issue for this fix can be found here: [#2853]

Fix: Ensure xtext cleans all output folders even if previous output is missing

---

.github/workflows/maven.yml
Jenkinsfile
pom.xml

Now the profiles for Java 11 and Java 21 are explicit and will not disturb each other.
Since the profile for Java 21 is not activated automatically anymore, the GitHub Actions workflows have been updated accordingly.

support Java 21 in Jenkins

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/validation/XbaseUIValidator.java

See https://github.com/eclipse/Xpect/issues/353 #3123

use reflection to read perprojectinfo.rootPathToResolvedEntries

---

org.eclipse.xtext/src/org/eclipse/xtext/formatting2/internal/TextReplacerContext.java

When calculating the leading chars in a line, the replacer context iterates over all previous contexts if there are no replacements. This PR also uses the region of the associated replacer to find the beginning of the current line.
Furthermore, it avoids unnecessary text replacer contexts by returning the current context when the resulting context would be identical.
Closes #3119

Optimize performance of text replacer context with autowrap and already formatted document

---

Jenkinsfile
pom.xml

and rely on the toolchain to force compilation and tests with other Java versions.
I left comments to document what I think it's the semantics of those Jenkinsfile parts
Closes #3135

Deal with Java 11, 17, and 21 for the Jenkins build

---

.github/workflows/maven.yml

Without the -B Maven CLI option a lot of print-out in the build logs of Github workflows is just transfer progress.
The `full-Build.sh` uses the same arguments for a build in Jenkins.

Run GH workflow build in batch-mode and fail at end

---

.github/workflows/maven.yml
.github/workflows/unit-tests.yml

As suggested in https://github.com/eclipse/xtext/pull/3139#issuecomment-2280471647.
@cdietrich, @LorenzoBettini unfortunately this is only picked up after it is submitted to the main branch (since I don't have write access to this repo and the new workflow runs when another one is complted).
But as far as I can tell this is the same config as we use in
- m2e:  https://github.com/eclipse-m2e/m2e-core/tree/master/.github/workflows
- eclipse-platform/equinox/jdt/pde (a bit more convoluted): https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/.github/workflows

[Build] Set up publication of Test results as comment on pull-requests

---

.github/workflows/maven.yml

attempt to fix upload

---

.github/workflows/maven.yml

The 'Publish Unit Test Results' introduced with https://github.com/eclipse/xtext/pull/3144 will fail if test-failures are found.
- https://tycho.eclipseprojects.io/doc/4.0.8/tycho-surefire-plugin/test-mojo.html#testFailureIgnore
- https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#testfailureignore
The test-result should always be collected, otherwise the test result publication cannot show the number of passed tests.

[Build] Always collect test-results and don't fail on test-failures

---

org.eclipse.xtext.tests/src/org/eclipse/xtext/parser/unorderedGroups/GrammarParserTest.java
org.eclipse.xtext.tests/src/org/eclipse/xtext/xtext/XtextValidationTest.java
org.eclipse.xtext/src/org/eclipse/xtext/xtext/XtextValidator.java

To fix issue #3068 as hinted by @szarnekow 
Please let me know if I should add a test case (where and what should I test? I'm not familiar with Xtext tests at all).

Allow fragments in unordered groups

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring2/ChangeConverter.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring2/ReplaceFileContentChange.java

The verify is executed before the any change is performed. When the verify checks for the existance of files beforehand, this might not work for UNDO when there are move/rename is involved. Hence skipping the check for UNDO.
Signed-off-by: frank.rene.benoit@gmail.com

#2457 Disable verify in ReplaceFileContentChange for UNDO

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring2/rename/RenameElementProcessor2.java

The `target` field in `RenameElementProcessor2` is not initialized, since it is shadowed by a local variable in `initialize(IRenameElementContext)`. As a result, the target passed to `IRenameNameValidator.validate(...)` in `validateNewName(String)` is always `null`.
This commit removes the local variable, so that the field is properly initialized instead.
Closes #3132

Fix uninitialized target field in RenameElementProcessor2

---

.github/workflows/maven.yml

Even if the Publish-Test-Results job fails in that case too (but it's currently not completely working as expected).
See https://github.com/eclipse/xtext/pull/3144#issuecomment-2289992783.

[Build] Fail individual builds if test-failures occur

---

org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/clustering/CopiedResourceDescription.java
org.eclipse.xtext.ecore/src/org/eclipse/xtext/ecore/EcoreResourceDescriptionStrategy.java
org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/serializer/impl/EObjectDescriptionProvider.java
org.eclipse.xtext.testlanguages/src/org/eclipse/xtext/testlanguages/ecore/EcoreResourceDescriptionStrategy.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/StatefulResourceDescription.java
org.eclipse.xtext.xtext.generator/src/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.xtend
org.eclipse.xtext.xtext.generator/xtend-gen/org/eclipse/xtext/xtext/generator/XtextGeneratorTemplates.java
org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/AbstractTraceRegion.java
org.eclipse.xtext/src/org/eclipse/xtext/resource/SaveOptions.java

In Java-19 there is even static factory method `HashMap.newHashMap(int)` that can be used as a drop-in replacement once Java-19 or later is required.
For now I calculate the necessary capacity explicitly using the formula: `expected-size *4/3+1`.
The change in XtextGeneratorTemplates also removes the usage of `Maps.newHashMapWithExpectedSize()` of many generated Activators, but I haven't changed them manually. I assume they should be regenerated, shouldn't they?
Part of https://github.com/eclipse/xtext/issues/2975

Replace usage of Maps.newHashMapWithExpectedSize() with standard Java

---

.github/workflows/unit-tests.yml

Let's see whether the job does not fail when there are flaky tests

Update unit-tests.yml with fail_on

---

NOTICE.md
org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
org.eclipse.xtext.dev-bom/pom.xml
org.eclipse.xtext.p2repository/category.xml
org.eclipse.xtext.tests/testdata/wizard-expectations/full/full.parent/full.target/full.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoApp/lsMavenTychoApp.parent/lsMavenTychoApp.target/lsMavenTychoApp.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/lsMavenTychoFatjar/lsMavenTychoFatjar.parent/lsMavenTychoFatjar.target/lsMavenTychoFatjar.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTycho/mavenTycho.parent/mavenTycho.target/mavenTycho.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoJ17/mavenTychoJ17.parent/mavenTychoJ17.target/mavenTychoJ17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2/mavenTychoP2.parent/mavenTychoP2.target/mavenTychoP2.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J17/mavenTychoP2J17.parent/mavenTychoP2J17.target/mavenTychoP2J17.target.target
org.eclipse.xtext.tests/testdata/wizard-expectations/mavenTychoP2J21/mavenTychoP2J21.parent/mavenTychoP2J21.target/mavenTychoP2J21.target.target
org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.xtend
org.eclipse.xtext.xtext.wizard/xtend-gen/org/eclipse/xtext/xtext/wizard/TargetPlatformProject.java
xtext-latest.target
xtext-r202203.target
xtext-r202206.target
xtext-r202209.target
xtext-r202212.target
xtext-r202303.target
xtext-r202306.target
xtext-r202309.target
xtext-r202312.target
xtext-r202403.target
xtext-r202406.target
xtext-r202409.target

also using 0.0.0 as @merks keeps doing updates too often
(our 2.36 release is broken, but i wont have time for a hotfix) :(

another classgraph bump

---

org.eclipse.xtend.core/src/org/eclipse/xtend/core/jvmmodel/XtendJvmModelInferrer.java

Fixes https://github.com/eclipse/xtext/issues/3182

Only add @XbaseGenerated annotation if available

---

org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/editor/DirtyStateEditorSupportIntegrationTest.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextEditor.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocumentProvider.java

This bugfix contains the fix for unsync workspace files wrt. the file system (see the
DirtyStateEditorSupportIntegrationTest.testModifyFileInExternEditor) and a one liner for beeing able to save the file when the changes were ignored. (see the ignored test case
DirtyStateEditorSupportIntegrationTest.testModifyDirtyFileInExternEditor).
The issue for this fix can be found here:
https://github.com/eclipse/xtext/issues/2385

Fix editor sync bug, when model file was edited outside of eclipse.

---

.github/dependabot.yml
org.eclipse.xtext.common.types/META-INF/MANIFEST.MF
org.eclipse.xtext.dev-bom/pom.xml
xtext-latest.target
xtext-r202203.target
xtext-r202206.target
xtext-r202209.target
xtext-r202212.target
xtext-r202303.target
xtext-r202306.target
xtext-r202309.target
xtext-r202312.target
xtext-r202403.target
xtext-r202406.target
xtext-r202409.target

another classgraph bump 4.8.176

---

org.eclipse.xtext.java/src/org/eclipse/xtext/java/resource/JavaDerivedStateComputer.java
org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/InMemoryJavaCompiler.java

This should fix the compilation errors caused by removed CompilerOptions in Jdt.

Remove obsolete compiler option assignments

---

.github/dependabot.yml
NOTICE.md
org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml
xtext-latest.target
xtext-r202203.target
xtext-r202206.target
xtext-r202209.target
xtext-r202212.target
xtext-r202303.target
xtext-r202306.target
xtext-r202309.target
xtext-r202312.target
xtext-r202403.target
xtext-r202406.target
xtext-r202409.target

- from the target platform
- in NOTICE replaced patch version with `x`
- removed redundant version from an Xtext Maven plugin IT
NOTE: in other places, MANIFEST, feature and category, possible version bumps must still be done manually

Remove strict version of Guava in some places

---

org.eclipse.xtext/src/org/eclipse/xtext/EcoreUtil2.java

Hi, I'd like to propose this patch. Nothing special actually, simply since EcoreUtil2 already offers one variant of some of its methods for EObjects and one for Resources, I think this one could be handy as well. At the moment I'm working around its absence by using `EcoreUtil2.typeSelect(EcoreUtil2.eAllContentsAsList(resource), MyType.class)` extensively in my project, which works fine but looks quite verbose IMHO.

EcoreUtil2: Introduce getAllContentsOfType() for resources

---

org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/editor/DirtyStateEditorSupportIntegrationTest.java

added a sleep before assert.. Tested on redhat 9 .. works as before.. tested on mac sonoma 14.6.1 .. works as before.. Needs observation

fix for flaky editor sync test #2385

---

NOTICE.md
org.eclipse.xtext.dev-bom/pom.xml

Sorry, I didn't note the version in the BOM because it has a different name and the previous Maven artifact has version 9.7 instead of 9.7.0.
I hope you don't mind in the NOTICE I only put `.x`
Related to https://github.com/eclipse/xtext/issues/3224

bump org.objectweb.asm 9.7.1 also in BOM

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/ui/RenameLinkedMode.java

This patch fixes the issue when the user is entering the linked editing mode and looses the focus (happens because of showing up the popup dialog).

Fix for loosing focus when entering linked mode (rename element) #3245

---

.github/workflows/maven.yml
Jenkinsfile

Use Java 21 for the latest tp

---

org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF

Closes #3271
This way, just importing .xbase.testing ensures the new `TemporaryFolder` in .xtext.testing can be found at run-time while running compilation tests

re-export .xtext.testing

---

org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/editor/DirtyStateEditorSupportIntegrationTest.java

This patch adds a delay (waitForReconciler-method call before checking the document content) and it should fix the synchronization problem which causes flaky tests under mac os.

Testfailure fix for MacOS (DirtyStateEditorSupportIntegrationTest)

---

org.eclipse.xtext.xbase.ui/src/org/eclipse/xtext/xbase/ui/hover/XbaseInformationControl.java

eclipse.platform.ui https://github.com/eclipse-platform/eclipse.platform.ui/issues/2534
This patch is fixing the problem, where the HoverManagers listeners are deregistered but the hover is still visibile on top. This happens when the hover was sticky eclipse was minimized and put back on foreground after it. In that case the listeners are already deregistered and there is no chance to react at all. So for this case the visibility has to be set explicitly when the close is going to stop.

Bugfix for Hover which is visible above other application windows. 

---

full-build.sh
org.eclipse.xtend.maven.archetype/README.md
org.eclipse.xtend.maven.archetype/pom.xml
org.eclipse.xtend.maven.archetype/src/main/resources/META-INF/maven/archetype-metadata.xml
org.eclipse.xtend.maven.archetype/src/test/resources/projects/first/archetype.properties
org.eclipse.xtend.maven.parent/pom.xml
org.eclipse.xtend.maven.plugin/pom.xml

Closes #2258 
This also fixes the IT project, which was missing a required property

Re-enabled Integration tests for xtend-archetype

---

org.eclipse.xtext.ui.tests/src-longrunning/org/eclipse/xtext/ui/tests/editor/DirtyStateEditorSupportIntegrationTest.java

@LorenzoBettini @szarnekow If you are ok with this decision, we can merge this PR. Its disbaling the test for the mac operating system.

Disable DirtyStateEditorSupportIntegrationTest.testModifyFileInExternEditor() for mac operating system.

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextEditor.java

Allow Xtext editor subclasses to control highlighting, for example, to (temporarily) disable semantic highlighting in order to handle very large sources. This avoids having to resort to reflection to access these methods.
Closes https://github.com/eclipse/xtext/issues/3249

Allow Xtext editor subclasses to control highlighting

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/model/XtextDocument.java

Avoid unnecessarily aquiring a lock on the UI thread if there are no model listeners in the Xtext document.
Closes https://github.com/eclipse/xtext/issues/3251

Avoid unnecessary lock on UI thread with no model listeners

---

org.eclipse.xtend.ide.tests/longrunning/src/org/eclipse/xtend/ide/tests/refactoring/RenameStrategyTest.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/WorkbenchTestHelper.java
org.eclipse.xtend.performance.tests/src/org/eclipse/xtend/performance/tests/PerformanceTestProjectSetup.java
org.eclipse.xtext.common.types.eclipse.tests/tests/org/eclipse/xtext/common/types/access/jdt/MockJavaProjectProvider.java
org.eclipse.xtext.common.types.ui/src/org/eclipse/xtext/common/types/ui/refactoring/participant/TextChangeCombiner.java
org.eclipse.xtext.ui.codetemplates.ui/src/org/eclipse/xtext/ui/codetemplates/ui/contentassist/DummyTextViewer.java
org.eclipse.xtext.ui.codetemplates.ui/src/org/eclipse/xtext/ui/codetemplates/ui/preferences/AdvancedTemplatesPreferencePage.java
org.eclipse.xtext.ui.codetemplates.ui/src/org/eclipse/xtext/ui/codetemplates/ui/preferences/EditTemplateDialog.java
org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/JavaProjectSetupUtil.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/model/edit/AbstractTextEditComposerTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/editor/model/edit/ChangeSerializerComposerTest.java
org.eclipse.xtext.ui.tests/tests/org/eclipse/xtext/ui/tests/refactoring/UpdateAcceptorTest.java
org.eclipse.xtext.ui/deprecated/org/eclipse/xtext/ui/editor/contentassist/antlr/ParserBasedContentAssistContextFactory.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/embedded/EmbeddedEditorModelAccess.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/templates/XtextTemplateContextTypeRegistry.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/generator/trace/FileOpenerSelector.java
org.eclipse.xtext.xtext.ui.graph.tests/src/org/eclipse/xtext/xtext/ui/graph/tests/TransformationTest.java
org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/ecore2xtext/GrammarTest.java
org.eclipse.xtext.xtext.ui/src/org/eclipse/xtext/xtext/ui/wizard/ecore2xtext/EPackageChooser.java

Removed some deprecations/warnings

---

org.eclipse.xtext/src/org/eclipse/xtext/parsetree/reconstr/impl/TokenUtil.java

Since some of the implementations need to do some small computations to return the grammar element it is preferable to save the value in a local variable.

Remove repeated calls to INode#getGrammarElement

---

org.eclipse.xtext/src/org/eclipse/xtext/linking/lazy/LazyLinkingResource.java

By doing that, when resources already linked are loaded from storage, no memory needs to be allocated for the proxyInformation list.

Lazy creation of the list proxyInformation

---

org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/IResourcesSetupUtil.java

The boolean enable parameter was not used anyway: it must have been a copy and paste error

isAutobuild without parameters, deprecated the old one

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/compiler/QuickDebugSourceInstallingCompilationParticipantTest.java
org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/hover/XtendHoverInEditorTest.xtend
org.eclipse.xtend.ide.tests/xtend-gen/org/eclipse/xtend/ide/tests/hover/XtendHoverInEditorTest.java
org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/IResourcesSetupUtil.java
org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/InternalBuilderTest.java
org.eclipse.xtext.xtext.ui.tests/src/org/eclipse/xtext/xtext/ui/editor/quickfix/XtextGrammarQuickfixProviderTest.java

This should remove further flakyness
* `QuickDebugSourceInstallingCompilationParticipantTest`: in the end, it looks like the problem was that the generated `.class` Eclipse resource was not fully synchronized
* Some tests did not properly reset the autobuild state

Fixed a few other flaky tests

---

org.eclipse.xtend.ide/src/org/eclipse/xtend/ide/editor/OverrideIndicatorModelListener.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/XtextEditorErrorTickUpdater.java

Set fields to volatile which could possible be accessed by multiple threads. Used local variables to store the value and added check with local variable.

> #3339 NPE caused by null defaultImage in XtextEditorTickUpdater (updateEditorImage)

---

org.eclipse.xtend.ide.tests/src/org/eclipse/xtend/ide/tests/compiler/QuickDebugSourceInstallingCompilationParticipantTest.java
org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/generator/trace/TraceForStorageProvider.java
org.eclipse.xtext/src/org/eclipse/xtext/generator/trace/internal/AbstractTraceForURIProvider.java

Flaky QuickDebugSourceInstallingCompilationParticipantTest

---

org.eclipse.xtext/src/org/eclipse/xtext/linking/lazy/LazyLinkingResource.java

By doing that, when resources already linked are loaded from storage or when no cyclic resolution takes place, no
memory needs to be allocated for the set.

Lazy creation of the Set resolving

---

CONTRIBUTING.md

The workflow is a tad different in the newest versions of the Eclipse Installer. Also the orange badge doesn't seem to work as suggested anymore, it only opens the webpage where other buttons that actually trigger or configure the Installer can be found.

Update development environment setup instructions

---

org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/refactoring/ui/SyncUtil.java

when jdt.core is not available
Closes #3381

catch NoClassDefFoundError

---

org.eclipse.xtend.m2e/lifecycle-mapping-metadata.xml

Closes #3455
Unfortunately, I cannot put 2.40.0 in the version range, because we're still use SNAPSHOT

updated for the org.eclipse.xtext groupId

---

Builds.md
org.eclipse.xtend.core.tests/pom.xml
org.eclipse.xtend.core/pom.xml
org.eclipse.xtend.ide.common/pom.xml
org.eclipse.xtend.ide.swtbot.tests/pom.xml
org.eclipse.xtend.ide.tests/pom.xml
org.eclipse.xtend.ide/pom.xml
org.eclipse.xtend.lib.tests/pom.xml
org.eclipse.xtend.lib/pom.xml
org.eclipse.xtend.performance.tests/pom.xml
org.eclipse.xtext.purexbase/pom.xml
org.eclipse.xtext.testing/pom.xml
org.eclipse.xtext.tests/pom.xml
org.eclipse.xtext.xbase.lib.tests/pom.xml
org.eclipse.xtext.xbase/pom.xml
org.eclipse.xtext.xtext.generator/pom.xml
org.eclipse.xtext.xtext.wizard/pom.xml
pom.xml

- bootstrap against 2.40.0.M0
- uploaded the instructions for releasing
On a side note, just for testing, the first commit only updates the xtend-maven-plugin version without changing the groupId, just to check whether the build runs fine with relocations.

Remaining groupId org.eclipse.xtend
